`timescale 1ns / 1ps
// Generated by Claude Code, 2026-08-20
// =============================================================================
// dna_reader — Device DNA(칩 고유 57비트 ID)를 리셋 직후 1회 읽어 고정 출력
//
// [왜 만들었나 — 2026-08-20]
//   Zybo 보드가 2대(회사/집)인데 캡처 CSV에 어느 보드인지 기록이 없었다. 그래서
//   측정 데이터를 사후에 유효탭 수(299=집 / 284=회사)와 링 오실레이터 주파수로
//   추정해야 했고, 그 과정에서 "빌드마다 지연선이 달라진다"는 잘못된 결론까지 냈다.
//   (실제로는 칩이 달랐던 것. 2026-08-19_report.md §1-3 참조 — 그 서술은 정정 대상)
//
//   실측 근거:
//     집  보드  유효탭 299  LSB 16.722 ps   (8/04, 8/09, 8/12, 8/13)
//     회사 보드  유효탭 284  LSB 17.606 ps   (8/06 온도셋, 8/20)
//     같은 칩끼리 탭 폭 상관 r = 0.999 (빌드가 달라도), 다른 칩끼리 r = 0.54
//   CARRY4 80단과 샘플링 FF 320개가 tdc.xdc 로 같은 슬라이스에 고정돼 있으므로
//   탭 폭은 그 슬라이스의 실리콘이 결정한다. 즉 칩이 바뀌면 지연선이 바뀐다.
//
//   이 모듈을 ILA 프로브에 물리면 모든 캡처 CSV에 보드 식별자가 영구히 박힌다.
//
// [동작]
//   DNA_PORT 는 READ 로 57비트 DNA 를 시프트 레지스터에 적재하고, SHIFT 로 한
//   비트씩 DOUT 으로 내보낸다. 리셋 해제 후 한 번만 수행하고 이후 값을 고정한다.
//
// [비트 순서에 대하여]
//   보드 식별이 목적이므로 DOUT 을 받는 순서(MSB-first / LSB-first)는 중요하지
//   않다. 같은 칩이면 항상 같은 값이 나오고 다른 칩이면 다른 값이 나오기만 하면
//   된다. 여기서는 먼저 나온 비트를 상위로 넣는다. Xilinx 문서의 공식 DNA 값과
//   자릿수를 맞추려면 비트를 뒤집어야 할 수 있다 — 확인하지 않았다.
//
// [클럭]
//   DNA_PORT 의 CLK 최대 주파수를 확인하지 않았으므로 보수적으로 clk 를 CLK_DIV
//   로 나눈 저속 클럭을 만들어 쓴다 (기본 16분주 → 200 MHz 기준 12.5 MHz).
//   dna_clk 는 일반 배선을 타는 토글 레지스터다. 리셋 직후 1회성 동작이라
//   타이밍이 중요하지 않다. Vivado 가 CLOCK_DEDICATED_ROUTE 를 경고하면
//   tdc.xdc 에 다음을 추가할 것:
//     set_false_path -to [get_pins -hier -filter {NAME =~ *u_dna*DNA_PORT*/CLK}]
// =============================================================================

module dna_reader #(
    parameter integer CLK_DIV = 16        // dna_clk = clk / CLK_DIV
)(
    input  wire        clk,               // 시스템 클럭 (clk_200_fixed)
    input  wire        rst_n,             // 비동기 리셋 (clk_locked)
    output reg  [56:0] dna,               // 읽어낸 57비트 Device DNA
    output reg         dna_valid          // 1 = 읽기 완료, dna 유효 (이후 고정)
);

    localparam integer HALF = (CLK_DIV / 2) - 1;   // 반주기 카운트 종단값

    // -------------------------------------------------------------
    // 저속 클럭 생성 — dna_clk 는 DNA_PORT.CLK 로 나간다
    // -------------------------------------------------------------
    reg [15:0] div_cnt;
    reg        dna_clk;
    wire       half_tick = (div_cnt == HALF[15:0]);
    wire       dna_clk_fall = half_tick & dna_clk;   // 다음 사이클에 1->0

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            div_cnt <= 16'd0;
            dna_clk <= 1'b0;
        end else if (half_tick) begin
            div_cnt <= 16'd0;
            dna_clk <= ~dna_clk;
        end else begin
            div_cnt <= div_cnt + 16'd1;
        end
    end

    // -------------------------------------------------------------
    // FSM — clk 도메인에서 돌고, 상태 전이는 dna_clk 하강에서만 한다.
    //   dna_clk 상승 엣지를 DNA_PORT 가 소비한 '뒤'에 DOUT 을 받기 위함.
    // -------------------------------------------------------------
    localparam [1:0] S_WAIT = 2'd0, S_READ = 2'd1, S_SHIFT = 2'd2, S_DONE = 2'd3;

    reg [1:0]  state;
    reg [5:0]  bit_cnt;      // 0 ~ 56 (57비트)
    reg [3:0]  wait_cnt;     // 리셋 후 안정화 대기
    reg        dna_read;
    reg        dna_shift;

    wire       dna_dout;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state     <= S_WAIT;
            bit_cnt   <= 6'd0;
            wait_cnt  <= 4'd0;
            dna_read  <= 1'b0;
            dna_shift <= 1'b0;
            dna       <= 57'd0;
            dna_valid <= 1'b0;
        end else if (dna_clk_fall) begin
            case (state)
                // 리셋 해제 후 dna_clk 몇 주기 대기 (안정화)
                S_WAIT: begin
                    if (wait_cnt == 4'd7) begin
                        dna_read <= 1'b1;      // 다음 상승 엣지에서 DNA 적재
                        state    <= S_READ;
                    end else begin
                        wait_cnt <= wait_cnt + 4'd1;
                    end
                end

                // READ 상승 엣지가 지나갔다 -> DOUT 에 첫 비트가 나와 있다
                S_READ: begin
                    dna_read  <= 1'b0;
                    dna_shift <= 1'b1;
                    dna       <= {dna[55:0], dna_dout};   // 1번째 비트
                    bit_cnt   <= 6'd1;
                    state     <= S_SHIFT;
                end

                // 나머지 56비트를 하강마다 받는다
                S_SHIFT: begin
                    dna <= {dna[55:0], dna_dout};
                    if (bit_cnt == 6'd56) begin
                        dna_shift <= 1'b0;
                        dna_valid <= 1'b1;
                        state     <= S_DONE;
                    end else begin
                        bit_cnt <= bit_cnt + 6'd1;
                    end
                end

                // 완료 — 값을 영구히 유지한다
                S_DONE: begin
                    dna_shift <= 1'b0;
                    dna_read  <= 1'b0;
                end

                default: state <= S_WAIT;
            endcase
        end
    end

    // -------------------------------------------------------------
    // DNA_PORT 프리미티브 (7-series)
    // -------------------------------------------------------------
    DNA_PORT #(
        .SIM_DNA_VALUE(57'h0AAAAAAAAAAAAAA)   // 시뮬레이션 전용. 실 하드웨어와 무관
    ) u_dna_port (
        .DOUT  (dna_dout),
        .CLK   (dna_clk),
        .DIN   (1'b0),
        .READ  (dna_read),
        .SHIFT (dna_shift)
    );

endmodule
