// Generated by Claude Code, 2026-08-04
// -----------------------------------------------------------------------------
// tdc_fmcw_core_co — CARRY4 의 CO(캐리) 출력을 탭으로 사용하는 검증용 코어
//
// 원본 tdc_fmcw_core.v 는 그대로 두고, 탭 소스만 O(XOR) -> CO(캐리)로 바꾼 사본이다.
//
// [왜 만들었나 — 2026-08-04]
//   Vivado 타이밍 모델(get_timing_arcs, fast_min 코너, speed file -1)에서 읽은 값:
//       CI -> CO[3] = 40 ps   (MUXCY 4단 전부 통과)
//       CI -> O[0]  = 53 ps   (XOR 출력 1개)
//       CI -> O[1]  = 89 ps , CI -> O[2] = 66 ps , CI -> O[3] = 91 ps
//   즉 (1) 캐리가 4단을 다 지나가는 것보다 XOR 출력 하나가 더 느리고,
//      (2) O 도착 순서가 인덱스 순서가 아니다 (0, 2, 1, 3).
//   popcount 는 "1 이 된 탭의 개수"를 세므로 히스토그램 bin 번호는 물리 탭 번호가
//   아니라 "도착 순서 등수"가 된다. O 를 쓰는 한 이 permutation 을 알 수 없고,
//   동작 조건에 따라 순서가 바뀌면 bin<->탭 대응 자체가 흔들린다.
//   CO 는 CO[0] < CO[1] < CO[2] < CO[3] 이 직렬 캐리라 구조적으로 보장되므로
//   도착 순서 = 탭 번호가 되고 permutation 문제가 사라진다.
//
// [원본 대비 변경점은 아래 ★ 주석 3곳뿐이다]
//
// ============================================================================
// [2026-08-05 실측 결과 — 위 "단조성 보장" 근거는 틀렸다]
//   thermometer code 를 직접 떠서(임시 디버그 포트, 측정 후 제거) 확인한 결과:
//
//     실측 도착 순서 :  CO[1] -> CO[3] -> CO[2] -> CO[0]
//
//   즉 CO 도 단조가 아니다. 다만 무작위 bubble 이 아니라 **고정된 순열**이다 —
//   가능한 14 패턴 중 3 개만 나타나고, 0->1 전이가 %4==1 과 %4==3 에만 생긴다.
//   CO[3] 이 CO[0] 보다 먼저 도착하는 것은 직렬 리플에서 불가능하므로,
//   **7-series CARRY4 는 4단 리플이 아니라 캐리 look-ahead 구조**임이 확인됐다.
//
//   따라서 이 파일을 만든 근거 중 (2) "permutation 이 사라진다" 는 성립하지 않는다.
//   남는 근거는 (1) 뿐이다 — CO 경로가 XOR 경로보다 짧아 온도 변동 요소가 하나 준다.
//   그럼에도 실측 개선은 확실하다: INL p-p 155.8 -> 96.8 ps (-37.8 %, 빌드 통제 완료),
//   40->80 C 무보정 드리프트 69.7 -> 8.3 ps.  자세한 내용은 Markdown/2026-08-04_report.md
//   §2-7 (빌드 통제) / §2-8 (thermometer) / §3-5,§3-6 (온도) 참조.
// ============================================================================
//
// [빌드 방법]
//   tdc_test_top.v:218 의  `tdc_fmcw_core u_tdc (`  ->  `tdc_fmcw_core_co u_tdc (`
//   포트는 원본과 완전히 동일하므로 그 한 단어만 바꾸면 된다.
//   내부 인스턴스 이름(CARRY_CHAIN / STAGE_0 / STAGE_N / u_carry4 / u_ff_0..3 /
//   taps_sampled_d1)도 원본과 동일하게 유지했으므로 tdc.xdc 의 LOC/BEL 제약
//   2000여 줄이 수정 없이 그대로 적용된다.
// -----------------------------------------------------------------------------
`timescale 1ns / 1ps

module tdc_fmcw_core_co #(
    parameter CARRY4_STAGES = 80 // 80 * 4 = 320 Taps (5ns 커버)
)(
    input wire clk,
    input wire rst_n,
    input wire hit,

    output reg [31:0]  ts_coarse,
    output reg [8:0]   ts_fine_idx,
    output reg         ts_valid
);

localparam NUM_TAPS = CARRY4_STAGES * 4; // 320

(* keep = "true" *) wire [NUM_TAPS-1:0] carry_co;
(* keep = "true", dont_touch = "true" *) wire [NUM_TAPS-1:0] carry_o;
(* ASYNC_REG = "TRUE", DONT_TOUCH = "TRUE" *) wire [NUM_TAPS-1:0] taps_sampled;

// -------------------------------------------------------------------------
// 1. Dual Phase Coarse Counters
// -------------------------------------------------------------------------
reg [31:0] coarse_0;
reg [31:0] coarse_180;
reg [31:0] coarse_180_sync;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_0 <= 0;
    else coarse_0 <= coarse_0 + 1'b1;
end

always @(negedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180 <= 0;
    else coarse_180 <= coarse_0;
end

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180_sync <= 0;
    else coarse_180_sync <= coarse_180;
end

// -------------------------------------------------------------------------
// 2. 파이프라인 레지스터 (★ Hold 에러 방지 속성 추가 ★)
// -------------------------------------------------------------------------
(* DONT_TOUCH = "TRUE" *) reg [NUM_TAPS-1:0] taps_sampled_d1;
reg taps_sampled_0_history;

reg snapshot_valid_stg2, snapshot_valid_stg3, snapshot_valid_stg4;

// Vivado가 Shift Register로 압축하는 것을 막아 라우터가 배선 지연을 추가할 수 있게 돕습니다.
(* srl_style = "register" *) reg [31:0] captured_c0_stg2, captured_c180_stg2;
(* srl_style = "register" *) reg [31:0] captured_c0_stg3, captured_c180_stg3_plus1;
(* srl_style = "register" *) reg [31:0] captured_c0_stg4, captured_c180_stg4_plus1;

reg [8:0]  fine_idx_stg4;
reg        danger_zone_stg4;

reg [3:0] stg1_halfA [0:19];
reg [3:0] stg1_halfB [0:19];
reg [7:0] stg3_group0, stg3_group1, stg3_group2, stg3_group3;

integer i;

function [3:0] popcount8;
    input [7:0] din;
    begin
        popcount8 = din[0] + din[1] + din[2] + din[3] +
                    din[4] + din[5] + din[6] + din[7];
    end
endfunction

// -------------------------------------------------------------------------
// ★ 변경 2/3 (2026-08-04) — 탭 극성 반전을 조합으로 흡수
// -------------------------------------------------------------------------
//   S=4'b1111 이므로  O[j] = 1 XOR carry = ~carry ,  CO[j] = carry  로 서로 반대다.
//   원본(O 탭): hit 하강 -> 탭이 0->1 로 전파 -> popcount = "지나간 탭 수"
//   CO 탭     : 탭이 1->0 으로 전파       -> popcount = "아직 안 지나간 탭 수"
//
//   그래서 taps_eff = ~taps_sampled_d1 을 만들어 이후 로직이 원본과 완전히 같은
//   의미("지나간 탭 수")를 보게 한다.
//
//   ※ .D(~carry_co[...]) 로 탭 경로에 인버터를 넣으면 LUT1 이 끼어들어 CO 로 바꾼
//     이유(XOR 경로 제거)가 사라진다. 반드시 샘플링 FF 뒤에서 반전해야 하며,
//     여기서의 반전은 뒤따르는 popcount LUT 에 흡수되어 추가 지연이 없다.
//     taps_sampled_d1 자체는 반전하지 않는다 — tdc.xdc 가 taps_sampled_d1_reg 를
//     SLICE_X43Y* 에 고정해 두었고 그 사이에 LUT 를 넣으면 배치가 깨진다.
wire [NUM_TAPS-1:0] taps_eff = ~taps_sampled_d1;

// -------------------------------------------------------------------------
// 3. CARRY4 CHAIN
// -------------------------------------------------------------------------
(* keep = "true" *) wire rst_high = ~rst_n;
genvar k;
generate
    for (k = 0; k < CARRY4_STAGES; k = k + 1) begin : CARRY_CHAIN
        if (k == 0) begin : STAGE_0
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(1'b0), .CYINIT(hit), .DI(4'b0000), .S(4'b1111));
        end else begin : STAGE_N
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(carry_co[(k*4)-1]), .CYINIT(1'b0), .DI(4'b0000), .S(4'b1111));
        end
        // ★ 변경 1/3 (2026-08-04) — 탭 소스를 carry_o(XOR) 에서 carry_co(캐리) 로 교체.
        //    이유는 파일 상단 주석 참조. FF 이름/BEL 은 원본과 동일하게 유지해야
        //    tdc.xdc 의 LOC/BEL 제약이 그대로 걸린다.
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_0 ( .Q(taps_sampled[(k*4)+0]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+0]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_1 ( .Q(taps_sampled[(k*4)+1]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+1]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_2 ( .Q(taps_sampled[(k*4)+2]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+2]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_3 ( .Q(taps_sampled[(k*4)+3]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+3]) );
    end
endgenerate

// -------------------------------------------------------------------------
// 4. MAIN LOGIC 파이프라인
// -------------------------------------------------------------------------
localparam DEAD_TIME_CYCLES = 2;
reg [3:0] dead_time_cnt;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        taps_sampled_d1 <= 0; taps_sampled_0_history <= 0; dead_time_cnt <= 0;
        snapshot_valid_stg2 <= 0; snapshot_valid_stg3 <= 0; snapshot_valid_stg4 <= 0;
        captured_c0_stg2 <= 0; captured_c180_stg2 <= 0;
        captured_c0_stg3 <= 0; captured_c180_stg3_plus1 <= 0;
        captured_c0_stg4 <= 0; captured_c180_stg4_plus1 <= 0;
        fine_idx_stg4 <= 0; danger_zone_stg4 <= 0;
        ts_coarse <= 0; ts_valid <= 0; ts_fine_idx <= 0;
        stg3_group0 <= 0; stg3_group1 <= 0; stg3_group2 <= 0; stg3_group3 <= 0;
        for (i = 0; i < 20; i = i + 1) begin
            stg1_halfA[i] <= 0; stg1_halfB[i] <= 0;
        end
    end
    else begin
        // [Stage 1]
        taps_sampled_d1 <= taps_sampled;
        // ★ 변경 3/3 (2026-08-04) — 아래 taps_sampled_d1[...] 참조를 전부 taps_eff[...] 로 교체.
        //    hit 하강 시 CO 탭은 1->0 이므로 taps_eff[0] 의 상승이 원본 taps_sampled_d1[0]
        //    상승과 같은 사건(= 캐리 프론트가 탭 0 을 통과)을 가리킨다.
        //    stage 0 은 CYINIT=hit, S=1 이므로 CO[0]=hit, 즉 taps_eff[0]=~hit 로
        //    원본(O[0]=~hit)과 동일 — 하강 에지 검출 의미가 그대로 보존된다.
        taps_sampled_0_history <= taps_eff[0];

        // [Stage 2]
        if (dead_time_cnt > 0) begin
            dead_time_cnt <= dead_time_cnt - 1'b1;
            snapshot_valid_stg2 <= 1'b0;
        end
        else if (taps_eff[0] && !taps_sampled_0_history) begin
            dead_time_cnt <= DEAD_TIME_CYCLES;

            captured_c0_stg2   <= coarse_0;
            captured_c180_stg2 <= coarse_180_sync;

            for (i = 0; i < 20; i = i + 1) begin
                stg1_halfA[i] <= popcount8(taps_eff[i*16 +: 8]);
                stg1_halfB[i] <= popcount8(taps_eff[i*16+8 +: 8]);
            end
            snapshot_valid_stg2 <= 1'b1;
        end else begin
            snapshot_valid_stg2 <= 1'b0;
        end

        // [Stage 3]
        if (snapshot_valid_stg2) begin
            stg3_group0 <= stg1_halfA[0]+stg1_halfB[0] + stg1_halfA[1]+stg1_halfB[1] + stg1_halfA[2]+stg1_halfB[2] + stg1_halfA[3]+stg1_halfB[3] + stg1_halfA[4]+stg1_halfB[4];
            stg3_group1 <= stg1_halfA[5]+stg1_halfB[5] + stg1_halfA[6]+stg1_halfB[6] + stg1_halfA[7]+stg1_halfB[7] + stg1_halfA[8]+stg1_halfB[8] + stg1_halfA[9]+stg1_halfB[9];
            stg3_group2 <= stg1_halfA[10]+stg1_halfB[10] + stg1_halfA[11]+stg1_halfB[11] + stg1_halfA[12]+stg1_halfB[12] + stg1_halfA[13]+stg1_halfB[13] + stg1_halfA[14]+stg1_halfB[14];
            stg3_group3 <= stg1_halfA[15]+stg1_halfB[15] + stg1_halfA[16]+stg1_halfB[16] + stg1_halfA[17]+stg1_halfB[17] + stg1_halfA[18]+stg1_halfB[18] + stg1_halfA[19]+stg1_halfB[19];

            captured_c0_stg3 <= captured_c0_stg2;
            captured_c180_stg3_plus1 <= captured_c180_stg2 + 1'b1;

            snapshot_valid_stg3 <= 1'b1;
        end else begin
            snapshot_valid_stg3 <= 1'b0;
        end

        // [Stage 4]
        if (snapshot_valid_stg3) begin
            begin : CALC_FINE
                reg [8:0] sum_fine;
                sum_fine = stg3_group0 + stg3_group1 + stg3_group2 + stg3_group3;
                fine_idx_stg4 <= sum_fine;

                // ★ 데이터 기반 Threshold 적용 구역 (40, 220)
                //   [2026-08-04 주의] 이 값은 O 탭 분포로 튜닝된 것이다. CO 탭은
                //   탭당 폭 분포가 달라지므로 첫 측정 후 재튜닝이 필요할 수 있다.
                //   지금은 원본과 동일 조건으로 비교하기 위해 그대로 둔다.
                danger_zone_stg4 <= (sum_fine < 9'd40 || sum_fine > 9'd220);
            end

            captured_c0_stg4 <= captured_c0_stg3;
            captured_c180_stg4_plus1 <= captured_c180_stg3_plus1;
            snapshot_valid_stg4 <= 1'b1;
        end else begin
            snapshot_valid_stg4 <= 1'b0;
        end

        // [Stage 5]
        if (snapshot_valid_stg4) begin
            ts_fine_idx <= fine_idx_stg4;

            if (danger_zone_stg4) begin
                ts_coarse <= captured_c180_stg4_plus1;
            end else begin
                ts_coarse <= captured_c0_stg4;
            end

            ts_valid <= 1'b1;
        end else begin
            ts_valid <= 1'b0;
        end
    end
end
endmodule
