// Generated by Claude Code, 2026-08-12
// -----------------------------------------------------------------------------
// ★★★ 임시 측정용 파일 — 측정이 끝나면 이 파일은 쓰지 말 것 ★★★
//
// tdc_fmcw_core_mix_thermo — tdc_fmcw_core_mix.v 에 thermometer 디버그 출력만 추가한 사본.
// 원본 tdc_fmcw_core_mix.v 는 건드리지 않았다. 측정이 끝나면 top 에서 모듈명을
// tdc_fmcw_core_mix 로 되돌리기만 하면 되고, 이 파일은 지워도 된다.
//
// =============================================================================
// [무엇을 재려는가 — 2026-08-12]
//
//   MIX_MODE=1 빌드(CO[0], CO[1], O[2], CO[3])의 히스토그램 실측 네 구간은
//       8.72 / 11.14 / 23.52 / 23.87 ps  (표준편차 8.01)
//   인데, 이것만으로는 d2 를 확정할 수 없다.
//
//   d2 = CO[1] 이 확정된 뒤 O[2] 가 확정되기까지의 시간 [ps].
//        O[2] = ~CO[1] (UG474) 이므로 O[2] 는 CO[1] 을 XOR 게이트 하나 지연시킨 복사본이고,
//        d2 가 곧 그 지연이다. 탭으로 쓰면 CO[1]→CO[3] 사이 31.08 ps 구간을
//        d2 와 (31.08 - d2) 로 쪼갠다.
//
//   히스토그램은 '구간의 길이'만 주고 '어느 구간이 어느 것인지'는 안 준다.
//   {d2, 31.08-d2} 는 15.54 를 축으로 대칭이라 표준편차로는 두 해가 구분되지 않는다:
//       d2 =  7.0 ps  ->  구간이  7.0 / 24.1 / 23.74 / 16.28
//       d2 = 24.1 ps  ->  구간이 24.1 /  7.0 / 23.74 / 16.28
//   둘 다 도착 '순서'도 같다 (CO[1] -> O[2] -> CO[3] -> CO[0]).
//
//   ★ 그러나 '체류 시간'은 뒤바뀐다. thermometer 로 CARRY4 4비트를 직접 보면
//     "CO[1] 만 1 이고 나머지 셋은 0" 인 상태에 머무는 비율 = d2 / 71.10 이다.
//     그 비율을 세면 d2 가 직접 나온다.
//
//   왜 중요한가: d2 가 큰 쪽이면 16조합 중 OOCO 가 5.45 ps 로 지금(CCOC, 8.01)보다
//   훨씬 균등해진다. 작은 쪽이면 지금이 이미 1위다. 다음 빌드를 정하는 갈림길이다.
//
// [읽는 법]
//   dbg_thermo[i] = taps_eff[64+i]  (탭 64~111 = CARRY4 스테이지 16~27, 12개)
//   taps_eff 는 극성 보정 후 값이라 1 = "파면이 이 탭을 지나갔다" 로 통일돼 있다.
//   CARRY4 하나는 4비트 묶음이고, 묶음 안의 비트 j 는 u_ff_j 가 받는 신호다:
//       비트 0 = CO[0] ,  비트 1 = CO[1] ,  비트 2 = O[2] ,  비트 3 = CO[3]
//   (MIX_MODE=1 기준. MIX_MODE=0 이면 비트2=CO[2], 비트3=O[2] 이지만 그 모드는
//    BEL 충돌로 배치가 안 된다.)
//
//   예상 부분 패턴 (파면이 CARRY4 안에 있을 때 셋만 나와야 한다):
//       0100            CO[1] 만        -> 체류 = d2
//       0110            CO[1], O[2]     -> 체류 = 31.08 - d2
//       1110  아니고 0111  CO[1],O[2],CO[3] -> 체류 = 23.74
//   그 외 11가지가 나오면 순서 가정이 틀린 것이므로 재해석해야 한다.
//
// [측정 방법 — 2026-08-09 와 동일]
//   Mode 1 (링 오실레이터). ILA storage qualification 을 dbg_valid 로 걸어
//   파면이 창 안에 있는 순간만 저장한다. 1024 샘플이면 충분하다.
//   probe0(1비트) / probe3(48비트) 를 재활용하므로 ILA IP 재생성이 필요 없다.
//
// [원복]
//   top 의 모듈명을 tdc_fmcw_core_mix 로 되돌리고, top 의 ★임시★ 블록 2곳을
//   되살리면 끝이다. 이 파일 자체는 수정할 것이 없다.
// =============================================================================
`timescale 1ns / 1ps

module tdc_fmcw_core_mix_thermo #(
    parameter CARRY4_STAGES = 80, // 80 * 4 = 320 Taps (5ns 커버)
    // 0 = CO[0],CO[1],CO[2],O[2]  (성능 최선, 위치 2 충돌 위험)
    // 1 = CO[0],CO[1],O[2],CO[3]  (위치당 하나씩, 안전)
    parameter MIX_MODE = 0
)(
    input wire clk,
    input wire rst_n,
    input wire hit,

    output reg [31:0]  ts_coarse,
    output reg [8:0]   ts_fine_idx,
    output reg         ts_valid,

    // ★임시★ thermometer 디버그 (측정 후 이 파일째로 폐기)
    output wire [47:0] dbg_thermo,   // taps_eff[64+:48] = 탭 64~111 (CARRY4 12개)
    output wire        dbg_valid     // 파면이 이 창 안에 있음 (ILA storage qualification)
);

localparam NUM_TAPS = CARRY4_STAGES * 4; // 320

(* keep = "true" *) wire [NUM_TAPS-1:0] carry_co;
(* keep = "true", dont_touch = "true" *) wire [NUM_TAPS-1:0] carry_o;
(* ASYNC_REG = "TRUE", DONT_TOUCH = "TRUE" *) wire [NUM_TAPS-1:0] taps_sampled;

// 자리별 탭 소스 (CO 또는 O 중 하나가 상수 선택으로 연결된다. 3. CARRY4 CHAIN 참조)
wire [NUM_TAPS-1:0] tap_src;

// -------------------------------------------------------------------------
// 1. Dual Phase Coarse Counters
// -------------------------------------------------------------------------
reg [31:0] coarse_0;
reg [31:0] coarse_180;
reg [31:0] coarse_180_sync;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_0 <= 0;
    else coarse_0 <= coarse_0 + 1'b1;
end

always @(negedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180 <= 0;
    else coarse_180 <= coarse_0;
end

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180_sync <= 0;
    else coarse_180_sync <= coarse_180;
end

// -------------------------------------------------------------------------
// 2. 파이프라인 레지스터
// -------------------------------------------------------------------------
(* DONT_TOUCH = "TRUE" *) reg [NUM_TAPS-1:0] taps_sampled_d1;
reg taps_sampled_0_history;

reg snapshot_valid_stg2, snapshot_valid_stg3, snapshot_valid_stg4;

// Vivado가 Shift Register로 압축하는 것을 막아 라우터가 배선 지연을 추가할 수 있게 돕습니다.
(* srl_style = "register" *) reg [31:0] captured_c0_stg2, captured_c180_stg2;
(* srl_style = "register" *) reg [31:0] captured_c0_stg3, captured_c180_stg3_plus1;
(* srl_style = "register" *) reg [31:0] captured_c0_stg4, captured_c180_stg4_plus1;

reg [8:0]  fine_idx_stg4;
reg        danger_zone_stg4;

reg [3:0] stg1_halfA [0:19];
reg [3:0] stg1_halfB [0:19];
reg [7:0] stg3_group0, stg3_group1, stg3_group2, stg3_group3;

integer i;

function [3:0] popcount8;
    input [7:0] din;
    begin
        popcount8 = din[0] + din[1] + din[2] + din[3] +
                    din[4] + din[5] + din[6] + din[7];
    end
endfunction

// -------------------------------------------------------------------------
// ★ 변경 1/2 (2026-08-12) — 탭 극성 반전을 "자리별"로 바꿈
// -------------------------------------------------------------------------
//   tdc_fmcw_core_co.v 는 네 자리가 모두 CO 라  taps_eff = ~taps_sampled_d1  한 줄이면
//   됐다. 이 빌드는 한 자리만 O 탭이라 자리마다 극성이 다르다:
//
//     CO 탭 : taps_sampled = carry        -> 반전 필요 (~)
//     O  탭 : taps_sampled = ~carry       -> 이미 원본(O 빌드) 극성. 반전하면 안 됨
//
//   O 탭이 들어가는 자리는 MIX_MODE 에 따라 다르다 (아래 O_POS).
//   반전은 반드시 샘플링 FF 뒤에서 해야 한다. .D(~...) 로 넣으면 LUT1 이 끼어들어
//   탭 경로가 길어지고 이 실험의 전제가 깨진다. 여기서의 반전은 뒤따르는 popcount
//   LUT 에 흡수되어 추가 지연이 없다. taps_sampled_d1 자체는 반전하지 않는다 —
//   tdc.xdc 가 taps_sampled_d1_reg 를 SLICE_X43Y* 에 고정해 두었기 때문이다.
//   ※ generate 로 자리마다 assign 을 만들면 이름 있는 생성 스코프가 하나 더 생겨
//     계층 경로가 바뀐다. tdc.xdc 에 정확 경로 지정([get_cells {u_tdc/CARRY_CHAIN[0].u_ff_2}])
//     이 있으므로 스코프를 늘리면 안 된다. 그래서 상수 마스크로 처리한다.
//
//     O_MASK4 의 비트 j = "자리 j 가 O 탭인가".  이걸 80번 반복해 320비트를 만든다.
localparam [3:0] O_MASK4 = (MIX_MODE == 0) ? 4'b1000 : 4'b0100;  // MIX0: 자리3 / MIX1: 자리2
wire [NUM_TAPS-1:0] o_mask = {CARRY4_STAGES{O_MASK4}};

//   mask=1 (O 탭)  -> ~mask=0 -> XOR 0 = 그대로
//   mask=0 (CO 탭) -> ~mask=1 -> XOR 1 = 반전
wire [NUM_TAPS-1:0] taps_eff = taps_sampled_d1 ^ ~o_mask;

// ★임시★ thermometer 출력 — taps_eff 는 극성 보정 후 값이므로 1 = "파면이 지나감".
//   taps_sampled_d1 이 레지스터라 한 클록 동안 안정하다. ILA 가 그대로 받으면 된다.
//   dbg_valid : 창이 전부 0 도 전부 1 도 아닌 순간 = 파면이 창 안에 있는 순간.
assign dbg_thermo = taps_eff[64 +: 48];
assign dbg_valid  = (|dbg_thermo) & ~(&dbg_thermo);

// -------------------------------------------------------------------------
// 3. CARRY4 CHAIN
// -------------------------------------------------------------------------
(* keep = "true" *) wire rst_high = ~rst_n;
genvar k;
generate
    for (k = 0; k < CARRY4_STAGES; k = k + 1) begin : CARRY_CHAIN
        if (k == 0) begin : STAGE_0
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(1'b0), .CYINIT(hit), .DI(4'b0000), .S(4'b1111));
        end else begin : STAGE_N
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(carry_co[(k*4)-1]), .CYINIT(1'b0), .DI(4'b0000), .S(4'b1111));
        end

        // ★ 변경 2/2 (2026-08-12) — 네 탭 중 한 자리만 O[2] 로 교체.
        //    O[2] = ~CO[1] + XOR지연 이므로 CO[1] 직후에 뜬다 → 31.08 ps 구간을 쪼갠다.
        //    나머지 세 자리는 tdc_fmcw_core_co.v 와 동일한 CO 탭이다.
        //    FF 이름/BEL 은 원본과 동일하게 유지해야 tdc.xdc 제약이 그대로 걸린다.
        //    MIX_MODE 는 파라미터라 아래 삼항연산자는 합성 시 상수로 접혀 단순 배선만
        //    남는다(LUT 생기지 않음). generate-if 를 쓰지 않는 이유는 위 극성 주석 참조 —
        //    생성 스코프가 늘면 tdc.xdc 의 정확 경로 제약이 깨진다.
        assign tap_src[(k*4)+0] = carry_co[(k*4)+0];                                    // CO[0]
        assign tap_src[(k*4)+1] = carry_co[(k*4)+1];                                    // CO[1]
        assign tap_src[(k*4)+2] = (MIX_MODE == 0) ? carry_co[(k*4)+2] : carry_o [(k*4)+2];
        assign tap_src[(k*4)+3] = (MIX_MODE == 0) ? carry_o [(k*4)+2] : carry_co[(k*4)+3];

        (* DONT_TOUCH = "TRUE" *) FDC u_ff_0 ( .Q(taps_sampled[(k*4)+0]), .C(clk), .CLR(rst_high), .D(tap_src[(k*4)+0]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_1 ( .Q(taps_sampled[(k*4)+1]), .C(clk), .CLR(rst_high), .D(tap_src[(k*4)+1]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_2 ( .Q(taps_sampled[(k*4)+2]), .C(clk), .CLR(rst_high), .D(tap_src[(k*4)+2]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_3 ( .Q(taps_sampled[(k*4)+3]), .C(clk), .CLR(rst_high), .D(tap_src[(k*4)+3]) );
    end
endgenerate

// -------------------------------------------------------------------------
// 4. MAIN LOGIC 파이프라인  (tdc_fmcw_core_co.v 와 완전히 동일)
// -------------------------------------------------------------------------
localparam DEAD_TIME_CYCLES = 2;
reg [3:0] dead_time_cnt;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        taps_sampled_d1 <= 0; taps_sampled_0_history <= 0; dead_time_cnt <= 0;
        snapshot_valid_stg2 <= 0; snapshot_valid_stg3 <= 0; snapshot_valid_stg4 <= 0;
        captured_c0_stg2 <= 0; captured_c180_stg2 <= 0;
        captured_c0_stg3 <= 0; captured_c180_stg3_plus1 <= 0;
        captured_c0_stg4 <= 0; captured_c180_stg4_plus1 <= 0;
        fine_idx_stg4 <= 0; danger_zone_stg4 <= 0;
        ts_coarse <= 0; ts_valid <= 0; ts_fine_idx <= 0;
        stg3_group0 <= 0; stg3_group1 <= 0; stg3_group2 <= 0; stg3_group3 <= 0;
        for (i = 0; i < 20; i = i + 1) begin
            stg1_halfA[i] <= 0; stg1_halfB[i] <= 0;
        end
    end
    else begin
        // [Stage 1]
        taps_sampled_d1 <= taps_sampled;
        // taps_eff[0] 은 자리 0 = CO[0] 탭이므로 반전된 값이다.
        // stage 0 은 CYINIT=hit, S=1 이므로 CO[0]=hit, 즉 taps_eff[0]=~hit 로
        // 원본(O 빌드의 O[0]=~hit)과 동일 — 하강 에지 검출 의미가 보존된다.
        taps_sampled_0_history <= taps_eff[0];

        // [Stage 2]
        if (dead_time_cnt > 0) begin
            dead_time_cnt <= dead_time_cnt - 1'b1;
            snapshot_valid_stg2 <= 1'b0;
        end
        else if (taps_eff[0] && !taps_sampled_0_history) begin
            dead_time_cnt <= DEAD_TIME_CYCLES;

            captured_c0_stg2   <= coarse_0;
            captured_c180_stg2 <= coarse_180_sync;

            for (i = 0; i < 20; i = i + 1) begin
                stg1_halfA[i] <= popcount8(taps_eff[i*16 +: 8]);
                stg1_halfB[i] <= popcount8(taps_eff[i*16+8 +: 8]);
            end
            snapshot_valid_stg2 <= 1'b1;
        end else begin
            snapshot_valid_stg2 <= 1'b0;
        end

        // [Stage 3]
        if (snapshot_valid_stg2) begin
            stg3_group0 <= stg1_halfA[0]+stg1_halfB[0] + stg1_halfA[1]+stg1_halfB[1] + stg1_halfA[2]+stg1_halfB[2] + stg1_halfA[3]+stg1_halfB[3] + stg1_halfA[4]+stg1_halfB[4];
            stg3_group1 <= stg1_halfA[5]+stg1_halfB[5] + stg1_halfA[6]+stg1_halfB[6] + stg1_halfA[7]+stg1_halfB[7] + stg1_halfA[8]+stg1_halfB[8] + stg1_halfA[9]+stg1_halfB[9];
            stg3_group2 <= stg1_halfA[10]+stg1_halfB[10] + stg1_halfA[11]+stg1_halfB[11] + stg1_halfA[12]+stg1_halfB[12] + stg1_halfA[13]+stg1_halfB[13] + stg1_halfA[14]+stg1_halfB[14];
            stg3_group3 <= stg1_halfA[15]+stg1_halfB[15] + stg1_halfA[16]+stg1_halfB[16] + stg1_halfA[17]+stg1_halfB[17] + stg1_halfA[18]+stg1_halfB[18] + stg1_halfA[19]+stg1_halfB[19];

            captured_c0_stg3 <= captured_c0_stg2;
            captured_c180_stg3_plus1 <= captured_c180_stg2 + 1'b1;

            snapshot_valid_stg3 <= 1'b1;
        end else begin
            snapshot_valid_stg3 <= 1'b0;
        end

        // [Stage 4]
        if (snapshot_valid_stg3) begin
            begin : CALC_FINE
                reg [8:0] sum_fine;
                sum_fine = stg3_group0 + stg3_group1 + stg3_group2 + stg3_group3;
                fine_idx_stg4 <= sum_fine;

                // [2026-08-12 주의] 이 (40, 220) 문턱은 O 탭 분포로 튜닝된 값이다.
                // 혼합 탭은 폭 분포가 또 달라지므로 첫 측정 후 재튜닝이 필요할 수 있다.
                // CO 빌드와 같은 조건으로 비교하기 위해 지금은 그대로 둔다.
                danger_zone_stg4 <= (sum_fine < 9'd40 || sum_fine > 9'd220);
            end

            captured_c0_stg4 <= captured_c0_stg3;
            captured_c180_stg4_plus1 <= captured_c180_stg3_plus1;
            snapshot_valid_stg4 <= 1'b1;
        end else begin
            snapshot_valid_stg4 <= 1'b0;
        end

        // [Stage 5]
        if (snapshot_valid_stg4) begin
            ts_fine_idx <= fine_idx_stg4;

            if (danger_zone_stg4) begin
                ts_coarse <= captured_c180_stg4_plus1;
            end else begin
                ts_coarse <= captured_c0_stg4;
            end

            ts_valid <= 1'b1;
        end else begin
            ts_valid <= 1'b0;
        end
    end
end
endmodule
