`timescale 1ns / 1ps
// =============================================================================
// tdc_seq.v  —  측정 시퀀서 FSM (1차: Mode 1 = 링오실레이터 코드밀도)
// Generated by Claude Code, 2026-09-05
//
//  [무엇인가]
//  PS 가 CTRL.START 를 쓰면 "RO 켜기 -> 주파수 재기 -> 안정화 -> 히스토그램
//  누적 -> 완료" 를 하드웨어가 알아서 순서대로 밟는다. 사람이 버튼을 누르거나
//  소프트웨어가 중간중간 개입할 필요가 없다.
//
//  [상태]  사용자 지정 6상태를 그대로 따른다.
//    S_IDLE       대기.                     -> START=1 이고 HIT_SRC=01 이면 진행
//    S_RO_ENABLE  RO 가동. 초기 트랜지언트 대기 (SETTLE_N 클럭)
//    S_MEAS_FREQ  RO 주파수 측정            -> 온전한 게이트 하나를 기다린다
//    S_STABILIZE  히스토그램 지우기 + 안정화 대기
//    S_HISTOGRAM  누적                      -> 목표 히트 도달 또는 STOP
//    S_DONE       DONE=1                    -> START=0 이 되면 IDLE 로
//
//  [★ 히트 수를 어떻게 세는가 — 여기가 제일 중요하다]
//  tdc_histogram 은 히트 하나를 넣는 데 4클럭이 걸린다
//  (IDLE -> RMW_R -> RMW_A -> RMW_W). ts_valid 를 보는 것은 IDLE 한 사이클뿐이라,
//  나머지 3클럭 동안 도착한 히트는 버려진다(데드타임 20 ns).
//  그래서 ts_valid 를 세면 BRAM 에 실제로 들어간 수보다 많아진다.
//  탭 폭을 w[i] = h[i]/H x 5000 ps 로 정의하므로 H 가 틀리면 모든 탭 폭이
//  그 비율만큼 통째로 틀어진다 — 폭의 합이 5000 ps 가 아니게 된다.
//    -> 그래서 histogram 이 "받아들였다"고 알려주는 hit_accepted 만 센다.
//       hit_cnt 는 PS 가 읽은 384탭의 합과 정확히 같아야 한다. 이 일치 여부가
//       곧 검증 항목이다.
//  버려진 수(hit_dropped)도 함께 센다. 데드타임 손실은 지금까지 추정값
//  (5초 614만발 기준 약 2.4%)뿐이었고 측정된 적이 없다.
//
//  [S_MEAS_FREQ 가 최대 20 ms 걸리는 이유]
//  RO 주파수 카운터는 FSM 과 무관하게 10 ms 게이트로 자유 실행 중이다
//  (tdc_test_top.v 의 GATE_CYCLES). 진입 시점이 게이트 중간일 수 있으므로,
//  첫 meas_strobe 로 경계를 잡고 그 다음 meas_strobe 를 기다린다. 그래야
//  RO 가 켜진 뒤 온전히 시작된 게이트 하나의 값을 얻는다. 최악 10+10 = 20 ms.
//
//  [클럭] 전부 tdc_clk(200 MHz) 도메인이다. ctrl_* 와 target_hits/settle_n 은
//  tdc_axi_regs 가 토글 핸드셰이크로 이미 이 도메인에 래치해서 준다.
// =============================================================================

module tdc_seq (
    input  wire        clk,              // tdc_clk (200 MHz)
    input  wire        rst_n,

    // ---- 제어 (AXI 도메인에서 이미 동기화되어 들어온다) ----
    input  wire        ctrl_start,
    input  wire        ctrl_stop,
    input  wire [1:0]  ctrl_hit_src,     // 00=off 01=RO 10=DPS 11=EXT
    input  wire [31:0] target_hits,      // 이만큼 모으면 끝낸다
    input  wire [31:0] settle_n,         // RO 안정화 대기 클럭 수

    // ---- 측정 조건 입력 ----
    input  wire        meas_strobe,      // 10 ms 게이트 완료 (1클럭)
    input  wire [31:0] ro_cnt,           // 그 게이트의 RO 에지 수
    input  wire [15:0] die_temp,         // 그 시점의 다이 온도 raw

    // ---- 히스토그램과 주고받는 신호 ----
    input  wire        hit_accepted,     // BRAM 에 실제로 반영된 히트 (1클럭)
    input  wire        hit_dropped,      // 데드타임에 버려진 히트 (1클럭)
    output reg         ro_en,            // 링오실레이터 가동
    output reg         histo_en,         // 누적 허용
    output reg         histo_clr,        // 지우기 (레벨)

    // ---- 상태 출력 ----
    output reg         busy,
    output reg         done,
    output reg  [2:0]  state_out,
    output reg  [31:0] hit_cnt,          // 실제 누적된 히트 수
    output reg  [31:0] drop_cnt,         // 버려진 히트 수
    output reg  [31:0] ro_at_start,
    output reg  [31:0] ro_at_end,
    output reg  [15:0] temp_at_start,
    output reg  [15:0] temp_at_end,
    output reg         snap_tgl          // 위 값들을 AXI 로 넘기는 CDC 토글
);

    localparam [2:0] S_IDLE      = 3'd0,
                     S_RO_ENABLE = 3'd1,
                     S_MEAS_FREQ = 3'd2,
                     S_STABILIZE = 3'd3,
                     S_HISTOGRAM = 3'd4,
                     S_DONE      = 3'd5;

    localparam [1:0] SRC_RO = 2'b01;

    // 히스토그램 BRAM 은 512칸이고 CLEAR 는 한 칸씩 돈다. 넉넉히 잡는다.
    localparam integer CLEAR_CYCLES = 1024;

    reg [2:0]  state;
    reg [31:0] timer;
    reg        strobe_seen;   // S_MEAS_FREQ 에서 첫 게이트 경계를 봤는가

    // ★ 2026-09-05 : 종료 판정을 감소 카운터 + 등록된 플래그로 한다.
    //   [무엇이 문제였나] 처음엔 이렇게 썼다가 타이밍이 깨졌다 :
    //       if (ctrl_stop || ((hit_cnt + (hit_accepted?1:0)) >= target_hits))
    //     32비트 덧셈(CARRY4 8개) -> 32비트 비교 -> 그 결과가 여러 레지스터의 CE 를
    //     구동한다. 실측 : 논리 12단, 데이터 지연 5.900 ns > 예산 5 ns,
    //     slack -1.161 ns, 위반 60곳 (vivado/zed_fsm/timing_summary.rpt).
    //   [어떻게 고쳤나] 남은 수를 세는 감소 카운터를 두고, "이번 히트로 0 이 된다"를
    //     미리 계산해 1비트 레지스터(remain_last)에 담아 둔다. 종료 조건은 그
    //     1비트만 보므로 CE 경로가 짧아진다. 뺄셈은 자기 자신으로만 돌아가는
    //     FF -> 가산기 -> FF 경로라 여유가 있다.
    //   [target_hits = 0 의 의미] 무제한. STOP 으로만 끝난다.
    //     Mode 2 실측처럼 "몇 발 올지 모르는" 경우에 쓴다.
    reg [31:0] remain;
    reg        remain_last;   // remain 이 1 이다 = 다음 히트가 마지막
    reg        unlimited;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state         <= S_IDLE;
            timer         <= 32'd0;
            strobe_seen   <= 1'b0;
            ro_en         <= 1'b0;
            histo_en      <= 1'b0;
            histo_clr     <= 1'b0;
            busy          <= 1'b0;
            done          <= 1'b0;
            hit_cnt       <= 32'd0;
            drop_cnt      <= 32'd0;
            ro_at_start   <= 32'd0;
            ro_at_end     <= 32'd0;
            temp_at_start <= 16'd0;
            temp_at_end   <= 16'd0;
            snap_tgl      <= 1'b0;
            remain        <= 32'd0;
            remain_last   <= 1'b0;
            unlimited     <= 1'b0;
        end else begin
            // 누적 중에는 10 ms 마다 스냅샷 토글을 보내 PS 가 진행 상황을
            // 볼 수 있게 한다. 상태 전이 시점에도 따로 보낸다(아래 참조).
            if (state == S_HISTOGRAM && meas_strobe) snap_tgl <= ~snap_tgl;

            case (state)
            // -----------------------------------------------------------------
            S_IDLE: begin
                ro_en     <= 1'b0;
                histo_en  <= 1'b0;
                histo_clr <= 1'b0;
                busy      <= 1'b0;
                // done 은 여기서 내리지 않는다. S_DONE 에서 내린 뒤 들어온다.
                if (ctrl_start && (ctrl_hit_src == SRC_RO)) begin
                    busy        <= 1'b1;
                    done        <= 1'b0;
                    hit_cnt     <= 32'd0;
                    drop_cnt    <= 32'd0;
                    timer       <= 32'd0;
                    ro_en       <= 1'b1;      // 여기서 바로 켠다
                    // 종료 판정용 감소 카운터를 여기서 장전한다.
                    remain      <= target_hits;
                    remain_last <= (target_hits == 32'd1);
                    unlimited   <= (target_hits == 32'd0);
                    state       <= S_RO_ENABLE;
                end
            end

            // -----------------------------------------------------------------
            // RO 를 켜고 초기 트랜지언트가 가라앉기를 기다린다.
            // ★ SETTLE_N 의 기본 100 us 는 근거 있는 값이 아니다. 지금까지 RO 를
            //   꺼본 적이 없어 켠 직후 거동이 측정된 적이 없다. 레지스터로 빼놨으니
            //   RO_CNT 가 몇 게이트 만에 수렴하는지 재서 실측값으로 바꿀 것.
            S_RO_ENABLE: begin
                if (timer >= settle_n) begin
                    timer       <= 32'd0;
                    strobe_seen <= 1'b0;
                    state       <= S_MEAS_FREQ;
                end else begin
                    timer <= timer + 1'b1;
                end
            end

            // -----------------------------------------------------------------
            // 온전한 게이트 하나를 기다린다 (첫 strobe = 경계, 두 번째 = 완료).
            S_MEAS_FREQ: begin
                if (meas_strobe) begin
                    if (!strobe_seen) begin
                        strobe_seen <= 1'b1;
                    end else begin
                        ro_at_start   <= ro_cnt;
                        temp_at_start <= die_temp;
                        snap_tgl      <= ~snap_tgl;
                        timer         <= 32'd0;
                        histo_clr     <= 1'b1;      // 지우기 시작
                        state         <= S_STABILIZE;
                    end
                end
            end

            // -----------------------------------------------------------------
            // 지우기 + 안정화. 지우기는 1024클럭(5.1 us)이면 512칸을 다 돈다.
            // settle_n(기본 100 us)이 그보다 크므로 둘을 겹쳐 기다린다.
            S_STABILIZE: begin
                if (timer >= CLEAR_CYCLES) histo_clr <= 1'b0;
                if (timer >= settle_n) begin
                    histo_clr <= 1'b0;
                    histo_en  <= 1'b1;
                    timer     <= 32'd0;
                    state     <= S_HISTOGRAM;
                end else begin
                    timer <= timer + 1'b1;
                end
            end

            // -----------------------------------------------------------------
            S_HISTOGRAM: begin
                if (hit_accepted) hit_cnt  <= hit_cnt  + 1'b1;
                if (hit_dropped)  drop_cnt <= drop_cnt + 1'b1;

                // 감소 카운터. remain_last 는 '지금 값이 1' 이라는 뜻이므로,
                // 이번 hit_accepted 가 곧 마지막 히트다.
                if (hit_accepted && !unlimited) begin
                    remain      <= remain - 1'b1;
                    remain_last <= (remain == 32'd2);
                end

                // 종료 조건은 등록된 1비트 둘만 본다 — CE 경로가 짧다.
                if (ctrl_stop || (!unlimited && remain_last && hit_accepted)) begin
                    histo_en    <= 1'b0;
                    ro_at_end   <= ro_cnt;
                    temp_at_end <= die_temp;
                    snap_tgl    <= ~snap_tgl;
                    busy        <= 1'b0;
                    done        <= 1'b1;
                    state       <= S_DONE;
                end
            end

            // -----------------------------------------------------------------
            // START 를 내려야 IDLE 로 돌아간다. 레벨 핸드셰이크라 PS 가 DONE 을
            // 놓칠 수 없다. done 은 IDLE 에서 다음 측정이 시작될 때 내려간다.
            S_DONE: begin
                ro_en    <= 1'b0;
                histo_en <= 1'b0;
                if (!ctrl_start) state <= S_IDLE;
            end

            default: state <= S_IDLE;
            endcase
        end
    end

    always @(*) state_out = state;

endmodule
