// Generated by Claude Code, 2026-08-12
// -----------------------------------------------------------------------------
// ★★★ 임시 측정용 파일 — 측정이 끝나면 이 파일은 쓰지 말 것 ★★★
//
// tdc_fmcw_core_co_thermo — tdc_fmcw_core_co.v 에 thermometer 디버그 출력만 추가한 사본.
// 원본 tdc_fmcw_core_co.v 는 건드리지 않았다. 탭 소스·극성·파이프라인 전부 동일하고
// 추가된 것은 출력 포트 2개와 assign 2줄뿐이다.
//
// =============================================================================
// [왜 만들었나 — 2026-08-12 : 재현성 확인]
//
//   2026-08-09 에 CO 빌드에서 thermometer 를 떠서 다음을 얻었다:
//       가능한 14 패턴 중 3 개만 관측       (고정 순열)
//       도착 순서 CO[1] -> CO[3] -> CO[2] -> CO[0]
//       0100 55.2% / 0101 11.8% / 0111 32.9%
//
//   2026-08-12 에 혼합 빌드(CO,CO,O[2],CO)에서 같은 측정을 했더니 완전히 달랐다:
//       14 패턴 중 8 개 관측                (순열이 흔들림)
//       CO[3] 와 CO[1] 이 준축퇴 (둘 다 단독 패턴으로 나옴)
//       O[2] 는 꼴찌 도착 (부분 패턴의 8.9 % 에서만 켜짐)
//
//   탭 하나를 바꿨을 뿐인데 캐리 도착 순서 자체가 뒤집힌 셈이다. 그런데 그 결론은
//   "8/9 CO 측정이 재현된다"는 전제 위에서만 성립한다. 두 측정은 3일 넘게 떨어져
//   있고 그 사이 합성을 여러 번 했으므로, CO 빌드 자체가 그때와 같은지 먼저 확인해야
//   한다. 이 파일은 그 대조군이다.
//
// [판정]
//   3 패턴 (0100 / 0101 / 0111) 이 8/9 와 비슷한 비율로 재현되면
//       -> 혼합 빌드의 8 패턴은 진짜 변화. 탭 소스가 캐리 타이밍을 바꾼다는 증거.
//   재현되지 않으면
//       -> 8/9 결과 자체가 빌드마다 흔들리는 것. 두 측정 비교가 무의미해진다.
//
// [읽는 법]
//   dbg_thermo[i] = taps_eff[64+i]  (탭 64~111 = CARRY4 스테이지 16~27, 12개)
//   taps_eff 는 극성 보정 후 값이라 1 = "파면이 이 탭을 지나갔다" 로 통일돼 있다.
//   CARRY4 4비트 묶음 안의 비트 j 가 받는 신호 (CO 빌드이므로 전부 CO):
//       비트 0 = CO[0] ,  비트 1 = CO[1] ,  비트 2 = CO[2] ,  비트 3 = CO[3]
//
// [측정 방법 — 8/9, 8/12 와 동일하게]
//   Mode 1 (링 오실레이터). ILA : Capture Mode BASIC, storage qual = dbg_valid == 1,
//   depth 1024, dbg_thermo 라딕스는 반드시 BINARY.
//   probe0(1비트) / probe3(48비트) 재활용이라 ILA IP 재생성 불필요.
//
// [원복]
//   top 의 모듈명을 tdc_fmcw_core_co (또는 tdc_fmcw_core) 로 되돌리고
//   top 의 ★임시★ 블록 2곳을 되살리면 끝. 이 파일은 삭제해도 된다.
// =============================================================================
`timescale 1ns / 1ps

module tdc_fmcw_core_co_thermo #(
    parameter CARRY4_STAGES = 80 // 80 * 4 = 320 Taps (5ns 커버)
)(
    input wire clk,
    input wire rst_n,
    input wire hit,

    output reg [31:0]  ts_coarse,
    output reg [8:0]   ts_fine_idx,
    output reg         ts_valid,

    // ★임시★ thermometer 디버그 (측정 후 이 파일째로 폐기)
    output wire [47:0] dbg_thermo,   // taps_eff[64+:48] = 탭 64~111 (CARRY4 12개)
    output wire        dbg_valid     // 파면이 이 창 안에 있음 (ILA storage qualification)
);

localparam NUM_TAPS = CARRY4_STAGES * 4; // 320

(* keep = "true" *) wire [NUM_TAPS-1:0] carry_co;
(* keep = "true", dont_touch = "true" *) wire [NUM_TAPS-1:0] carry_o;
(* ASYNC_REG = "TRUE", DONT_TOUCH = "TRUE" *) wire [NUM_TAPS-1:0] taps_sampled;

// -------------------------------------------------------------------------
// 1. Dual Phase Coarse Counters
// -------------------------------------------------------------------------
reg [31:0] coarse_0;
reg [31:0] coarse_180;
reg [31:0] coarse_180_sync;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_0 <= 0;
    else coarse_0 <= coarse_0 + 1'b1;
end

always @(negedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180 <= 0;
    else coarse_180 <= coarse_0;
end

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180_sync <= 0;
    else coarse_180_sync <= coarse_180;
end

// -------------------------------------------------------------------------
// 2. 파이프라인 레지스터 (★ Hold 에러 방지 속성 추가 ★)
// -------------------------------------------------------------------------
(* DONT_TOUCH = "TRUE" *) reg [NUM_TAPS-1:0] taps_sampled_d1;
reg taps_sampled_0_history;

reg snapshot_valid_stg2, snapshot_valid_stg3, snapshot_valid_stg4;

// Vivado가 Shift Register로 압축하는 것을 막아 라우터가 배선 지연을 추가할 수 있게 돕습니다.
(* srl_style = "register" *) reg [31:0] captured_c0_stg2, captured_c180_stg2;
(* srl_style = "register" *) reg [31:0] captured_c0_stg3, captured_c180_stg3_plus1;
(* srl_style = "register" *) reg [31:0] captured_c0_stg4, captured_c180_stg4_plus1;

reg [8:0]  fine_idx_stg4;
reg        danger_zone_stg4;

reg [3:0] stg1_halfA [0:19];
reg [3:0] stg1_halfB [0:19];
reg [7:0] stg3_group0, stg3_group1, stg3_group2, stg3_group3;

integer i;

function [3:0] popcount8;
    input [7:0] din;
    begin
        popcount8 = din[0] + din[1] + din[2] + din[3] +
                    din[4] + din[5] + din[6] + din[7];
    end
endfunction

// -------------------------------------------------------------------------
// ★ 변경 2/3 (2026-08-04) — 탭 극성 반전을 조합으로 흡수
// -------------------------------------------------------------------------
//   S=4'b1111 이므로  O[j] = 1 XOR carry = ~carry ,  CO[j] = carry  로 서로 반대다.
//   원본(O 탭): hit 하강 -> 탭이 0->1 로 전파 -> popcount = "지나간 탭 수"
//   CO 탭     : 탭이 1->0 으로 전파       -> popcount = "아직 안 지나간 탭 수"
//
//   그래서 taps_eff = ~taps_sampled_d1 을 만들어 이후 로직이 원본과 완전히 같은
//   의미("지나간 탭 수")를 보게 한다.
//
//   ※ .D(~carry_co[...]) 로 탭 경로에 인버터를 넣으면 LUT1 이 끼어들어 CO 로 바꾼
//     이유(XOR 경로 제거)가 사라진다. 반드시 샘플링 FF 뒤에서 반전해야 하며,
//     여기서의 반전은 뒤따르는 popcount LUT 에 흡수되어 추가 지연이 없다.
//     taps_sampled_d1 자체는 반전하지 않는다 — tdc.xdc 가 taps_sampled_d1_reg 를
//     SLICE_X43Y* 에 고정해 두었고 그 사이에 LUT 를 넣으면 배치가 깨진다.
wire [NUM_TAPS-1:0] taps_eff = ~taps_sampled_d1;

// ★임시★ thermometer 출력 — taps_eff 는 극성 보정 후라 1 = "파면이 지나감".
//   taps_sampled_d1 이 레지스터라 한 클록 동안 안정하다. ILA 가 그대로 받으면 된다.
assign dbg_thermo = taps_eff[64 +: 48];
assign dbg_valid  = (|dbg_thermo) & ~(&dbg_thermo);

// -------------------------------------------------------------------------
// 3. CARRY4 CHAIN
// -------------------------------------------------------------------------
(* keep = "true" *) wire rst_high = ~rst_n;
genvar k;
generate
    for (k = 0; k < CARRY4_STAGES; k = k + 1) begin : CARRY_CHAIN
        if (k == 0) begin : STAGE_0
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(1'b0), .CYINIT(hit), .DI(4'b0000), .S(4'b1111));
        end else begin : STAGE_N
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(carry_co[(k*4)-1]), .CYINIT(1'b0), .DI(4'b0000), .S(4'b1111));
        end
        // ★ 변경 1/3 (2026-08-04) — 탭 소스를 carry_o(XOR) 에서 carry_co(캐리) 로 교체.
        //    이유는 파일 상단 주석 참조. FF 이름/BEL 은 원본과 동일하게 유지해야
        //    tdc.xdc 의 LOC/BEL 제약이 그대로 걸린다.
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_0 ( .Q(taps_sampled[(k*4)+0]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+0]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_1 ( .Q(taps_sampled[(k*4)+1]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+1]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_2 ( .Q(taps_sampled[(k*4)+2]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+2]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_3 ( .Q(taps_sampled[(k*4)+3]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+3]) );
    end
endgenerate

// -------------------------------------------------------------------------
// 4. MAIN LOGIC 파이프라인
// -------------------------------------------------------------------------
localparam DEAD_TIME_CYCLES = 2;
reg [3:0] dead_time_cnt;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        taps_sampled_d1 <= 0; taps_sampled_0_history <= 0; dead_time_cnt <= 0;
        snapshot_valid_stg2 <= 0; snapshot_valid_stg3 <= 0; snapshot_valid_stg4 <= 0;
        captured_c0_stg2 <= 0; captured_c180_stg2 <= 0;
        captured_c0_stg3 <= 0; captured_c180_stg3_plus1 <= 0;
        captured_c0_stg4 <= 0; captured_c180_stg4_plus1 <= 0;
        fine_idx_stg4 <= 0; danger_zone_stg4 <= 0;
        ts_coarse <= 0; ts_valid <= 0; ts_fine_idx <= 0;
        stg3_group0 <= 0; stg3_group1 <= 0; stg3_group2 <= 0; stg3_group3 <= 0;
        for (i = 0; i < 20; i = i + 1) begin
            stg1_halfA[i] <= 0; stg1_halfB[i] <= 0;
        end
    end
    else begin
        // [Stage 1]
        taps_sampled_d1 <= taps_sampled;
        // ★ 변경 3/3 (2026-08-04) — 아래 taps_sampled_d1[...] 참조를 전부 taps_eff[...] 로 교체.
        //    hit 하강 시 CO 탭은 1->0 이므로 taps_eff[0] 의 상승이 원본 taps_sampled_d1[0]
        //    상승과 같은 사건(= 캐리 프론트가 탭 0 을 통과)을 가리킨다.
        //    stage 0 은 CYINIT=hit, S=1 이므로 CO[0]=hit, 즉 taps_eff[0]=~hit 로
        //    원본(O[0]=~hit)과 동일 — 하강 에지 검출 의미가 그대로 보존된다.
        taps_sampled_0_history <= taps_eff[0];

        // [Stage 2]
        if (dead_time_cnt > 0) begin
            dead_time_cnt <= dead_time_cnt - 1'b1;
            snapshot_valid_stg2 <= 1'b0;
        end
        else if (taps_eff[0] && !taps_sampled_0_history) begin
            dead_time_cnt <= DEAD_TIME_CYCLES;

            captured_c0_stg2   <= coarse_0;
            captured_c180_stg2 <= coarse_180_sync;

            for (i = 0; i < 20; i = i + 1) begin
                stg1_halfA[i] <= popcount8(taps_eff[i*16 +: 8]);
                stg1_halfB[i] <= popcount8(taps_eff[i*16+8 +: 8]);
            end
            snapshot_valid_stg2 <= 1'b1;
        end else begin
            snapshot_valid_stg2 <= 1'b0;
        end

        // [Stage 3]
        if (snapshot_valid_stg2) begin
            stg3_group0 <= stg1_halfA[0]+stg1_halfB[0] + stg1_halfA[1]+stg1_halfB[1] + stg1_halfA[2]+stg1_halfB[2] + stg1_halfA[3]+stg1_halfB[3] + stg1_halfA[4]+stg1_halfB[4];
            stg3_group1 <= stg1_halfA[5]+stg1_halfB[5] + stg1_halfA[6]+stg1_halfB[6] + stg1_halfA[7]+stg1_halfB[7] + stg1_halfA[8]+stg1_halfB[8] + stg1_halfA[9]+stg1_halfB[9];
            stg3_group2 <= stg1_halfA[10]+stg1_halfB[10] + stg1_halfA[11]+stg1_halfB[11] + stg1_halfA[12]+stg1_halfB[12] + stg1_halfA[13]+stg1_halfB[13] + stg1_halfA[14]+stg1_halfB[14];
            stg3_group3 <= stg1_halfA[15]+stg1_halfB[15] + stg1_halfA[16]+stg1_halfB[16] + stg1_halfA[17]+stg1_halfB[17] + stg1_halfA[18]+stg1_halfB[18] + stg1_halfA[19]+stg1_halfB[19];

            captured_c0_stg3 <= captured_c0_stg2;
            captured_c180_stg3_plus1 <= captured_c180_stg2 + 1'b1;

            snapshot_valid_stg3 <= 1'b1;
        end else begin
            snapshot_valid_stg3 <= 1'b0;
        end

        // [Stage 4]
        if (snapshot_valid_stg3) begin
            begin : CALC_FINE
                reg [8:0] sum_fine;
                sum_fine = stg3_group0 + stg3_group1 + stg3_group2 + stg3_group3;
                fine_idx_stg4 <= sum_fine;

                // ★ 데이터 기반 Threshold 적용 구역 (40, 220)
                //   [2026-08-04 주의] 이 값은 O 탭 분포로 튜닝된 것이다. CO 탭은
                //   탭당 폭 분포가 달라지므로 첫 측정 후 재튜닝이 필요할 수 있다.
                //   지금은 원본과 동일 조건으로 비교하기 위해 그대로 둔다.
                danger_zone_stg4 <= (sum_fine < 9'd40 || sum_fine > 9'd220);
            end

            captured_c0_stg4 <= captured_c0_stg3;
            captured_c180_stg4_plus1 <= captured_c180_stg3_plus1;
            snapshot_valid_stg4 <= 1'b1;
        end else begin
            snapshot_valid_stg4 <= 1'b0;
        end

        // [Stage 5]
        if (snapshot_valid_stg4) begin
            ts_fine_idx <= fine_idx_stg4;

            if (danger_zone_stg4) begin
                ts_coarse <= captured_c180_stg4_plus1;
            end else begin
                ts_coarse <= captured_c0_stg4;
            end

            ts_valid <= 1'b1;
        end else begin
            ts_valid <= 1'b0;
        end
    end
end
endmodule
