`timescale 1ns / 1ps
// =============================================================================
// tdc_zedboard_top.v  —  ZedBoard (XC7Z020-CLG484) 용 최상위
// Generated by Claude Code, 2026-09-02
//
//  [★ 2026-09-04 전면 개편 — PS + AXI 구조로]
//
//  무엇이 바뀌었나
//    (1) 클럭 소스가 하나가 됐다.
//        기존 : Y9 온보드 발진기(100 MHz) -> clk_wiz_0 -> 200 MHz
//        변경 : PS7 의 FCLK_CLK0(100 MHz) -> clk_wiz_0 -> 200 MHz
//               같은 FCLK 가 AXI 도메인도 돌린다.
//        Y9 핀은 더 이상 쓰지 않는다 (포트에서 제거).
//    (2) PS7 블록 디자인(ps_sys)과 AXI 레지스터 블록(tdc_axi_regs)이 들어왔다.
//
//  왜 클럭을 FCLK 로 통일했나
//    클럭 소스가 둘이면 AXI 도메인과 TDC 도메인이 완전한 비동기가 되어 건너가는
//    신호마다 동기화가 필요하다. FCLK 하나로 통일하면 200 MHz 가 그 FCLK 에
//    위상 고정되므로 두 도메인이 2:1 로 동기 관계가 된다.
//    ※ 다만 FCLK 는 PS 의 PLL 에서 나오므로 전용 크리스털(Y9)보다 지터가 크다.
//      TDC 분해능을 직접 제한하는 것이 샘플링 클럭 지터라, 이 변경이 탭 폭 분포에
//      영향을 주는지는 **아직 측정된 바 없다.** 2026-09-04 에 잰 값
//      (유효탭 320, LSB 15.625 ps, 양자화 한계 7.35 ps)은 전부 Y9 기준이므로,
//      FCLK 로 바꾼 뒤 Mode 1 히스토그램을 다시 떠서 비교해야 한다.
//
//  [Zybo 와 다른 점]
//    1) 히트 입력 : PMOD 단일선(V8) -> FMC LA27_P/N 차동쌍(E21/D21)
//                   TLV3605 비교기의 LVDS 출력을 IBUFDS 로 받는다.
//    2) 클럭      : 온보드 발진기 -> PS7 FCLK_CLK0
//    3) 디바이스  : XC7Z010-CLG400 -> XC7Z020-CLG484
//    4) 캐리체인  : 80단(320탭) -> 96단(384탭)
//
//  [RTL 밖에서 반드시 해야 할 것]
//    (a) clk_wiz_0 IP 를 재생성할 것.
//        입력 100 MHz, VCO 1000 MHz(M=10, D=1), CLKOUT0/1 = 200 MHz(/5).
//        ★ 입력이 이제 외부 핀이 아니라 내부 클럭이므로
//          PRIM_SOURCE 를 Global_buffer 로 둘 것. 핀용 설정을 그대로 두면
//          쓸데없는 IBUF 가 끼어든다.
//        VCO 를 1000 MHz 로 유지해야 phase_shifter.v 의 스텝 17.857 ps 가 성립한다.
//    (b) ZedBoard 점퍼 J18 을 2.5V 로 옮길 것 (기본값 1.8V).
//        FMC 뱅크의 VCCO 가 2.5V 여야 LVDS_25 수신과 내부 100옴 종단이 동작한다.
//    (c) 블록 디자인 ps_sys 를 만들 것 : tcl/bd_ps_sys.tcl
//    (d) RTL/tdc_zedboard.xdc 를 쓸 것. Zybo 용 tdc.xdc 는 넣지 말 것.
//        캐리체인 LOC 2400줄은 python/gen_chain_xdc.py --stages 96 으로 생성한다.
//        DDR / FIXED_IO 는 Zynq 전용 핀이라 XDC 에 위치 제약을 쓰지 않는다.
//    (e) tdc_calib_rom 을 384칸으로 재생성할 것.
// =============================================================================

module tdc_zedboard_top #(
    // tdc_test_top 과 동일한 의미.
    //   0 : Hit = 내부 Test Sync | 1 : Hit = Ring Osc | 2 : Hit = FMC LVDS
    //   ※ 새 모드 정의(0=RO 코드밀도 / 1=DPS 지터 / 2=실측)는 AXI 시퀀서가
    //     들어오는 2단계에서 CTRL.HIT_SRC 로 옮겨간다.
    parameter integer OPERATION_MODE = 1
)(
    // ---------------- Zynq PS 전용 핀 (Vivado 가 자동 매핑, XDC 불필요) ----------
    inout  wire [14:0] DDR_addr,
    inout  wire [ 2:0] DDR_ba,
    inout  wire        DDR_cas_n,
    inout  wire        DDR_ck_n,
    inout  wire        DDR_ck_p,
    inout  wire        DDR_cke,
    inout  wire        DDR_cs_n,
    inout  wire [ 3:0] DDR_dm,
    inout  wire [31:0] DDR_dq,
    inout  wire [ 3:0] DDR_dqs_n,
    inout  wire [ 3:0] DDR_dqs_p,
    inout  wire        DDR_odt,
    inout  wire        DDR_ras_n,
    inout  wire        DDR_reset_n,
    inout  wire        DDR_we_n,
    inout  wire        FIXED_IO_ddr_vrn,
    inout  wire        FIXED_IO_ddr_vrp,
    inout  wire [53:0] FIXED_IO_mio,
    inout  wire        FIXED_IO_ps_clk,
    inout  wire        FIXED_IO_ps_porb,
    inout  wire        FIXED_IO_ps_srstb,

    // ---------------- PL 핀 ----------------
    //  ※ clk_100(Y9) 은 2026-09-04 부로 제거. 클럭은 PS 의 FCLK_CLK0 를 쓴다.
    input  wire        rst_n,        // BTNC(P16). 이름과 달리 active-HIGH 로 쓰인다
    input  wire        btn_shift,    // BTNU(T18). 위상 목표를 한 칸씩 올리는 임시 버튼
    input  wire        hit_lvds_p,   // E21, FMC LA27_P  <- TLV3605 LVDS+
    input  wire        hit_lvds_n,   // D21, FMC LA27_N  <- TLV3605 LVDS-
    output wire [3:0]  led
);

    // -------------------------------------------------------------------------
    // LVDS 히트 수신
    //
    //  DIFF_TERM = "TRUE" 로 FPGA 내부 100옴 차동 종단을 켠다. 종단하지 않으면
    //  반사로 에지가 무너지고, 그건 곧 캐리체인 진입 slew 저하 -> 진입 트랜지언트
    //  악화로 이어진다. (tdc_test_top.v 의 led[2] 사례 : hit 네트에 부하가 붙자
    //  CARRY4 초입 3단이 정상값의 1.16~1.89배로 늘어났다.)
    //
    //  ★ IBUFDS 출력은 어떤 로직도 거치지 않고 곧장 코어의 hit 입력으로 간다.
    //    레지스터를 끼우거나 다른 곳에 분기하면 안 된다.
    // -------------------------------------------------------------------------
    wire hit_from_fmc;

    IBUFDS #(
        .DIFF_TERM    ("TRUE"),      // 내부 100옴 차동 종단 (VCCO 2.5V 필요)
        .IBUF_LOW_PWR ("FALSE")      // 성능 우선
    ) u_hit_ibufds (
        .I  (hit_lvds_p),
        .IB (hit_lvds_n),
        .O  (hit_from_fmc)
    );

    // =========================================================================
    // PS7 블록 디자인 (tcl/bd_ps_sys.tcl 로 생성)
    //   PS7 + proc_sys_reset + AXI 인터커넥트. AXI4-Lite 마스터 하나를 내보낸다.
    //   슬레이브 주소는 0x43C0_0000 (64K) 로 배정돼 있다.
    // =========================================================================
    wire        fclk;            // FCLK_CLK0 100 MHz — AXI 도메인 겸 MMCM 입력
    wire [0:0]  arstn;           // AXI 도메인 리셋 (active low)

    wire [31:0] axi_awaddr, axi_araddr, axi_wdata, axi_rdata;
    wire [ 2:0] axi_awprot, axi_arprot;
    wire [ 3:0] axi_wstrb;
    wire [ 1:0] axi_bresp,  axi_rresp;
    wire        axi_awvalid, axi_awready, axi_wvalid, axi_wready;
    wire        axi_bvalid,  axi_bready;
    wire        axi_arvalid, axi_arready, axi_rvalid, axi_rready;

    ps_sys_wrapper u_ps (
        .DDR_addr          (DDR_addr),
        .DDR_ba            (DDR_ba),
        .DDR_cas_n         (DDR_cas_n),
        .DDR_ck_n          (DDR_ck_n),
        .DDR_ck_p          (DDR_ck_p),
        .DDR_cke           (DDR_cke),
        .DDR_cs_n          (DDR_cs_n),
        .DDR_dm            (DDR_dm),
        .DDR_dq            (DDR_dq),
        .DDR_dqs_n         (DDR_dqs_n),
        .DDR_dqs_p         (DDR_dqs_p),
        .DDR_odt           (DDR_odt),
        .DDR_ras_n         (DDR_ras_n),
        .DDR_reset_n       (DDR_reset_n),
        .DDR_we_n          (DDR_we_n),
        .FIXED_IO_ddr_vrn  (FIXED_IO_ddr_vrn),
        .FIXED_IO_ddr_vrp  (FIXED_IO_ddr_vrp),
        .FIXED_IO_mio      (FIXED_IO_mio),
        .FIXED_IO_ps_clk   (FIXED_IO_ps_clk),
        .FIXED_IO_ps_porb  (FIXED_IO_ps_porb),
        .FIXED_IO_ps_srstb (FIXED_IO_ps_srstb),

        .M_AXI_awaddr      (axi_awaddr),
        .M_AXI_awprot      (axi_awprot),
        .M_AXI_awvalid     (axi_awvalid),
        .M_AXI_awready     (axi_awready),
        .M_AXI_wdata       (axi_wdata),
        .M_AXI_wstrb       (axi_wstrb),
        .M_AXI_wvalid      (axi_wvalid),
        .M_AXI_wready      (axi_wready),
        .M_AXI_bresp       (axi_bresp),
        .M_AXI_bvalid      (axi_bvalid),
        .M_AXI_bready      (axi_bready),
        .M_AXI_araddr      (axi_araddr),
        .M_AXI_arprot      (axi_arprot),
        .M_AXI_arvalid     (axi_arvalid),
        .M_AXI_arready     (axi_arready),
        .M_AXI_rdata       (axi_rdata),
        .M_AXI_rresp       (axi_rresp),
        .M_AXI_rvalid      (axi_rvalid),
        .M_AXI_rready      (axi_rready),

        .fclk_clk0         (fclk),
        .peripheral_arstn  (arstn)
    );

    // =========================================================================
    // TDC 코어
    //
    //  clk_125 포트에 FCLK_CLK0(100 MHz)를 넣는다. 포트 이름이 실제 주파수와
    //  다르지만 "PL 클럭 입력" 이라는 의미이고, 실제 주파수는 clk_wiz_0 설정이 정한다.
    //
    //  MMCM 리셋 : PS 가 뜨기 전에는 FCLK 가 돌지 않으므로, PS 리셋이 풀린 뒤에
    //  MMCM 을 놓아줘야 한다. arstn 이 그 시점을 알려준다. 버튼도 OR 로 물린다.
    //  (rst_n 포트는 이름과 달리 active-HIGH 로 쓰인다 — clk_wiz 의 reset 이
    //   ACTIVE_HIGH 로 설정돼 있기 때문이다.)
    // =========================================================================
    wire mmcm_rst = (~arstn[0]) | rst_n;

    wire        tdc_clk;
    wire        tdc_locked;
    wire [30:0] tdc_dna;
    wire        tdc_dna_valid;
    wire        tdc_phase_busy;

    // ★ 2026-09-05 : AXI 2단계 — 히스토그램 읽기 창과 측정 조건 신호
    wire        tdc_meas_strobe;
    wire [31:0] tdc_ro_cnt;
    wire [15:0] tdc_die_temp;
    wire [8:0]  tdc_phase_cur;
    wire [8:0]  ctrl_phase_tgt;
    wire [8:0]  histo_addr;
    wire [31:0] histo_data;

    // ★ 2026-09-05 : 시퀀서 FSM 신호
    wire        seq_busy, seq_done, seq_snap_tgl;
    wire [2:0]  seq_state;
    wire [31:0] seq_hit_cnt, seq_drop_cnt, seq_ro_start, seq_ro_end;
    wire [15:0] seq_temp_start, seq_temp_end;
    wire [31:0] ctrl_target_hits, ctrl_settle_n;
    // ★ 2026-09-05 : 캡처 버퍼 (Mode 2)
    wire [12:0] ctrl_cap_n, cap_cnt;
    wire [8:0]  ctrl_danger_lo, ctrl_danger_hi;
    wire [11:0] cap_addr;
    wire        cap_hi;
    wire [31:0] cap_data;

    // ★ 2026-09-05 : ctrl_histo_clr 를 아래 u_core 인스턴스가 먼저 쓰므로
    //   선언이 여기 있어야 한다 (Verilog 는 암시적 선언을 1비트로 만들어 버린다).
    wire [1:0] ctrl_hit_src;
    wire       ctrl_start, ctrl_stop, ctrl_histo_clr, ctrl_tdc_rst, ctrl_cap_fmt;

    tdc_test_top #(
        .OPERATION_MODE (OPERATION_MODE),
        .CARRY4_STAGES  (96)              // 384탭. 근거는 tdc_fmcw_core_co.v 상단 주석
    ) u_core (
        .clk_125      (fclk),             // ★ 2026-09-04 : Y9 발진기 -> PS FCLK_CLK0
        .rst_n        (mmcm_rst),
        .btn_shift    (btn_shift),        // ★ 2026-09-05 : 코어 내부에서 미사용 (주석 참조)
        .ext_hit_in   (hit_from_fmc),
        .led          (led),
        .o_tdc_clk    (tdc_clk),
        .o_locked     (tdc_locked),
        .o_dna        (tdc_dna),
        .o_dna_valid  (tdc_dna_valid),
        .o_phase_busy (tdc_phase_busy),

        // ★ 2026-09-05 추가
        .o_meas_strobe (tdc_meas_strobe),
        .o_ro_cnt      (tdc_ro_cnt),
        .o_die_temp    (tdc_die_temp),
        .o_phase_cur   (tdc_phase_cur),
        .i_phase_tgt   (ctrl_phase_tgt),
        .i_histo_clr   (ctrl_histo_clr),
        // 히스토그램 BRAM Port B 는 AXI 클럭(fclk)으로 돈다
        .i_axi_clk     (fclk),
        .i_histo_addr  (histo_addr),
        .o_histo_data  (histo_data),

        // ★ 2026-09-05 : 시퀀서
        .i_ctrl_start   (ctrl_start),
        .i_ctrl_stop    (ctrl_stop),
        .i_ctrl_hit_src (ctrl_hit_src),
        .i_ctrl_cap_fmt (ctrl_cap_fmt),
        .i_target_hits  (ctrl_target_hits),
        .i_settle_n     (ctrl_settle_n),
        .i_danger_lo    (ctrl_danger_lo),
        .i_danger_hi    (ctrl_danger_hi),
        .o_busy         (seq_busy),
        .o_done         (seq_done),
        .o_state        (seq_state),
        .o_hit_cnt      (seq_hit_cnt),
        .o_drop_cnt     (seq_drop_cnt),
        .o_ro_start     (seq_ro_start),
        .o_ro_end       (seq_ro_end),
        .o_temp_start   (seq_temp_start),
        .o_temp_end     (seq_temp_end),
        .o_snap_tgl     (seq_snap_tgl),

        // ★ 2026-09-05 : 캡처 버퍼
        .i_cap_n        (ctrl_cap_n),
        .o_cap_cnt      (cap_cnt),
        .i_cap_addr     (cap_addr),
        .i_cap_hi       (cap_hi),
        .o_cap_data     (cap_data)
    );

    // =========================================================================
    // AXI 제어/상태 레지스터
    //   ★ 2026-09-05 (2단계) : 히스토그램 리드백 + RO_CNT/DIE_TEMP/PHASE 추가.
    //     주소 폭이 8 -> 16 으로 늘었다. 히스토그램 창이 0x1000 부터라
    //     주소 비트 12 가 필요하고, 8비트로는 0x1000 이 0x00 으로 접혀
    //     ID 레지스터와 충돌한다.
    //     ctrl_start/stop/tdc_rst/cap_fmt 는 아직 안 쓴다 — 3단계 시퀀서가 받는다.
    //   PS 에서 0x43C0_0000 을 읽어 0x54444302 가 나오면 성공.
    // =========================================================================
    tdc_axi_regs #(
        .C_S_AXI_ADDR_WIDTH (16),            // ★ 2026-09-05 : 8 -> 16
        .CHAIN_STAGES       (96)
    ) u_regs (
        .s_axi_aclk      (fclk),
        .s_axi_aresetn   (arstn[0]),
        .s_axi_awaddr    (axi_awaddr[15:0]),  // ★ 2026-09-05 : 64K 어퍼처 전체
        .s_axi_awvalid   (axi_awvalid),
        .s_axi_awready   (axi_awready),
        .s_axi_wdata     (axi_wdata),
        .s_axi_wstrb     (axi_wstrb),
        .s_axi_wvalid    (axi_wvalid),
        .s_axi_wready    (axi_wready),
        .s_axi_bresp     (axi_bresp),
        .s_axi_bvalid    (axi_bvalid),
        .s_axi_bready    (axi_bready),
        .s_axi_araddr    (axi_araddr[15:0]),  // ★ 2026-09-05 : 8 -> 16비트
        .s_axi_arvalid   (axi_arvalid),
        .s_axi_arready   (axi_arready),
        .s_axi_rdata     (axi_rdata),
        .s_axi_rresp     (axi_rresp),
        .s_axi_rvalid    (axi_rvalid),
        .s_axi_rready    (axi_rready),

        .tdc_clk         (tdc_clk),
        .tdc_rst_n       (tdc_locked),

        .stat_mmcm_locked(tdc_locked),
        .stat_dna        (tdc_dna),
        .stat_dna_valid  (tdc_dna_valid),
        .stat_busy       (seq_busy),          // ★ 2026-09-05 : 시퀀서 연결
        .stat_done       (seq_done),
        .stat_phase_busy (tdc_phase_busy),

        // ★ 2026-09-05 추가
        .stat_meas_strobe(tdc_meas_strobe),
        .stat_ro_cnt     (tdc_ro_cnt),
        .stat_die_temp   (tdc_die_temp),
        .stat_phase_cur  (tdc_phase_cur),
        .histo_addr      (histo_addr),
        .histo_data      (histo_data),

        // ★ 2026-09-05 : 캡처 버퍼
        .cap_addr        (cap_addr),
        .cap_hi          (cap_hi),
        .cap_data        (cap_data),
        .stat_cap_cnt    (cap_cnt),

        // ★ 2026-09-05 : 시퀀서 스냅샷
        .stat_snap_tgl   (seq_snap_tgl),
        .stat_hit_cnt    (seq_hit_cnt),
        .stat_drop_cnt   (seq_drop_cnt),
        .stat_ro_start   (seq_ro_start),
        .stat_ro_end     (seq_ro_end),
        .stat_temp_start (seq_temp_start),
        .stat_temp_end   (seq_temp_end),
        .stat_state      (seq_state),

        .ctrl_hit_src    (ctrl_hit_src),
        .ctrl_start      (ctrl_start),
        .ctrl_stop       (ctrl_stop),
        .ctrl_histo_clr  (ctrl_histo_clr),
        .ctrl_tdc_rst    (ctrl_tdc_rst),
        .ctrl_cap_fmt    (ctrl_cap_fmt),
        .ctrl_phase_tgt  (ctrl_phase_tgt),    // ★ 2026-09-05 : BTNU 대체
        .ctrl_target_hits(ctrl_target_hits),
        .ctrl_settle_n   (ctrl_settle_n),
        .ctrl_cap_n      (ctrl_cap_n),
        .ctrl_danger_lo  (ctrl_danger_lo),
        .ctrl_danger_hi  (ctrl_danger_hi)
    );

endmodule
