`timescale 1ns / 1ps
// =============================================================================
// tdc_capture.v  —  히트별 타임스탬프 캡처 버퍼
// Generated by Claude Code, 2026-09-05
//
//  [무엇인가]
//  히스토그램이 "탭마다 몇 발" 을 세는 것과 달리, 이쪽은 히트 하나하나의
//  타임스탬프를 도착 순서대로 쌓는다. Mode 2(외부 LVDS 실측)와 Mode 0(DPS)이 쓴다.
//  두 모드는 CTRL.HIT_SRC 가 단일 선택 필드라 동시에 켜질 수 없으므로 버퍼를
//  공유해도 안전하다.
//
//  [왜 64비트인가]
//  하드웨어가 계산한 timestamp_ps 는 48비트이고, raw {coarse[31:0], fine[8:0]} 은
//  41비트다. 32비트 한 워드에 안 들어간다. 그래서 히트 하나가 2워드를 차지한다.
//    CAP_FMT=0 : 워드0 = timestamp_ps[31:0]      워드1 = {16'd0, timestamp_ps[47:32]}
//    CAP_FMT=1 : 워드0 = coarse[31:0]            워드1 = {23'd0, fine_idx[8:0]}
//  raw 를 남기는 이유는, 교정표를 바꿔가며 같은 원본을 다시 계산해 보기 위해서다.
//
//  [★ 메모리를 32비트 둘로 쪼갠 이유]
//  AXI4-Lite 는 한 번에 32비트만 읽는다. 64비트 메모리를 하나 두고 상위/하위를
//  고르게 하면 읽을 때마다 64비트를 다 꺼내 절반을 버리게 된다. 그래서 처음부터
//  lo/hi 두 개로 나눠 두고, 주소 비트 하나로 어느 쪽을 읽을지 고른다.
//
//  [클럭이 둘인 이유 — tdc_histogram 과 같은 방식]
//  쓰기는 tdc_clk(200 MHz), 읽기는 s_axi_aclk(100 MHz). 7-series BRAM 은 포트마다
//  클럭이 따로 있는 진짜 듀얼포트라 이렇게 쓰면 AXI 쪽은 전부 동기 논리가 되어
//  클럭 도메인 교차 처리가 아예 필요 없다. 읽는 중에 반대편이 써도 32비트 워드가
//  찢어지지 않는다(BRAM 포트 읽기는 워드 단위로 원자적이다).
//
//  ※ 다만 '같은 히트의 lo 와 hi' 는 서로 다른 두 메모리에서 두 번에 걸쳐 읽는다.
//    그 사이에 그 자리를 새 히트가 덮어쓰면 두 반쪽이 다른 히트의 것이 된다.
//    지금 FSM 은 CAP_N 발을 채우면 멈추고(S_DONE), PS 가 다 읽은 뒤에야 다시
//    시작하므로 그럴 일이 없다. 나중에 핑퐁/연속 모드를 넣을 때 이 점을 반드시
//    다시 볼 것.
// =============================================================================

module tdc_capture #(
    parameter integer ADDR_WIDTH = 12          // 4096 발
)(
    // ---------------- 쓰기 (tdc_clk 도메인) ----------------
    input  wire                   clk,
    input  wire                   rst_n,

    input  wire                   en,          // FSM 의 S_ACQ 구간에서만 1
    input  wire                   clr,         // 포인터 0 으로 (레벨)
    input  wire                   cap_fmt,     // 0=timestamp_ps  1=raw
    input  wire                   ts_valid,
    input  wire [47:0]            timestamp_ps,
    input  wire [31:0]            ts_coarse,
    input  wire [8:0]             ts_fine_idx,
    input  wire [ADDR_WIDTH:0]    cap_n,       // 이만큼 모으면 full (1 비트 여유)

    output reg  [ADDR_WIDTH:0]    cap_cnt,     // 지금까지 모인 수
    output wire                   full,
    output wire                   hit_written, // 실제로 쓴 히트 (1클럭)
    output wire                   hit_lost,    // full 이라 버린 히트 (1클럭)

    // ---------------- 읽기 (s_axi_aclk 도메인) ----------------
    input  wire                   clk_b,
    input  wire [ADDR_WIDTH-1:0]  read_addr,
    input  wire                   read_hi,     // 0=하위 워드, 1=상위 워드
    output wire [31:0]            read_data
);

    localparam integer DEPTH = (1 << ADDR_WIDTH);

    assign full        = (cap_cnt >= cap_n);
    assign hit_written = en && ts_valid && !full;
    assign hit_lost    = en && ts_valid &&  full;

    wire [31:0] w_lo = cap_fmt ? ts_coarse            : timestamp_ps[31:0];
    wire [31:0] w_hi = cap_fmt ? {23'd0, ts_fine_idx} : {16'd0, timestamp_ps[47:32]};

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)      cap_cnt <= 0;
        else if (clr)    cap_cnt <= 0;
        else if (hit_written) cap_cnt <= cap_cnt + 1'b1;
    end

    wire [ADDR_WIDTH-1:0] wr_addr = cap_cnt[ADDR_WIDTH-1:0];

    (* ram_style = "block" *) reg [31:0] mem_lo [0:DEPTH-1];
    (* ram_style = "block" *) reg [31:0] mem_hi [0:DEPTH-1];
    reg [31:0] dout_lo, dout_hi;

    always @(posedge clk) begin
        if (hit_written) begin
            mem_lo[wr_addr] <= w_lo;
            mem_hi[wr_addr] <= w_hi;
        end
    end

    always @(posedge clk_b) begin
        dout_lo <= mem_lo[read_addr];
        dout_hi <= mem_hi[read_addr];
    end

    // read_hi 는 주소와 함께 걸리고 데이터는 한 클럭 뒤에 나온다. 선택은
    // 데이터가 나온 뒤에 하므로 read_hi 도 한 클럭 늦춰야 짝이 맞는다.
    reg read_hi_d1;
    always @(posedge clk_b) read_hi_d1 <= read_hi;

    assign read_data = read_hi_d1 ? dout_hi : dout_lo;

endmodule
