`timescale 1ns / 1ps
// =============================================================================
// tdc_axi_regs.v  —  TDC 제어/상태 레지스터 (AXI4-Lite 슬레이브)
// Generated by Claude Code, 2026-09-04
//
//  [무엇인가]
//  PS(ARM)가 AXI4-Lite 로 TDC 를 제어하고 상태를 읽는 창구다.
//
//  [★ 2026-09-05 — 2단계. 히스토그램을 AXI 로 읽는다]
//  1단계 주석에는 "대용량 메모리는 AXI BRAM Controller IP 가 맡는다"고 적혀
//  있었다. 2단계에서 그 방침을 뒤집었다. 왜:
//    - 히스토그램은 읽기 전용 384워드뿐이라 IP 를 하나 더 얹을 값어치가 없다.
//    - BRAM 은 이미 tdc_histogram.v 안에 RTL 로 추론돼 있다. AXI BRAM Controller
//      는 원래 Block Memory Generator IP 와 짝을 이루는 물건이라, RTL 배열에
//      붙이려면 BRAM 인터페이스를 BD 밖으로 빼서 손으로 이어야 한다.
//    - 캐리체인 배치 제약(SLICE LOC/BEL)이 RTL 계층 이름에 묶여 있어, 설계를
//      BD 로 옮길수록 제약이 깨질 위험이 커진다. "PS 만 BD, TDC 는 RTL" 경계를
//      유지하는 편이 안전하다.
//  대신 Port B 의 클럭을 s_axi_aclk 로 옮겨서(= tdc_histogram.v 변경) AXI 쪽은
//  전부 동기 논리가 되게 했다. 그래서 히스토그램 읽기에는 CDC 가 아예 없다.
//  교정표(4단계)는 쓰기가 필요하고 타임스탬프 파이프라인이 매 클럭 읽으므로
//  사정이 다르다. 그때 다시 판단할 것.
//
//  [구현 범위]
//   1단계 : ID / BUILD / CTRL / STATUS / DNA
//   2단계 : + RO_CNT / DIE_TEMP / PHASE / HISTO[0..383]
//           -> ILA 와 BTNU 버튼 없이 Vitis 만으로 Mode 1 측정이 끝난다.
//   이후   : CAP_N / DANGER / CAP_CNT / 캡처버퍼 (3단계)
//
//  [클럭이 두 개인 이유]
//    s_axi_aclk : PS 의 FCLK_CLK0 (100 MHz).
//                 Zynq-7000 의 M_AXI_GP 포트 상한이 150 MHz 라 TDC 의 200 MHz 를
//                 그대로 쓸 수 없다.
//    tdc_clk    : 200 MHz.
//                 clk_wiz_0 에 100 MHz 출력을 하나 더 만들면 두 클럭을 동기로
//                 맞출 수 있지만, 교정 전체가 이 MMCM 의 200 MHz 특성에 달려
//                 있으므로 MMCM 은 건드리지 않는다. 대신 아래처럼 CDC 를 한다.
//
//  [★ CDC — 토글 핸드셰이크 하나로 처리한다]
//  CTRL 은 HIT_SRC(2비트)와 START 를 한 워드에 담는다. 비트마다 따로 2FF 동기화하면
//  START 가 HIT_SRC 보다 한 클럭 먼저 도착할 수 있고, 그러면 시퀀서가 엉뚱한 모드로
//  출발한다. 그래서 데이터는 그대로 두고 "썼다"는 토글 1비트만 건너보낸 뒤,
//  TDC 쪽이 그 토글이 바뀐 것을 보고 레지스터 전체를 한꺼번에 래치한다.
//  토글이 2단 동기화를 거치는 동안(TDC 클럭 2개 이상) 데이터는 이미 안정돼 있다.
//  STATUS 의 단일 비트들은 서로 정합이 필요 없으므로 비트별 2FF 로 충분하다.
// =============================================================================

module tdc_axi_regs #(
    // ★ 2026-09-05 : 8 -> 16. 히스토그램 창(0x1000~0x15FF)을 담으려면 주소 비트 12가
    //   필요하다. 8비트로는 0x1000 이 0x00 으로 접혀 ID 레지스터와 충돌한다.
    parameter integer C_S_AXI_ADDR_WIDTH = 16,    // 64 KB 어퍼처 전체
    parameter integer CHAIN_STAGES       = 96,    // BUILD 레지스터에 실어 보낼 값
    parameter [7:0]   REGMAP_VER         = 8'd6   // ★ 2026-09-05 : 5 -> 6 (DANGER 레지스터)
)(
    // ---------------- AXI4-Lite 슬레이브 (s_axi_aclk 도메인) ----------------
    input  wire                            s_axi_aclk,
    input  wire                            s_axi_aresetn,

    input  wire [C_S_AXI_ADDR_WIDTH-1:0]   s_axi_awaddr,
    input  wire                            s_axi_awvalid,
    output wire                            s_axi_awready,
    input  wire [31:0]                     s_axi_wdata,
    input  wire [3:0]                      s_axi_wstrb,
    input  wire                            s_axi_wvalid,
    output wire                            s_axi_wready,
    output wire [1:0]                      s_axi_bresp,
    output wire                            s_axi_bvalid,
    input  wire                            s_axi_bready,

    input  wire [C_S_AXI_ADDR_WIDTH-1:0]   s_axi_araddr,
    input  wire                            s_axi_arvalid,
    output wire                            s_axi_arready,
    output wire [31:0]                     s_axi_rdata,
    output wire [1:0]                      s_axi_rresp,
    output wire                            s_axi_rvalid,
    input  wire                            s_axi_rready,

    // ---------------- TDC 도메인 ----------------
    input  wire                            tdc_clk,
    input  wire                            tdc_rst_n,

    // 상태 입력 (TDC 도메인 -> 이 모듈이 AXI 도메인으로 동기화한다)
    input  wire                            stat_mmcm_locked,
    input  wire [30:0]                     stat_dna,
    input  wire                            stat_dna_valid,
    input  wire                            stat_busy,
    input  wire                            stat_done,
    input  wire                            stat_phase_busy,

    // ★ 2026-09-05 추가 : 측정 조건 (RO 주파수 / 다이 온도)
    //   stat_meas_strobe 는 10 ms 게이트마다 1클럭 뜨는 "값 갱신 완료" 펄스다.
    //   이 펄스로 토글을 만들어 AXI 쪽이 그때만 32/16비트를 통째로 래치한다.
    //   왜 비트별 2FF 로 하지 않나 : ro_cnt 는 32비트라 갱신 순간에 걸리면
    //   상위·하위가 섞인 값이 읽힌다. 10 ms(=AXI 100만 클럭)에 한 번뿐이라
    //   드물지만 0 은 아니고, 그렇게 나온 값은 조용히 틀린다.
    input  wire                            stat_meas_strobe,
    input  wire [31:0]                     stat_ro_cnt,
    input  wire [15:0]                     stat_die_temp,
    input  wire [8:0]                      stat_phase_cur,

    // ★ 2026-09-05 추가 : 시퀀서 상태 (전부 tdc_clk 도메인)
    //   snap_tgl 이 바뀔 때 아래 값들을 한꺼번에 래치한다. 누적 중에는 10 ms 마다,
    //   상태가 넘어갈 때는 그 즉시 토글이 온다. 값들이 서로 정합해야 하므로
    //   (예: hit_cnt 와 ro_at_end 가 같은 시점의 것이어야 한다) 토글 하나로 묶는다.
    input  wire                            stat_snap_tgl,
    input  wire [31:0]                     stat_hit_cnt,
    input  wire [31:0]                     stat_drop_cnt,
    input  wire [31:0]                     stat_ro_start,
    input  wire [31:0]                     stat_ro_end,
    input  wire [15:0]                     stat_temp_start,
    input  wire [15:0]                     stat_temp_end,
    input  wire [2:0]                      stat_state,

    // ★ 2026-09-05 추가 : 히스토그램 읽기 창 (전부 s_axi_aclk 도메인)
    //   tdc_histogram 의 BRAM Port B 에 직접 붙는다. Port B 클럭이 s_axi_aclk 라
    //   여기에는 CDC 가 없다. 읽기 지연 1클럭은 아래 §3 에서 처리한다.
    output reg  [8:0]                      histo_addr,
    input  wire [31:0]                     histo_data,

    // ★ 2026-09-05 추가 : 캡처 버퍼 읽기 창 (s_axi_aclk 도메인)
    output reg  [11:0]                     cap_addr,
    output reg                             cap_hi,
    input  wire [31:0]                     cap_data,
    input  wire [12:0]                     stat_cap_cnt,

    // 제어 출력 (AXI 도메인 -> 이 모듈이 TDC 도메인으로 동기화해서 내보낸다)
    output reg  [1:0]                      ctrl_hit_src,   // 00=off 01=RO 10=DPS 11=EXT
    output reg                             ctrl_start,
    output reg                             ctrl_stop,
    output reg                             ctrl_histo_clr,
    output reg                             ctrl_tdc_rst,
    output reg                             ctrl_cap_fmt,
    output reg  [8:0]                      ctrl_phase_tgt, // ★ 2026-09-05 : BTNU 대체
    output reg  [31:0]                     ctrl_target_hits,
    output reg  [31:0]                     ctrl_settle_n,
    output reg  [12:0]                     ctrl_cap_n,
    output reg  [8:0]                      ctrl_danger_lo,
    output reg  [8:0]                      ctrl_danger_hi
);

    // ---------------- 레지스터 주소 (워드 단위) ----------------
    localparam [5:0] A_ID     = 6'h0,   // 0x00  R   매직값
                     A_BUILD  = 6'h1,   // 0x04  R   빌드 정보
                     A_CTRL   = 6'h2,   // 0x08  RW  제어
                     A_STATUS = 6'h3,   // 0x0C  R   상태
                     A_DNA    = 6'h4,   // 0x10  R   보드 식별자
                     // ★ 2026-09-05 추가
                     // ★ RO_CNT 는 에지 수지 Hz 가 아니다. 환산식을 여기 박아둔다 —
                     //   이 식이 코드에 없어서 2026-09-04 문서가 2배 틀린 값을 실었다.
                     //     ro_divider_cnt 는 RO 상승엣지마다 +1 (tdc_test_top.v)
                     //     측정 탭이 [1] 이므로 그 비트는 4번 증가마다 한 주기
                     //     ro_edge 는 상승엣지만 세므로 RO 4주기당 1카운트
                     //   ->  f_RO [Hz] = RO_CNT x 4 / 0.01 s
                     //   ->  히트율   = f_RO / 64   (hit_random = ro_divider_cnt[5])
                     //   검증 : 2026-09-05 3단계에서 RO_CNT 168,194 -> 67.28 MHz
                     //          -> 히트율 1.051 MHz, 실측 200만발/1.9초 = 1.05 MHz.
                     A_ROCNT  = 6'h5,   // 0x14  R   RO 에지 수 / 10 ms 게이트
                     A_TEMP   = 6'h6,   // 0x18  R   [15:0] XADC 온도 raw
                     A_PHASE  = 6'h7,   // 0x1C  RW  [8:0] 목표, [24:16] 현재 위상
                     // ★ 2026-09-05 추가 — 시퀀서 (맵 버전 4)
                     A_TARGET = 6'h8,   // 0x20  RW  목표 히트 수
                     A_HITCNT = 6'h9,   // 0x24  R   실제 누적된 히트 수
                     A_SETTLE = 6'hA,   // 0x28  RW  RO 안정화 대기 클럭 수
                     A_ROSTA  = 6'hB,   // 0x2C  R   측정 시작 시 RO 에지 수
                     A_ROEND  = 6'hC,   // 0x30  R   측정 종료 시 RO 에지 수
                     A_TEMPSE = 6'hD,   // 0x34  R   {끝 온도[31:16], 시작 온도[15:0]}
                     A_DROP   = 6'hE,   // 0x38  R   데드타임에 버려진 히트 수
                     // ★ 2026-09-05 추가 — 캡처 버퍼 (맵 버전 5)
                     A_CAPN   = 6'hF,   // 0x3C  RW  캡처할 히트 수 (1..4096)
                     A_CAPCNT = 6'h10,  // 0x40  R   지금까지 모인 수
                     // ★ 2026-09-05 : danger 임계값 (맵 버전 6)
                     //   {danger_hi[24:16], danger_lo[8:0]}. 기본 220/40.
                     //   이 값은 "히트가 클럭 에지 근처인가" 를 fine 탭 번호로
                     //   판단하는 경계다. 창(히트가 찍히는 탭 범위)의 위치가
                     //   히트 경로 지연에 따라 미끄러지므로 상수로 둘 수 없다.
                     //   상세는 tdc_fmcw_core_co.v 의 danger_lo 포트 주석 참조.
                     A_DANGER = 6'h11;  // 0x44  RW

    // ★ 2026-09-05 : 영역 구분은 주소 비트 12 로 한다.
    //   addr[12]=0 -> 위 레지스터들 (0x0000~0x0FFF, 하위 8비트만 디코딩)
    //   addr[12]=1 -> 히스토그램   (0x1000 + 탭*4, 탭 0..383 이면 0x1000~0x15FF)
    //   64K 어퍼처 안이므로 BD 의 주소 할당은 그대로 두면 된다.
    localparam integer HISTO_SEL_BIT = 12;

    // ★ 2026-09-05 : 캡처 버퍼는 어퍼처 위쪽 절반(0x8000~0xFFFF, 32 KB)에 둔다.
    //   히트 하나가 8바이트(2워드)이므로 4096발이 딱 32 KB 다.
    //     주소 = 0x8000 + 히트번호*8 + (0=하위 워드, 4=상위 워드)
    //     히트번호 = addr[14:3],  워드 선택 = addr[2]
    //   히스토그램(비트 12)과 겹치지 않도록 최상위 비트로 갈랐다.
    localparam integer CAP_SEL_BIT = 15;

    localparam [31:0] ID_MAGIC   = 32'h5444_4302;         // "TD" "C" + regmap ver
    localparam [15:0] NUM_TAPS_C = CHAIN_STAGES * 4;

    // =========================================================================
    // 1. AXI 쓰기 채널
    //    AXI4-Lite 는 버스트가 없으므로 주소와 데이터가 모두 왔을 때 한 번에 받는다.
    //    AWREADY 가 AWVALID 에 의존하는 것은 AXI 규격상 허용된다
    //    (금지된 것은 그 반대, 즉 VALID 가 READY 에 의존하는 것이다).
    // =========================================================================
    reg [31:0] ctrl_reg;
    reg [8:0]  phase_reg;         // ★ 2026-09-05 : 목표 위상 (0..279)
    reg [31:0] target_reg;        // ★ 2026-09-05 : 목표 히트 수
    // SETTLE_N 기본 20,000 클럭 = 100 us @ 200 MHz.
    //  ★ 이 값은 근거 있는 값이 아니다. RO 를 껐다 켠 직후 거동이 측정된 적이
    //    없어 넉넉히 잡은 것이다. RO_CNT 가 몇 게이트 만에 수렴하는지 재서
    //    실측값으로 바꿀 것.
    reg [31:0] settle_reg = 32'd20000;
    reg [12:0] cap_n_reg   = 13'd4096;   // ★ 2026-09-05 : 캡처할 히트 수
    reg [8:0]  danger_lo_reg = 9'd40;    // ★ 2026-09-05 : 종전 상수와 같은 기본값
    reg [8:0]  danger_hi_reg = 9'd220;
    reg        ctrl_upd_tgl;      // CTRL/PHASE 를 쓸 때마다 토글. CDC 용.
    reg        bvalid_r;

    wire wr_go = s_axi_awvalid & s_axi_wvalid & ~bvalid_r;

    assign s_axi_awready = wr_go;
    assign s_axi_wready  = wr_go;
    assign s_axi_bvalid  = bvalid_r;
    assign s_axi_bresp   = 2'b00;   // 항상 OKAY. 없는 주소에 써도 조용히 무시한다.

    wire [5:0] wr_word = s_axi_awaddr[7:2];

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            ctrl_reg     <= 32'd0;
            phase_reg    <= 9'd0;
            target_reg   <= 32'd0;
            settle_reg   <= 32'd20000;
            cap_n_reg    <= 13'd4096;
            danger_lo_reg <= 9'd40;
            danger_hi_reg <= 9'd220;
            ctrl_upd_tgl <= 1'b0;
            bvalid_r     <= 1'b0;
        end else begin
            if (wr_go) begin
                if (wr_word == A_CTRL) begin
                    if (s_axi_wstrb[0]) ctrl_reg[ 7: 0] <= s_axi_wdata[ 7: 0];
                    if (s_axi_wstrb[1]) ctrl_reg[15: 8] <= s_axi_wdata[15: 8];
                    if (s_axi_wstrb[2]) ctrl_reg[23:16] <= s_axi_wdata[23:16];
                    if (s_axi_wstrb[3]) ctrl_reg[31:24] <= s_axi_wdata[31:24];
                    ctrl_upd_tgl <= ~ctrl_upd_tgl;
                end
                // ★ 2026-09-05 : PHASE 도 같은 토글을 쓴다.
                //   토글 하나로 두 레지스터를 함께 래치하므로, 어느 쪽을 써도
                //   TDC 도메인은 둘 다 최신값으로 갱신한다. 토글을 따로 두면
                //   토글 2개의 도착 순서를 또 따져야 해서 오히려 위험하다.
                if (wr_word == A_PHASE) begin
                    if (s_axi_wstrb[0]) phase_reg[7:0] <= s_axi_wdata[7:0];
                    if (s_axi_wstrb[1]) phase_reg[8]   <= s_axi_wdata[8];
                    ctrl_upd_tgl <= ~ctrl_upd_tgl;
                end
                // ★ 2026-09-05 : TARGET/SETTLE 도 같은 토글에 실어 보낸다.
                //   32비트라 바이트 스트로브를 그대로 존중한다.
                if (wr_word == A_TARGET) begin
                    if (s_axi_wstrb[0]) target_reg[ 7: 0] <= s_axi_wdata[ 7: 0];
                    if (s_axi_wstrb[1]) target_reg[15: 8] <= s_axi_wdata[15: 8];
                    if (s_axi_wstrb[2]) target_reg[23:16] <= s_axi_wdata[23:16];
                    if (s_axi_wstrb[3]) target_reg[31:24] <= s_axi_wdata[31:24];
                    ctrl_upd_tgl <= ~ctrl_upd_tgl;
                end
                if (wr_word == A_CAPN) begin
                    if (s_axi_wstrb[0]) cap_n_reg[ 7:0] <= s_axi_wdata[ 7:0];
                    if (s_axi_wstrb[1]) cap_n_reg[12:8] <= s_axi_wdata[12:8];
                    ctrl_upd_tgl <= ~ctrl_upd_tgl;
                end
                if (wr_word == A_DANGER) begin
                    if (s_axi_wstrb[0]) danger_lo_reg[7:0] <= s_axi_wdata[7:0];
                    if (s_axi_wstrb[1]) danger_lo_reg[8]   <= s_axi_wdata[8];
                    if (s_axi_wstrb[2]) danger_hi_reg[7:0] <= s_axi_wdata[23:16];
                    if (s_axi_wstrb[3]) danger_hi_reg[8]   <= s_axi_wdata[24];
                    ctrl_upd_tgl <= ~ctrl_upd_tgl;
                end
                if (wr_word == A_SETTLE) begin
                    if (s_axi_wstrb[0]) settle_reg[ 7: 0] <= s_axi_wdata[ 7: 0];
                    if (s_axi_wstrb[1]) settle_reg[15: 8] <= s_axi_wdata[15: 8];
                    if (s_axi_wstrb[2]) settle_reg[23:16] <= s_axi_wdata[23:16];
                    if (s_axi_wstrb[3]) settle_reg[31:24] <= s_axi_wdata[31:24];
                    ctrl_upd_tgl <= ~ctrl_upd_tgl;
                end
                bvalid_r <= 1'b1;
            end else if (bvalid_r && s_axi_bready) begin
                bvalid_r <= 1'b0;
            end
        end
    end

    // =========================================================================
    // 2. 상태 입력 동기화 (TDC -> AXI 도메인)
    //    STATUS 의 단일 비트들은 서로 정합이 필요 없어 비트별 2FF 로 충분하다.
    //    DNA 는 dna_valid 가 뜬 뒤로 변하지 않는 상수라 2FF 로 안전하다.
    // =========================================================================
    (* ASYNC_REG = "TRUE" *) reg [4:0]  st_d1, st_d2;
    (* ASYNC_REG = "TRUE" *) reg [30:0] dna_d1, dna_d2;

    wire [4:0] st_raw = { stat_phase_busy, stat_done, stat_busy,
                          stat_dna_valid, stat_mmcm_locked };

    always @(posedge s_axi_aclk) begin
        st_d1  <= st_raw;     st_d2  <= st_d1;
        dna_d1 <= stat_dna;   dna_d2 <= dna_d1;
    end

    // ---- ★ 2026-09-05 : RO 카운트 / 다이 온도 (다중 비트, 10 ms 마다 갱신) ----
    //   TDC 도메인에서 meas_strobe 로 토글을 만들고, AXI 도메인이 그 토글의
    //   변화를 보고 32/16비트를 통째로 래치한다. CTRL 의 토글 핸드셰이크와
    //   같은 방식이되 방향만 반대다.
    //   왜 안전한가 : 데이터는 다음 게이트까지 10 ms 동안 그대로 있으므로,
    //   토글이 2FF 를 통과하는 20 ns 사이에 값이 바뀔 수 없다.
    reg meas_tgl = 1'b0;
    always @(posedge tdc_clk or negedge tdc_rst_n) begin
        if (!tdc_rst_n)             meas_tgl <= 1'b0;
        else if (stat_meas_strobe)  meas_tgl <= ~meas_tgl;
    end

    (* ASYNC_REG = "TRUE" *) reg mt_d1 = 1'b0, mt_d2 = 1'b0;
    reg mt_d3 = 1'b0;
    reg [31:0] ro_cnt_lat   = 32'd0;
    reg [15:0] die_temp_lat = 16'd0;

    always @(posedge s_axi_aclk) begin
        mt_d1 <= meas_tgl;   // 동기화 1단 (비동기 입력)
        mt_d2 <= mt_d1;      // 동기화 2단 (메타스테이빌리티 해소)
        mt_d3 <= mt_d2;      // 에지 검출용
        if (mt_d2 ^ mt_d3) begin
            ro_cnt_lat   <= stat_ro_cnt;
            die_temp_lat <= stat_die_temp;
        end
    end

    // ---- ★ 2026-09-05 : 시퀀서 스냅샷 (다중 비트 6종) ----
    //   snap_tgl 이 바뀔 때 여섯 값을 한꺼번에 래치한다. 토글을 하나로 묶은 이유는
    //   값들이 서로 정합해야 하기 때문이다 — hit_cnt 와 ro_at_end 가 다른 시점의
    //   것이면 "이 측정의 조건" 이라는 말 자체가 성립하지 않는다.
    (* ASYNC_REG = "TRUE" *) reg sn_d1 = 1'b0, sn_d2 = 1'b0;
    reg sn_d3 = 1'b0;
    reg [31:0] hit_cnt_lat  = 32'd0, drop_cnt_lat = 32'd0;
    reg [31:0] ro_sta_lat   = 32'd0, ro_end_lat   = 32'd0;
    reg [15:0] tmp_sta_lat  = 16'd0, tmp_end_lat  = 16'd0;

    always @(posedge s_axi_aclk) begin
        sn_d1 <= stat_snap_tgl;
        sn_d2 <= sn_d1;
        sn_d3 <= sn_d2;
        if (sn_d2 ^ sn_d3) begin
            hit_cnt_lat  <= stat_hit_cnt;
            drop_cnt_lat <= stat_drop_cnt;
            ro_sta_lat   <= stat_ro_start;
            ro_end_lat   <= stat_ro_end;
            tmp_sta_lat  <= stat_temp_start;
            tmp_end_lat  <= stat_temp_end;
        end
    end

    // ---- ★ 2026-09-05 : 현재 위상 (9비트) ----
    //   주의 : 이 값은 PHASE_BUSY 가 0 일 때만 믿을 것.
    //   위상이 움직이는 중에는 2FF 통과 시점에 따라 옛값/새값이 섞일 수 있다.
    //   소프트웨어는 어차피 "목표를 쓰고 -> BUSY 가 0 이 될 때까지 기다리고 ->
    //   현재 위상을 읽는" 순서로 쓰므로 실제로는 문제되지 않는다.
    (* ASYNC_REG = "TRUE" *) reg [8:0] ph_d1 = 9'd0, ph_d2 = 9'd0;
    always @(posedge s_axi_aclk) begin
        ph_d1 <= stat_phase_cur;
        ph_d2 <= ph_d1;
    end

    // ★ 2026-09-05 : 시퀀서 상태를 STATUS[10:8] 에 실어 보낸다.
    //   FSM 이 어느 상태에서 멈췄는지 PS 가 바로 볼 수 있어야 디버깅이 된다.
    //   3비트라 비트별 2FF 로도 잠깐 섞일 수 있으나, 상태는 사람이 폴링해서
    //   보는 용도이고 잘못 읽어도 다음 폴링에서 바로잡힌다.
    (* ASYNC_REG = "TRUE" *) reg [2:0] sstate_d1, sstate_d2;
    always @(posedge s_axi_aclk) begin
        sstate_d1 <= stat_state;
        sstate_d2 <= sstate_d1;
    end

    wire [31:0] status_word = { 21'd0,
                                sstate_d2,   // [10:8] 시퀀서 상태 (0..5)
                                2'd0,        // [7:6] 예약
                                st_d2[4],    // [5] PHASE_BUSY
                                st_d2[3],    // [4] DONE
                                st_d2[2],    // [3] BUSY
                                st_d2[1],    // [2] DNA_VALID
                                1'b0,        // [1] 예약
                                st_d2[0] };  // [0] MMCM_LOCKED

    // =========================================================================
    // 3. AXI 읽기 채널
    // =========================================================================
    reg [31:0] rdata_r;
    reg        rvalid_r;

    // ★ 2026-09-05 : 히스토그램 읽기는 BRAM 을 거치므로 즉답이 안 된다.
    //   BRAM Port B 출력이 레지스터드라, 주소를 걸고 나서 데이터가 나오기까지
    //   시간이 걸린다. 정확히는 이 순서다.
    //     T   : rd_go. histo_addr 에 주소를 실어 둔다(다음 클럭부터 유효).
    //     T+1 : BRAM 이 그 주소를 샘플링한다.
    //     T+2 : histo_data 가 유효해진다. 여기서 잡아 rvalid 를 올린다.
    //   hpend 는 이 2클럭을 세는 시프트 레지스터다.
    //   이걸 안 하고 즉시 rvalid 를 올리면 '직전 주소의 값'이 읽힌다 —
    //   ILA 시절 probe_read_addr_d1 로 해결했던 것과 정확히 같은 함정이다.
    reg [1:0] hpend = 2'b00;
    reg       cap_rd = 1'b0;         // 이번 읽기가 캡처 버퍼인가
    wire      histo_busy = |hpend;

    // cap_cnt 는 tdc_clk 도메인의 13비트다. 캡처 중에는 계속 변하므로 2FF 로
    // 넘긴다 — 진행 상황을 사람이 폴링해서 보는 값이라 한 번 잘못 읽어도
    // 다음 폴링에서 바로잡힌다. 최종값은 DONE 이 뜬 뒤에 읽으면 정확하다.
    (* ASYNC_REG = "TRUE" *) reg [12:0] cap_cnt_d1, cap_cnt_d2;
    always @(posedge s_axi_aclk) begin
        cap_cnt_d1 <= stat_cap_cnt;
        cap_cnt_d2 <= cap_cnt_d1;
    end

    // 진행 중인 히스토그램 읽기가 있으면 새 요청을 받지 않는다.
    wire rd_go   = s_axi_arvalid & ~rvalid_r & ~histo_busy;
    wire is_cap  = s_axi_araddr[CAP_SEL_BIT];                        // 0x8000 이상
    wire is_hist = ~s_axi_araddr[CAP_SEL_BIT] & s_axi_araddr[HISTO_SEL_BIT];

    assign s_axi_arready = rd_go;
    assign s_axi_rvalid  = rvalid_r;
    assign s_axi_rdata   = rdata_r;
    assign s_axi_rresp   = 2'b00;   // 항상 OKAY

    wire [5:0] rd_word = s_axi_araddr[7:2];

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            rdata_r    <= 32'd0;
            rvalid_r   <= 1'b0;
            hpend      <= 2'b00;
            histo_addr <= 9'd0;
            cap_addr   <= 12'd0;
            cap_hi     <= 1'b0;
            cap_rd     <= 1'b0;
        end else begin
            hpend <= { hpend[0], 1'b0 };     // 기본은 한 칸 밀기

            if (rd_go && is_hist) begin
                // 0x1000 + 탭*4 -> 탭 번호는 주소 비트 [10:2]
                histo_addr <= s_axi_araddr[10:2];
                hpend      <= 2'b01;
                cap_rd     <= 1'b0;
            end else if (rd_go && is_cap) begin
                // ★ 0x8000 + 히트번호*8 + (0 또는 4)
                //   히트번호 = addr[14:3], 워드 선택 = addr[2]
                //   히스토그램과 같은 2클럭 지연을 쓴다 (BRAM 출력이 레지스터드).
                cap_addr <= s_axi_araddr[14:3];
                cap_hi   <= s_axi_araddr[2];
                hpend    <= 2'b01;
                cap_rd   <= 1'b1;
            end else if (rd_go) begin
                case (rd_word)
                    A_ID:     rdata_r <= ID_MAGIC;
                    A_BUILD:  rdata_r <= { NUM_TAPS_C, CHAIN_STAGES[7:0], REGMAP_VER };
                    A_CTRL:   rdata_r <= ctrl_reg;
                    A_STATUS: rdata_r <= status_word;
                    A_DNA:    rdata_r <= { st_d2[1], dna_d2 };   // [31] = dna_valid
                    A_ROCNT:  rdata_r <= ro_cnt_lat;
                    A_TEMP:   rdata_r <= { 16'd0, die_temp_lat };
                    A_PHASE:  rdata_r <= { 7'd0, ph_d2, 7'd0, phase_reg };
                    A_TARGET: rdata_r <= target_reg;
                    A_HITCNT: rdata_r <= hit_cnt_lat;
                    A_SETTLE: rdata_r <= settle_reg;
                    A_ROSTA:  rdata_r <= ro_sta_lat;
                    A_ROEND:  rdata_r <= ro_end_lat;
                    A_TEMPSE: rdata_r <= { tmp_end_lat, tmp_sta_lat };
                    A_DROP:   rdata_r <= drop_cnt_lat;
                    A_CAPN:   rdata_r <= { 19'd0, cap_n_reg };
                    A_CAPCNT: rdata_r <= { 19'd0, cap_cnt_d2 };
                    A_DANGER: rdata_r <= { 7'd0, danger_hi_reg, 7'd0, danger_lo_reg };
                    default:  rdata_r <= 32'hDEAD_0000;          // 없는 주소를 눈에 띄게
                endcase
                rvalid_r <= 1'b1;
            end else if (hpend[1]) begin
                rdata_r  <= cap_rd ? cap_data : histo_data;  // BRAM 출력 유효 사이클
                rvalid_r <= 1'b1;
            end else if (rvalid_r && s_axi_rready) begin
                rvalid_r <= 1'b0;
            end
        end
    end

    // =========================================================================
    // 4. 제어 출력 동기화 (AXI -> TDC 도메인)
    //    ★ 토글 핸드셰이크. 파일 상단 [CDC] 주석 참조.
    //    토글이 2단 동기화되는 동안 ctrl_reg 는 이미 안정돼 있으므로,
    //    토글이 바뀐 시점에 통째로 래치하면 비트 간 스큐가 생기지 않는다.
    // =========================================================================
    (* ASYNC_REG = "TRUE" *) reg tgl_d1, tgl_d2;
    reg tgl_d3;

    always @(posedge tdc_clk or negedge tdc_rst_n) begin
        if (!tdc_rst_n) begin
            tgl_d1 <= 1'b0; tgl_d2 <= 1'b0; tgl_d3 <= 1'b0;
            ctrl_hit_src   <= 2'b00;
            ctrl_start     <= 1'b0;
            ctrl_stop      <= 1'b0;
            ctrl_histo_clr <= 1'b0;
            ctrl_tdc_rst   <= 1'b0;
            ctrl_cap_fmt   <= 1'b0;
            ctrl_phase_tgt <= 9'd0;
            ctrl_target_hits <= 32'd0;
            ctrl_settle_n    <= 32'd20000;
            ctrl_cap_n       <= 13'd4096;
            ctrl_danger_lo   <= 9'd40;
            ctrl_danger_hi   <= 9'd220;
        end else begin
            tgl_d1 <= ctrl_upd_tgl;   // 동기화 1단 (비동기 입력)
            tgl_d2 <= tgl_d1;         // 동기화 2단 (메타스테이빌리티 해소)
            tgl_d3 <= tgl_d2;         // 에지 검출용

            if (tgl_d2 ^ tgl_d3) begin
                ctrl_hit_src   <= ctrl_reg[1:0];
                ctrl_start     <= ctrl_reg[2];
                ctrl_stop      <= ctrl_reg[3];
                ctrl_histo_clr <= ctrl_reg[4];
                ctrl_tdc_rst   <= ctrl_reg[5];
                ctrl_cap_fmt   <= ctrl_reg[6];
                ctrl_phase_tgt   <= phase_reg;   // ★ 2026-09-05
                ctrl_target_hits <= target_reg;
                ctrl_settle_n    <= settle_reg;
                ctrl_cap_n       <= cap_n_reg;
                ctrl_danger_lo   <= danger_lo_reg;
                ctrl_danger_hi   <= danger_hi_reg;
            end
        end
    end

endmodule
