`timescale 1ns / 1ps
// =============================================================================
// tdc_axi_regs.v  —  TDC 제어/상태 레지스터 (AXI4-Lite 슬레이브)
// Generated by Claude Code, 2026-09-04
//
//  [무엇인가]
//  PS(ARM)가 AXI4-Lite 로 TDC 를 제어하고 상태를 읽는 창구다.
//  대용량 메모리(교정표/히스토그램/캡처버퍼)는 여기 없다 — 그건 Xilinx
//  AXI BRAM Controller IP 가 따로 맡는다. 이 모듈은 스칼라 레지스터만 다룬다.
//  그래야 우리가 직접 짜는 AXI 로직이 최소로 유지된다.
//
//  [1단계 범위]
//  ID / BUILD / CTRL / STATUS / DNA 만 구현한다. 데이터패스는 아직 안 붙인다.
//  PS 가 0x00 에서 0x54444302 를 읽으면 PL-PS 경로가 살아 있다는 뜻이고,
//  0x10 에서 DNA(0x3D996854)가 나오면 TDC 도메인까지 이어진 것이다.
//  CAP_N / PHASE_TGT / DANGER / CAP_CNT / DIE_TEMP / RO_FREQ 는 2단계 이후.
//
//  [클럭이 두 개인 이유]
//    s_axi_aclk : PS 의 FCLK_CLK0 (100 MHz).
//                 Zynq-7000 의 M_AXI_GP 포트 상한이 150 MHz 라 TDC 의 200 MHz 를
//                 그대로 쓸 수 없다.
//    tdc_clk    : 200 MHz.
//                 clk_wiz_0 에 100 MHz 출력을 하나 더 만들면 두 클럭을 동기로
//                 맞출 수 있지만, 교정 전체가 이 MMCM 의 200 MHz 특성에 달려
//                 있으므로 MMCM 은 건드리지 않는다. 대신 아래처럼 CDC 를 한다.
//
//  [★ CDC — 토글 핸드셰이크 하나로 처리한다]
//  CTRL 은 HIT_SRC(2비트)와 START 를 한 워드에 담는다. 비트마다 따로 2FF 동기화하면
//  START 가 HIT_SRC 보다 한 클럭 먼저 도착할 수 있고, 그러면 시퀀서가 엉뚱한 모드로
//  출발한다. 그래서 데이터는 그대로 두고 "썼다"는 토글 1비트만 건너보낸 뒤,
//  TDC 쪽이 그 토글이 바뀐 것을 보고 레지스터 전체를 한꺼번에 래치한다.
//  토글이 2단 동기화를 거치는 동안(TDC 클럭 2개 이상) 데이터는 이미 안정돼 있다.
//  STATUS 의 단일 비트들은 서로 정합이 필요 없으므로 비트별 2FF 로 충분하다.
// =============================================================================

module tdc_axi_regs #(
    parameter integer C_S_AXI_ADDR_WIDTH = 8,     // 64 워드. 상위 주소는 별칭으로 접힌다
    parameter integer CHAIN_STAGES       = 96,    // BUILD 레지스터에 실어 보낼 값
    parameter [7:0]   REGMAP_VER         = 8'd2
)(
    // ---------------- AXI4-Lite 슬레이브 (s_axi_aclk 도메인) ----------------
    input  wire                            s_axi_aclk,
    input  wire                            s_axi_aresetn,

    input  wire [C_S_AXI_ADDR_WIDTH-1:0]   s_axi_awaddr,
    input  wire                            s_axi_awvalid,
    output wire                            s_axi_awready,
    input  wire [31:0]                     s_axi_wdata,
    input  wire [3:0]                      s_axi_wstrb,
    input  wire                            s_axi_wvalid,
    output wire                            s_axi_wready,
    output wire [1:0]                      s_axi_bresp,
    output wire                            s_axi_bvalid,
    input  wire                            s_axi_bready,

    input  wire [C_S_AXI_ADDR_WIDTH-1:0]   s_axi_araddr,
    input  wire                            s_axi_arvalid,
    output wire                            s_axi_arready,
    output wire [31:0]                     s_axi_rdata,
    output wire [1:0]                      s_axi_rresp,
    output wire                            s_axi_rvalid,
    input  wire                            s_axi_rready,

    // ---------------- TDC 도메인 ----------------
    input  wire                            tdc_clk,
    input  wire                            tdc_rst_n,

    // 상태 입력 (TDC 도메인 -> 이 모듈이 AXI 도메인으로 동기화한다)
    input  wire                            stat_mmcm_locked,
    input  wire [30:0]                     stat_dna,
    input  wire                            stat_dna_valid,
    input  wire                            stat_busy,
    input  wire                            stat_done,
    input  wire                            stat_phase_busy,

    // 제어 출력 (AXI 도메인 -> 이 모듈이 TDC 도메인으로 동기화해서 내보낸다)
    output reg  [1:0]                      ctrl_hit_src,   // 00=off 01=RO 10=DPS 11=EXT
    output reg                             ctrl_start,
    output reg                             ctrl_stop,
    output reg                             ctrl_histo_clr,
    output reg                             ctrl_tdc_rst,
    output reg                             ctrl_cap_fmt
);

    // ---------------- 레지스터 주소 (워드 단위) ----------------
    localparam [5:0] A_ID     = 6'h0,   // 0x00  R   매직값
                     A_BUILD  = 6'h1,   // 0x04  R   빌드 정보
                     A_CTRL   = 6'h2,   // 0x08  RW  제어
                     A_STATUS = 6'h3,   // 0x0C  R   상태
                     A_DNA    = 6'h4;   // 0x10  R   보드 식별자

    localparam [31:0] ID_MAGIC   = 32'h5444_4302;         // "TD" "C" + regmap ver
    localparam [15:0] NUM_TAPS_C = CHAIN_STAGES * 4;

    // =========================================================================
    // 1. AXI 쓰기 채널
    //    AXI4-Lite 는 버스트가 없으므로 주소와 데이터가 모두 왔을 때 한 번에 받는다.
    //    AWREADY 가 AWVALID 에 의존하는 것은 AXI 규격상 허용된다
    //    (금지된 것은 그 반대, 즉 VALID 가 READY 에 의존하는 것이다).
    // =========================================================================
    reg [31:0] ctrl_reg;
    reg        ctrl_upd_tgl;      // CTRL 을 쓸 때마다 토글. CDC 용.
    reg        bvalid_r;

    wire wr_go = s_axi_awvalid & s_axi_wvalid & ~bvalid_r;

    assign s_axi_awready = wr_go;
    assign s_axi_wready  = wr_go;
    assign s_axi_bvalid  = bvalid_r;
    assign s_axi_bresp   = 2'b00;   // 항상 OKAY. 없는 주소에 써도 조용히 무시한다.

    wire [5:0] wr_word = s_axi_awaddr[7:2];

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            ctrl_reg     <= 32'd0;
            ctrl_upd_tgl <= 1'b0;
            bvalid_r     <= 1'b0;
        end else begin
            if (wr_go) begin
                if (wr_word == A_CTRL) begin
                    if (s_axi_wstrb[0]) ctrl_reg[ 7: 0] <= s_axi_wdata[ 7: 0];
                    if (s_axi_wstrb[1]) ctrl_reg[15: 8] <= s_axi_wdata[15: 8];
                    if (s_axi_wstrb[2]) ctrl_reg[23:16] <= s_axi_wdata[23:16];
                    if (s_axi_wstrb[3]) ctrl_reg[31:24] <= s_axi_wdata[31:24];
                    ctrl_upd_tgl <= ~ctrl_upd_tgl;
                end
                bvalid_r <= 1'b1;
            end else if (bvalid_r && s_axi_bready) begin
                bvalid_r <= 1'b0;
            end
        end
    end

    // =========================================================================
    // 2. 상태 입력 동기화 (TDC -> AXI 도메인)
    //    STATUS 의 단일 비트들은 서로 정합이 필요 없어 비트별 2FF 로 충분하다.
    //    DNA 는 dna_valid 가 뜬 뒤로 변하지 않는 상수라 2FF 로 안전하다.
    // =========================================================================
    (* ASYNC_REG = "TRUE" *) reg [4:0]  st_d1, st_d2;
    (* ASYNC_REG = "TRUE" *) reg [30:0] dna_d1, dna_d2;

    wire [4:0] st_raw = { stat_phase_busy, stat_done, stat_busy,
                          stat_dna_valid, stat_mmcm_locked };

    always @(posedge s_axi_aclk) begin
        st_d1  <= st_raw;     st_d2  <= st_d1;
        dna_d1 <= stat_dna;   dna_d2 <= dna_d1;
    end

    wire [31:0] status_word = { 26'd0,
                                st_d2[4],    // [5] PHASE_BUSY
                                st_d2[3],    // [4] DONE
                                st_d2[2],    // [3] BUSY
                                st_d2[1],    // [2] DNA_VALID
                                1'b0,        // [1] 예약 (2단계에서 HISTO_CLR_BUSY)
                                st_d2[0] };  // [0] MMCM_LOCKED

    // =========================================================================
    // 3. AXI 읽기 채널
    // =========================================================================
    reg [31:0] rdata_r;
    reg        rvalid_r;

    wire rd_go = s_axi_arvalid & ~rvalid_r;

    assign s_axi_arready = rd_go;
    assign s_axi_rvalid  = rvalid_r;
    assign s_axi_rdata   = rdata_r;
    assign s_axi_rresp   = 2'b00;   // 항상 OKAY

    wire [5:0] rd_word = s_axi_araddr[7:2];

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            rdata_r  <= 32'd0;
            rvalid_r <= 1'b0;
        end else begin
            if (rd_go) begin
                case (rd_word)
                    A_ID:     rdata_r <= ID_MAGIC;
                    A_BUILD:  rdata_r <= { NUM_TAPS_C, CHAIN_STAGES[7:0], REGMAP_VER };
                    A_CTRL:   rdata_r <= ctrl_reg;
                    A_STATUS: rdata_r <= status_word;
                    A_DNA:    rdata_r <= { st_d2[1], dna_d2 };   // [31] = dna_valid
                    default:  rdata_r <= 32'hDEAD_0000;          // 없는 주소를 눈에 띄게
                endcase
                rvalid_r <= 1'b1;
            end else if (rvalid_r && s_axi_rready) begin
                rvalid_r <= 1'b0;
            end
        end
    end

    // =========================================================================
    // 4. 제어 출력 동기화 (AXI -> TDC 도메인)
    //    ★ 토글 핸드셰이크. 파일 상단 [CDC] 주석 참조.
    //    토글이 2단 동기화되는 동안 ctrl_reg 는 이미 안정돼 있으므로,
    //    토글이 바뀐 시점에 통째로 래치하면 비트 간 스큐가 생기지 않는다.
    // =========================================================================
    (* ASYNC_REG = "TRUE" *) reg tgl_d1, tgl_d2;
    reg tgl_d3;

    always @(posedge tdc_clk or negedge tdc_rst_n) begin
        if (!tdc_rst_n) begin
            tgl_d1 <= 1'b0; tgl_d2 <= 1'b0; tgl_d3 <= 1'b0;
            ctrl_hit_src   <= 2'b00;
            ctrl_start     <= 1'b0;
            ctrl_stop      <= 1'b0;
            ctrl_histo_clr <= 1'b0;
            ctrl_tdc_rst   <= 1'b0;
            ctrl_cap_fmt   <= 1'b0;
        end else begin
            tgl_d1 <= ctrl_upd_tgl;   // 동기화 1단 (비동기 입력)
            tgl_d2 <= tgl_d1;         // 동기화 2단 (메타스테이빌리티 해소)
            tgl_d3 <= tgl_d2;         // 에지 검출용

            if (tgl_d2 ^ tgl_d3) begin
                ctrl_hit_src   <= ctrl_reg[1:0];
                ctrl_start     <= ctrl_reg[2];
                ctrl_stop      <= ctrl_reg[3];
                ctrl_histo_clr <= ctrl_reg[4];
                ctrl_tdc_rst   <= ctrl_reg[5];
                ctrl_cap_fmt   <= ctrl_reg[6];
            end
        end
    end

endmodule
