// Generated by Claude Code, 2026-08-12
// -----------------------------------------------------------------------------
// tdc_fmcw_core_mix — CARRY4 의 CO(캐리) 탭에 O(XOR) 탭을 한 자리만 섞은 검증용 코어
//
// tdc_fmcw_core.v (O 탭) / tdc_fmcw_core_co.v (CO 탭) 는 그대로 두고 만든 세 번째 사본.
// tdc_fmcw_core_co.v 대비 바뀐 곳은 아래 ★ 주석 2곳뿐이다.
//
// =============================================================================
// [왜 만들었나 — 2026-08-12]
//
//   CO 빌드 40 °C 실측(python/co_temp/co_histo_40*.csv, 3캡처)에서 CARRY4 하나
//   안의 네 구간 폭이 심하게 불균등하다:
//
//     CO[1] ──── 31.08 ──── CO[3] ─ 4.86 ─ CO[2] ─── 18.88 ─── CO[0] ── 16.28 ──> 다음 CO[1]
//              (%4==1)            (%4==2)          (%4==3)          (%4==0)
//
//     이상적 균등값 = 71.10/4 = 17.78 ps.   현재 네 값의 표준편차 10.76 ps.
//     31.08 은 이상값의 1.75배, 4.86 은 0.27배다.
//
//   4.86 ps 구간을 직접 넓힐 수는 없다. 그 구간은 CO[3] 과 CO[2] 라는 두 끝점
//   사이이고, 한 끝점을 옮기면 인접 구간이 같은 양만큼 줄어드는 제로섬이다.
//   대신 **31.08 ps 짜리 넓은 구간 안에 새 절단점을 넣는 것**이 이득이 크다.
//
// [O 를 쓰면 새 절단점이 생기는 이유 — Xilinx UG474 CARRY4 정의]
//
//     CO[0] = S[0] ? CI    : DI[0]        O[0] = S[0] XOR CI
//     CO[1] = S[1] ? CO[0] : DI[1]        O[1] = S[1] XOR CO[0]
//     CO[2] = S[2] ? CO[1] : DI[2]        O[2] = S[2] XOR CO[1]
//     CO[3] = S[3] ? CO[2] : DI[3]        O[3] = S[3] XOR CO[2]
//
//   즉 O[j] 는 CO[j] 가 아니라 **CO[j-1] 을 XOR 게이트 하나만큼 늦춘 복사본**이다.
//   S=4'b1111 이므로 O[j] = ~(CO[j-1]) 이고, 극성도 반대다.
//   따라서 O[2] 는 CO[1] 도착 시각 + d2 에 뜬다 → 31.08 ps 구간을 둘로 쪼갠다.
//
//   d2(XOR 지연의 절대값)는 아직 모른다. O 빌드(python/o_rebuild)와 CO 빌드는
//   서로 다른 탭만 재서 두 시간축을 이어붙일 기준이 없기 때문이다.
//   **이 빌드가 그 절대 정렬을 처음으로 측정한다.**  O 빌드 구간값을 역산해 얻은
//   상대 지연은 d0-d2 = +2.2, d1-d2 = +9.7, d3-d2 = +18.7 ps (미검증 추정).
//
// [예상 결과]
//   MIX_MODE=0 :  d2 / (35.94-d2) / 18.88 / 16.28    d2=17.9 이면 표준편차 1.1 ps
//   MIX_MODE=1 :  d2 / (31.08-d2) / 23.74 / 16.28    d2=15.5 이면 표준편차 4.0 ps
//   현재 CO 빌드                                                    표준편차 10.8 ps
//   d2 가 아주 작으면 두 모드 모두 개선이 없다. 다만 지금보다 나빠지지는 않는다.
//
// [★ MIX_MODE 를 둔 이유 — 배치 충돌]
//   7-series 슬라이스에서 O[j] 와 CO[j] 는 같은 위치 j 의 FF(AFF/BFF/CFF/DFF)로
//   직결된다. 한 위치에서 두 신호를 뽑으면 하나는 슬라이스 밖 일반 배선을 타야 하고,
//   제어 안 된 지연이 붙거나 배치가 실패할 수 있다.
//
//     MIX_MODE=0 : CO[0], CO[1], CO[2], O[2]   <- 위치 2 를 둘이 원함. 성능은 최선.
//                  O[2] 가 u_ff_3(DFF) 로 가야 하므로 배치 위험 있음.
//     MIX_MODE=1 : CO[0], CO[1], O[2], CO[3]   <- 위치당 하나씩. 충돌 없음. 안전.
//                  CO[2] 를 버리므로 4.86+18.88 이 23.74 로 합쳐진다.
//
//   0 번을 먼저 시도하고, 배치/타이밍 경고가 나면 1 번으로 내린다.
//
// [선행연구 — 이 방향은 이미 있다]
//   Carra et al., IEEE TNS 2018        : C/S 조합 16가지 전수 비교. CCCC 가 최적이라 결론
//   Chen et al., Sensors 25, 2923 2025 : heterogeneous C/S 혼합 (자리마다 다른 소스)
//   둘 다 **온도 실험이 없고**, thermometer 실측으로 도착 순서를 확인한 뒤 그 근거로
//   조합을 고르지도 않았다. 우리 차별점은 결과가 아니라 근거를 재서 고른다는 것이다.
//
// [빌드 방법]
//   tdc_test_top.v 의  `tdc_fmcw_core u_tdc (`  ->  `tdc_fmcw_core_mix u_tdc (`
//   포트는 원본과 완전히 동일하다.
//   내부 인스턴스 이름(CARRY_CHAIN / STAGE_0 / STAGE_N / u_carry4 / u_ff_0..3 /
//   taps_sampled_d1)도 동일하게 유지했으므로 tdc.xdc 의 LOC/BEL 제약이 그대로 걸린다.
//   배치는 SLICE_X42Y0~Y79 (2026-08-12 배치 실험 후 원복된 원래 위치).
//
// [측정 시 주의]
//   danger_zone 문턱 (40, 220) 은 O 탭 분포로 튜닝된 값이다. 이 빌드는 탭 폭 분포가
//   또 달라지므로 첫 측정 후 재튜닝이 필요할 수 있다. 지금은 CO 빌드와 같은 조건으로
//   비교하기 위해 그대로 둔다.
// =============================================================================
`timescale 1ns / 1ps

module tdc_fmcw_core_mix #(
    parameter CARRY4_STAGES = 80, // 80 * 4 = 320 Taps (5ns 커버)
    // 0 = CO[0],CO[1],CO[2],O[2]  (성능 최선, 위치 2 충돌 위험)
    // 1 = CO[0],CO[1],O[2],CO[3]  (위치당 하나씩, 안전)
    parameter MIX_MODE = 0
)(
    input wire clk,
    input wire rst_n,
    input wire hit,

    output reg [31:0]  ts_coarse,
    output reg [8:0]   ts_fine_idx,
    output reg         ts_valid
);

localparam NUM_TAPS = CARRY4_STAGES * 4; // 320

(* keep = "true" *) wire [NUM_TAPS-1:0] carry_co;
(* keep = "true", dont_touch = "true" *) wire [NUM_TAPS-1:0] carry_o;
(* ASYNC_REG = "TRUE", DONT_TOUCH = "TRUE" *) wire [NUM_TAPS-1:0] taps_sampled;

// 자리별 탭 소스 (CO 또는 O 중 하나가 상수 선택으로 연결된다. 3. CARRY4 CHAIN 참조)
wire [NUM_TAPS-1:0] tap_src;

// -------------------------------------------------------------------------
// 1. Dual Phase Coarse Counters
// -------------------------------------------------------------------------
reg [31:0] coarse_0;
reg [31:0] coarse_180;
reg [31:0] coarse_180_sync;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_0 <= 0;
    else coarse_0 <= coarse_0 + 1'b1;
end

always @(negedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180 <= 0;
    else coarse_180 <= coarse_0;
end

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180_sync <= 0;
    else coarse_180_sync <= coarse_180;
end

// -------------------------------------------------------------------------
// 2. 파이프라인 레지스터
// -------------------------------------------------------------------------
(* DONT_TOUCH = "TRUE" *) reg [NUM_TAPS-1:0] taps_sampled_d1;
reg taps_sampled_0_history;

reg snapshot_valid_stg2, snapshot_valid_stg3, snapshot_valid_stg4;

// Vivado가 Shift Register로 압축하는 것을 막아 라우터가 배선 지연을 추가할 수 있게 돕습니다.
(* srl_style = "register" *) reg [31:0] captured_c0_stg2, captured_c180_stg2;
(* srl_style = "register" *) reg [31:0] captured_c0_stg3, captured_c180_stg3_plus1;
(* srl_style = "register" *) reg [31:0] captured_c0_stg4, captured_c180_stg4_plus1;

reg [8:0]  fine_idx_stg4;
reg        danger_zone_stg4;

reg [3:0] stg1_halfA [0:19];
reg [3:0] stg1_halfB [0:19];
reg [7:0] stg3_group0, stg3_group1, stg3_group2, stg3_group3;

integer i;

function [3:0] popcount8;
    input [7:0] din;
    begin
        popcount8 = din[0] + din[1] + din[2] + din[3] +
                    din[4] + din[5] + din[6] + din[7];
    end
endfunction

// -------------------------------------------------------------------------
// ★ 변경 1/2 (2026-08-12) — 탭 극성 반전을 "자리별"로 바꿈
// -------------------------------------------------------------------------
//   tdc_fmcw_core_co.v 는 네 자리가 모두 CO 라  taps_eff = ~taps_sampled_d1  한 줄이면
//   됐다. 이 빌드는 한 자리만 O 탭이라 자리마다 극성이 다르다:
//
//     CO 탭 : taps_sampled = carry        -> 반전 필요 (~)
//     O  탭 : taps_sampled = ~carry       -> 이미 원본(O 빌드) 극성. 반전하면 안 됨
//
//   O 탭이 들어가는 자리는 MIX_MODE 에 따라 다르다 (아래 O_POS).
//   반전은 반드시 샘플링 FF 뒤에서 해야 한다. .D(~...) 로 넣으면 LUT1 이 끼어들어
//   탭 경로가 길어지고 이 실험의 전제가 깨진다. 여기서의 반전은 뒤따르는 popcount
//   LUT 에 흡수되어 추가 지연이 없다. taps_sampled_d1 자체는 반전하지 않는다 —
//   tdc.xdc 가 taps_sampled_d1_reg 를 SLICE_X43Y* 에 고정해 두었기 때문이다.
//   ※ generate 로 자리마다 assign 을 만들면 이름 있는 생성 스코프가 하나 더 생겨
//     계층 경로가 바뀐다. tdc.xdc 에 정확 경로 지정([get_cells {u_tdc/CARRY_CHAIN[0].u_ff_2}])
//     이 있으므로 스코프를 늘리면 안 된다. 그래서 상수 마스크로 처리한다.
//
//     O_MASK4 의 비트 j = "자리 j 가 O 탭인가".  이걸 80번 반복해 320비트를 만든다.
localparam [3:0] O_MASK4 = (MIX_MODE == 0) ? 4'b1000 : 4'b0100;  // MIX0: 자리3 / MIX1: 자리2
wire [NUM_TAPS-1:0] o_mask = {CARRY4_STAGES{O_MASK4}};

//   mask=1 (O 탭)  -> ~mask=0 -> XOR 0 = 그대로
//   mask=0 (CO 탭) -> ~mask=1 -> XOR 1 = 반전
wire [NUM_TAPS-1:0] taps_eff = taps_sampled_d1 ^ ~o_mask;

// -------------------------------------------------------------------------
// 3. CARRY4 CHAIN
// -------------------------------------------------------------------------
(* keep = "true" *) wire rst_high = ~rst_n;
genvar k;
generate
    for (k = 0; k < CARRY4_STAGES; k = k + 1) begin : CARRY_CHAIN
        if (k == 0) begin : STAGE_0
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(1'b0), .CYINIT(hit), .DI(4'b0000), .S(4'b1111));
        end else begin : STAGE_N
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(carry_co[(k*4)-1]), .CYINIT(1'b0), .DI(4'b0000), .S(4'b1111));
        end

        // ★ 변경 2/2 (2026-08-12) — 네 탭 중 한 자리만 O[2] 로 교체.
        //    O[2] = ~CO[1] + XOR지연 이므로 CO[1] 직후에 뜬다 → 31.08 ps 구간을 쪼갠다.
        //    나머지 세 자리는 tdc_fmcw_core_co.v 와 동일한 CO 탭이다.
        //    FF 이름/BEL 은 원본과 동일하게 유지해야 tdc.xdc 제약이 그대로 걸린다.
        //    MIX_MODE 는 파라미터라 아래 삼항연산자는 합성 시 상수로 접혀 단순 배선만
        //    남는다(LUT 생기지 않음). generate-if 를 쓰지 않는 이유는 위 극성 주석 참조 —
        //    생성 스코프가 늘면 tdc.xdc 의 정확 경로 제약이 깨진다.
        assign tap_src[(k*4)+0] = carry_co[(k*4)+0];                                    // CO[0]
        assign tap_src[(k*4)+1] = carry_co[(k*4)+1];                                    // CO[1]
        assign tap_src[(k*4)+2] = (MIX_MODE == 0) ? carry_co[(k*4)+2] : carry_o [(k*4)+2];
        assign tap_src[(k*4)+3] = (MIX_MODE == 0) ? carry_o [(k*4)+2] : carry_co[(k*4)+3];

        (* DONT_TOUCH = "TRUE" *) FDC u_ff_0 ( .Q(taps_sampled[(k*4)+0]), .C(clk), .CLR(rst_high), .D(tap_src[(k*4)+0]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_1 ( .Q(taps_sampled[(k*4)+1]), .C(clk), .CLR(rst_high), .D(tap_src[(k*4)+1]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_2 ( .Q(taps_sampled[(k*4)+2]), .C(clk), .CLR(rst_high), .D(tap_src[(k*4)+2]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_3 ( .Q(taps_sampled[(k*4)+3]), .C(clk), .CLR(rst_high), .D(tap_src[(k*4)+3]) );
    end
endgenerate

// -------------------------------------------------------------------------
// 4. MAIN LOGIC 파이프라인  (tdc_fmcw_core_co.v 와 완전히 동일)
// -------------------------------------------------------------------------
localparam DEAD_TIME_CYCLES = 2;
reg [3:0] dead_time_cnt;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        taps_sampled_d1 <= 0; taps_sampled_0_history <= 0; dead_time_cnt <= 0;
        snapshot_valid_stg2 <= 0; snapshot_valid_stg3 <= 0; snapshot_valid_stg4 <= 0;
        captured_c0_stg2 <= 0; captured_c180_stg2 <= 0;
        captured_c0_stg3 <= 0; captured_c180_stg3_plus1 <= 0;
        captured_c0_stg4 <= 0; captured_c180_stg4_plus1 <= 0;
        fine_idx_stg4 <= 0; danger_zone_stg4 <= 0;
        ts_coarse <= 0; ts_valid <= 0; ts_fine_idx <= 0;
        stg3_group0 <= 0; stg3_group1 <= 0; stg3_group2 <= 0; stg3_group3 <= 0;
        for (i = 0; i < 20; i = i + 1) begin
            stg1_halfA[i] <= 0; stg1_halfB[i] <= 0;
        end
    end
    else begin
        // [Stage 1]
        taps_sampled_d1 <= taps_sampled;
        // taps_eff[0] 은 자리 0 = CO[0] 탭이므로 반전된 값이다.
        // stage 0 은 CYINIT=hit, S=1 이므로 CO[0]=hit, 즉 taps_eff[0]=~hit 로
        // 원본(O 빌드의 O[0]=~hit)과 동일 — 하강 에지 검출 의미가 보존된다.
        taps_sampled_0_history <= taps_eff[0];

        // [Stage 2]
        if (dead_time_cnt > 0) begin
            dead_time_cnt <= dead_time_cnt - 1'b1;
            snapshot_valid_stg2 <= 1'b0;
        end
        else if (taps_eff[0] && !taps_sampled_0_history) begin
            dead_time_cnt <= DEAD_TIME_CYCLES;

            captured_c0_stg2   <= coarse_0;
            captured_c180_stg2 <= coarse_180_sync;

            for (i = 0; i < 20; i = i + 1) begin
                stg1_halfA[i] <= popcount8(taps_eff[i*16 +: 8]);
                stg1_halfB[i] <= popcount8(taps_eff[i*16+8 +: 8]);
            end
            snapshot_valid_stg2 <= 1'b1;
        end else begin
            snapshot_valid_stg2 <= 1'b0;
        end

        // [Stage 3]
        if (snapshot_valid_stg2) begin
            stg3_group0 <= stg1_halfA[0]+stg1_halfB[0] + stg1_halfA[1]+stg1_halfB[1] + stg1_halfA[2]+stg1_halfB[2] + stg1_halfA[3]+stg1_halfB[3] + stg1_halfA[4]+stg1_halfB[4];
            stg3_group1 <= stg1_halfA[5]+stg1_halfB[5] + stg1_halfA[6]+stg1_halfB[6] + stg1_halfA[7]+stg1_halfB[7] + stg1_halfA[8]+stg1_halfB[8] + stg1_halfA[9]+stg1_halfB[9];
            stg3_group2 <= stg1_halfA[10]+stg1_halfB[10] + stg1_halfA[11]+stg1_halfB[11] + stg1_halfA[12]+stg1_halfB[12] + stg1_halfA[13]+stg1_halfB[13] + stg1_halfA[14]+stg1_halfB[14];
            stg3_group3 <= stg1_halfA[15]+stg1_halfB[15] + stg1_halfA[16]+stg1_halfB[16] + stg1_halfA[17]+stg1_halfB[17] + stg1_halfA[18]+stg1_halfB[18] + stg1_halfA[19]+stg1_halfB[19];

            captured_c0_stg3 <= captured_c0_stg2;
            captured_c180_stg3_plus1 <= captured_c180_stg2 + 1'b1;

            snapshot_valid_stg3 <= 1'b1;
        end else begin
            snapshot_valid_stg3 <= 1'b0;
        end

        // [Stage 4]
        if (snapshot_valid_stg3) begin
            begin : CALC_FINE
                reg [8:0] sum_fine;
                sum_fine = stg3_group0 + stg3_group1 + stg3_group2 + stg3_group3;
                fine_idx_stg4 <= sum_fine;

                // [2026-08-12 주의] 이 (40, 220) 문턱은 O 탭 분포로 튜닝된 값이다.
                // 혼합 탭은 폭 분포가 또 달라지므로 첫 측정 후 재튜닝이 필요할 수 있다.
                // CO 빌드와 같은 조건으로 비교하기 위해 지금은 그대로 둔다.
                danger_zone_stg4 <= (sum_fine < 9'd40 || sum_fine > 9'd220);
            end

            captured_c0_stg4 <= captured_c0_stg3;
            captured_c180_stg4_plus1 <= captured_c180_stg3_plus1;
            snapshot_valid_stg4 <= 1'b1;
        end else begin
            snapshot_valid_stg4 <= 1'b0;
        end

        // [Stage 5]
        if (snapshot_valid_stg4) begin
            ts_fine_idx <= fine_idx_stg4;

            if (danger_zone_stg4) begin
                ts_coarse <= captured_c180_stg4_plus1;
            end else begin
                ts_coarse <= captured_c0_stg4;
            end

            ts_valid <= 1'b1;
        end else begin
            ts_valid <= 1'b0;
        end
    end
end
endmodule
