`timescale 1ns / 1ps
// =============================================================================
// tdc_zedboard_top.v  —  ZedBoard (XC7Z020-CLG484) 용 최상위 래퍼
// Generated by Claude Code, 2026-09-02
//
//  [왜 이 파일이 따로 있나]
//  Zybo(XC7Z010) 용 tdc_test_top.v 를 건드리지 않고 ZedBoard 를 지원하기 위해서다.
//  Zybo 2대는 교정 캠페인에 계속 쓰이는 중이라, 그 파일이 바뀌면 이미 잡아 둔
//  측정 데이터와의 대응이 흐트러진다.
//
//  코어 로직(MMCM, 링오실레이터, XADC, 히스토그램, ILA, 파이프라인)은 전부
//  tdc_test_top 안에 그대로 있고, 이 파일은 ZedBoard 고유의 입출력만 처리한다.
//  600줄을 복제하지 않으므로 앞으로 코어를 고칠 때 두 곳을 동기화할 필요가 없다.
//
//  [Zybo 와 다른 점]
//    1) 히트 입력 : PMOD 단일선(V8) -> FMC LA27_P/N 차동쌍(E21/D21)
//                   TLV3605 비교기의 LVDS 출력을 IBUFDS 로 받는다.
//    2) PL 클럭   : 125 MHz(K17) -> 100 MHz(Y9, Bank 13)
//    3) 디바이스  : XC7Z010-CLG400 -> XC7Z020-CLG484
//
//  [RTL 밖에서 반드시 해야 할 것 — 안 하면 동작하지 않는다]
//    (a) clk_wiz_0 IP 를 ZedBoard 프로젝트에서 재생성할 것.
//        입력 100 MHz, VCO 1000 MHz(M=10, D=1), CLKOUT0/1 = 200 MHz(÷5).
//        VCO 를 1000 MHz 로 유지해야 phase_shifter.v 의 PHASE_STEP = 1000/56
//        = 17.857 ps 가 그대로 성립한다. 이 값이 Mode 0 의 참 시간축이다.
//    (b) ZedBoard 점퍼 J18 을 2.5V 로 옮길 것 (기본값 1.8V).
//        FMC 뱅크 34/35 의 VCCO 가 2.5V 여야 LVDS_25 수신과 내부 100옴 종단
//        (DIFF_TERM)이 동작한다. 1.8V 로 두면 LVDS 입력이 규격을 벗어난다.
//    (c) RTL/tdc_zedboard.xdc 를 쓸 것. Zybo 용 tdc.xdc 는 넣지 말 것(핀 충돌).
//        ★ 2026-09-03 : 체인이 96단(384탭)으로 늘어 LOC 제약이 2400줄이 됐다.
//        손으로 쓰는 것이 아니라 python/gen_chain_xdc.py --stages 96 으로 생성한다.
//        캐리체인 LOC 좌표는 2026-09-03 에 link_design -part xc7z020clg484-1 로
//        조회해 확인했다 — X42=SLICEM, X43=SLICEL, 둘 다 Y0~Y149 연속이므로
//        96단(Y0~Y95)은 여유 있게 들어간다.
// =============================================================================

module tdc_zedboard_top #(
    // tdc_test_top 과 동일한 의미.
    //   0 : Hit = 내부 Test Sync | Clock = Shifted 200MHz  (MMCM 위상 스윕 교정)
    //   1 : Hit = Ring Osc       | Clock = Fixed 200MHz    (코드밀도 히스토그램)
    //   2 : Hit = FMC LVDS       | Clock = Fixed 200MHz    (TLV3605 실측)
    parameter integer OPERATION_MODE = 2
)(
    input  wire       clk_100,      // Y9,  Bank 13, LVCMOS33, 온보드 100 MHz 발진기
    input  wire       rst_n,        // 버튼 (실제로는 MMCM 의 active-high reset 으로 들어간다)
    input  wire       btn_shift,    // 버튼, Mode 0 위상 스윕 시작
    input  wire       hit_lvds_p,   // E21, FMC LA27_P  <- TLV3605 LVDS+
    input  wire       hit_lvds_n,   // D21, FMC LA27_N  <- TLV3605 LVDS-
    output wire [3:0] led
);

    // -------------------------------------------------------------------------
    // LVDS 히트 수신
    //
    //  DIFF_TERM = "TRUE" 로 FPGA 내부 100옴 차동 종단을 켠다. TLV3605 출력에서
    //  FMC 커넥터까지 오는 차동 선로를 종단하지 않으면 반사로 에지가 무너지고,
    //  그건 곧 캐리체인 진입 slew 저하 -> 진입 트랜지언트 악화로 이어진다.
    //  (tdc_test_top.v §6 의 led[2] 사례 참조 : hit 네트에 부하가 붙자
    //   CARRY4 초입 3단이 정상값의 1.16~1.89배로 늘어났다.)
    //
    //  IOSTANDARD 는 XDC 에서 지정한다(LVDS_25). 여기서 파라미터로 박으면
    //  뱅크 전압을 바꿀 때 두 곳을 고쳐야 해서 XDC 한 곳으로 모은다.
    //
    //  ★ IBUFDS 출력은 어떤 로직도 거치지 않고 곧장 코어의 hit 입력으로 간다.
    //    레지스터를 끼우거나 다른 곳에 분기하면 안 된다 — hit 네트는 CARRY4 의
    //    CYINIT 하나만 구동해야 한다.
    // -------------------------------------------------------------------------
    wire hit_from_fmc;

    IBUFDS #(
        .DIFF_TERM    ("TRUE"),      // 내부 100옴 차동 종단 (VCCO 2.5V 필요)
        .IBUF_LOW_PWR ("FALSE")      // 성능 우선 — 저전력 모드는 지연/지터가 나쁘다
    ) u_hit_ibufds (
        .I  (hit_lvds_p),
        .IB (hit_lvds_n),
        .O  (hit_from_fmc)
    );

    // -------------------------------------------------------------------------
    // TDC 코어 (Zybo 와 완전히 동일한 파일을 그대로 쓴다)
    //
    //  clk_125 포트에 100 MHz 를 넣는다. 포트 이름이 실제 주파수와 다르지만,
    //  이 포트는 "PL 클럭 입력"이라는 의미이고 실제 주파수는 clk_wiz_0 IP 설정이
    //  정한다. 이름을 바꾸려면 Zybo 용 파일을 건드려야 하므로 그대로 둔다.
    //
    //  ext_hit_in 포트에 IBUFDS 출력을 연결한다. tdc_test_top 안에서 Mode 2 는
    //  ext_hit_in 을 그대로 tdc_hit_in 으로 넘기므로, LVDS 신호가 CYINIT 까지
    //  아무 로직 없이 도달한다.
    // -------------------------------------------------------------------------
    // ★ [2026-09-03] CARRY4_STAGES = 96 (384탭) 로 넘긴다.
    //   ZedBoard 는 320탭이 5 ns 안에 전부 들어가 버려서(2026-09-03 Mode 2 측정에서
    //   히스토그램 320칸이 모두 채워짐) 유효탭 상한을 히스토그램에서 읽을 수가 없었다.
    //   384탭이면 세 보드 모두 뒤쪽에 빈 칸이 생겨 상한이 눈에 보인다.
    //   (448 도 빌드해 봤으나 타이밍 여유가 5 ps 뿐이었다 —
    //    자세한 근거는 tdc_fmcw_core_co.v 상단 [왜 384 인가] 참조)
    //   자세한 근거는 Markdown/2026-09-03_zedboard_tap_range_plan.md §7, §9 참조.
    //   ※ XDC 도 같이 96단이어야 한다 : python/gen_chain_xdc.py --stages 96
    tdc_test_top #(
        .OPERATION_MODE (OPERATION_MODE),
        .CARRY4_STAGES  (96)
    ) u_core (
        .clk_125    (clk_100),        // ★ 실제로는 100 MHz. clk_wiz_0 를 100 MHz 입력으로 재생성할 것
        .rst_n      (rst_n),
        .btn_shift  (btn_shift),
        .ext_hit_in (hit_from_fmc),   // ★ FMC LA27 차동 -> 단일선
        .led        (led)
    );

endmodule
