// Generated by Claude Code, 2026-08-04
// -----------------------------------------------------------------------------
// tdc_fmcw_core_co — CARRY4 의 CO(캐리) 출력을 탭으로 사용하는 검증용 코어
//
// 원본 tdc_fmcw_core.v 는 그대로 두고, 탭 소스만 O(XOR) -> CO(캐리)로 바꾼 사본이다.
//
// [왜 만들었나 — 2026-08-04]
//   Vivado 타이밍 모델(get_timing_arcs, fast_min 코너, speed file -1)에서 읽은 값:
//       CI -> CO[3] = 40 ps   (MUXCY 4단 전부 통과)
//       CI -> O[0]  = 53 ps   (XOR 출력 1개)
//       CI -> O[1]  = 89 ps , CI -> O[2] = 66 ps , CI -> O[3] = 91 ps
//   즉 (1) 캐리가 4단을 다 지나가는 것보다 XOR 출력 하나가 더 느리고,
//      (2) O 도착 순서가 인덱스 순서가 아니다 (0, 2, 1, 3).
//   popcount 는 "1 이 된 탭의 개수"를 세므로 히스토그램 bin 번호는 물리 탭 번호가
//   아니라 "도착 순서 등수"가 된다. O 를 쓰는 한 이 permutation 을 알 수 없고,
//   동작 조건에 따라 순서가 바뀌면 bin<->탭 대응 자체가 흔들린다.
//   CO 는 CO[0] < CO[1] < CO[2] < CO[3] 이 직렬 캐리라 구조적으로 보장되므로
//   도착 순서 = 탭 번호가 되고 permutation 문제가 사라진다.
//
// [원본 대비 변경점은 아래 ★ 주석 3곳뿐이다]
//
// ============================================================================
// [2026-08-05 실측 결과 — 위 "단조성 보장" 근거는 틀렸다]
//   thermometer code 를 직접 떠서(임시 디버그 포트, 측정 후 제거) 확인한 결과:
//
//     실측 도착 순서 :  CO[1] -> CO[3] -> CO[2] -> CO[0]
//
//   즉 CO 도 단조가 아니다. 다만 무작위 bubble 이 아니라 **고정된 순열**이다 —
//   가능한 14 패턴 중 3 개만 나타나고, 0->1 전이가 %4==1 과 %4==3 에만 생긴다.
//   CO[3] 이 CO[0] 보다 먼저 도착하는 것은 직렬 리플에서 불가능하므로,
//   **7-series CARRY4 는 4단 리플이 아니라 캐리 look-ahead 구조**임이 확인됐다.
//
//   따라서 이 파일을 만든 근거 중 (2) "permutation 이 사라진다" 는 성립하지 않는다.
//   남는 근거는 (1) 뿐이다 — CO 경로가 XOR 경로보다 짧아 온도 변동 요소가 하나 준다.
//   그럼에도 실측 개선은 확실하다: INL p-p 155.8 -> 96.8 ps (-37.8 %, 빌드 통제 완료),
//   40->80 C 무보정 드리프트 69.7 -> 8.3 ps.  자세한 내용은 Markdown/2026-08-04_report.md
//   §2-7 (빌드 통제) / §2-8 (thermometer) / §3-5,§3-6 (온도) 참조.
// ============================================================================
//
// [빌드 방법]
//   tdc_test_top.v:218 의  `tdc_fmcw_core u_tdc (`  ->  `tdc_fmcw_core_co u_tdc (`
//   포트는 원본과 완전히 동일하므로 그 한 단어만 바꾸면 된다.
//   내부 인스턴스 이름(CARRY_CHAIN / STAGE_0 / STAGE_N / u_carry4 / u_ff_0..3 /
//   taps_sampled_d1)도 원본과 동일하게 유지했으므로 tdc.xdc 의 LOC/BEL 제약
//   2000여 줄이 수정 없이 그대로 적용된다.
// -----------------------------------------------------------------------------
`timescale 1ns / 1ps

module tdc_fmcw_core_co #(
    parameter CARRY4_STAGES = 80 // 80 * 4 = 320 Taps (5ns 커버)
)(
    input wire clk,
    input wire rst_n,
    input wire hit,

    output reg [31:0]  ts_coarse,
    output reg [8:0]   ts_fine_idx,
    output reg         ts_valid
);

localparam NUM_TAPS = CARRY4_STAGES * 4; // 320

(* keep = "true" *) wire [NUM_TAPS-1:0] carry_co;
(* keep = "true", dont_touch = "true" *) wire [NUM_TAPS-1:0] carry_o;
(* ASYNC_REG = "TRUE", DONT_TOUCH = "TRUE" *) wire [NUM_TAPS-1:0] taps_sampled;

// -------------------------------------------------------------------------
// 1. Dual Phase Coarse Counters
// -------------------------------------------------------------------------
reg [31:0] coarse_0;
reg [31:0] coarse_180;
reg [31:0] coarse_180_sync;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_0 <= 0;
    else coarse_0 <= coarse_0 + 1'b1;
end

always @(negedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180 <= 0;
    else coarse_180 <= coarse_0;
end

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) coarse_180_sync <= 0;
    else coarse_180_sync <= coarse_180;
end

// -------------------------------------------------------------------------
// 2. 파이프라인 레지스터 (★ Hold 에러 방지 속성 추가 ★)
// -------------------------------------------------------------------------
(* DONT_TOUCH = "TRUE" *) reg [NUM_TAPS-1:0] taps_sampled_d1;
reg taps_sampled_0_history;

reg snapshot_valid_stg2, snapshot_valid_stg3, snapshot_valid_stg4;

// Vivado가 Shift Register로 압축하는 것을 막아 라우터가 배선 지연을 추가할 수 있게 돕습니다.
(* srl_style = "register" *) reg [31:0] captured_c0_stg2, captured_c180_stg2;
(* srl_style = "register" *) reg [31:0] captured_c0_stg3, captured_c180_stg3_plus1;
(* srl_style = "register" *) reg [31:0] captured_c0_stg4, captured_c180_stg4_plus1;

reg [8:0]  fine_idx_stg4;
// ★ [2026-09-03] danger_zone_stg4 레지스터 삭제 — 비교를 Stage 5 로 옮겼다.
//
//  [무엇이 문제였나] 384탭 첫 빌드에서 최악 경로가
//      stg3_group_reg[2][2] -> danger_zone_stg4_reg/D   (WNS +0.010 ns, 여유 10 ps)
//    였다. Stage 4 가 한 사이클에 "4항 덧셈 + 비교 2개" 를 전부 하고 있었기 때문이다.
//      sum_fine = stg3_group[0]+[1]+[2]+[3];              <- 덧셈
//      danger_zone_stg4 <= (sum_fine < 40 || sum_fine > 220);  <- 비교까지 연달아
//
//  [무엇을 바꿨나] danger_zone 은 Stage 5 에서만 쓰인다. 그런데 Stage 4 에서 덧셈
//    결과가 나오자마자 비교까지 해서 레지스터에 넣고 있었다. 비교를 Stage 5 로
//    옮기고, 레지스터된 fine_idx_stg4 를 직접 비교한다.
//
//  [왜 안전한가 — 동작이 한 치도 안 바뀐다]
//    기존 : danger_zone_stg4 = f(sum_fine),  sum_fine 은 fine_idx_stg4 에 그대로 들어감
//    변경 : Stage 5 에서 f(fine_idx_stg4) 를 계산
//    fine_idx_stg4 == sum_fine 이므로 같은 값을, 같은 사이클에, 같은 곳에서 쓴다.
//    레이턴시도 그대로다 (파이프라인 단수 불변). 임계경로만 둘로 쪼개진다:
//      Stage 4 : FF -> 덧셈 -> FF
//      Stage 5 : FF -> 비교 + 먹스 -> FF
//
//  임계값은 localparam 으로 이름을 붙여 밖에서 보이게 했다. 값 자체는 안 바꿨다.
//  (이 값들은 옛 O 탭 분포로 튜닝된 것이고 아직 재튜닝된 적이 없다 — 아래 주석 참조.
//   AXI 단계에서 레지스터로 뺄 항목이다.)
localparam [8:0] DANGER_LO = 9'd40;    // 이번 에지 바로 앞 -> coarse_0 가 전이 중
localparam [8:0] DANGER_HI = 9'd220;   // 지난 에지 바로 뒤 -> 역시 에지 근처

// ★ [2026-09-03] 384탭(96단) 확장 — popcount 트리를 단수에서 유도하도록 파라미터화
//
//  [무엇이 문제였나] 트리가 320탭에 맞춰 하드코딩돼 있었다. stg1_half*[0:19] 는
//    "16비트 묶음 20개", stg3_group0~3 은 "묶음 5개씩 4덩어리" 로 320 = 4x5x16 전용이었다.
//
//  [왜 바꾸나] ZedBoard(XC7Z020, DNA 0x3D996854) 는 320탭이 5 ns 안에 전부 들어간다.
//    즉 지연선이 클럭 한 주기보다 짧아, 끝단에 히트가 안 쌓이는 "빈 칸"이 생기지 않는다.
//    빈 칸이 없으면 유효탭 상한을 히스토그램에서 읽어낼 수가 없고, 최악의 경우 320탭을
//    다 지나고도 시간이 남아 sum_fine=320(ROM 주소 범위 밖)이 되는 사각지대가 생긴다.
//    체인을 384탭으로 늘리면 세 보드 전부 뒤쪽에 빈 칸이 생기므로,
//    유효탭 상한이 빌드 한 번으로 히스토그램에 그대로 드러난다.
//
//  [왜 384 인가]
//    (1) 쓸 수 있는 단수는 16의 배수뿐이다 (아래 GPQ 가 정수여야 한다).
//        즉 320(현행) / 384 / 448 셋 중 하나다. 400탭(100단)은 GPQ=6.25 라 불가능.
//    (2) 448 이 구조적 상한이다 : sum_fine / ts_fine_idx 가 [8:0](<=511),
//        히스토그램이 512칸, stg3_group 이 [7:0] 이라 448 까지는 선언 폭을 하나도
//        안 바꿔도 된다. 512 로 가면 sum_fine 이 10비트가 되어 fine 인덱스 /
//        히스토그램 주소 / ROM 주소가 전부 따라 넓어진다.
//    (3) 그런데 448 은 타이밍 여유가 없다 — 2026-09-03 ZedBoard 실측:
//          기본 전략           WNS -0.070 ns (위반 4개)
//          고강도 전략 + phys_opt  WNS +0.005 ns (겨우 통과)
//        위반 경로는 전부 stg1_half* -> stg3_group 트리 가산기였고, 지연의
//        64~67 %가 배선이었다 (로직은 1.6~1.8 ns 뿐). 5 ps 여유는 여유가 아니다.
//    (4) 384 는 트리가 24묶음(448 은 28묶음)이라 배선이 가볍고, 필요한 빈 칸은
//        충분히 확보된다 : 384 x 15.6 ps = 5990 ps 로 ZedBoard 에서도 5 ns 를 넘긴다.
//
//  NGRP = 16비트 묶음 개수      = CARRY4_STAGES/4   (80단 -> 20, 96단 -> 24)
//  GPQ  = stg3 한 덩어리가 맡는 묶음 수 = NGRP/4     (80단 ->  5, 96단 ->  6)
//  ※ CARRY4_STAGES 는 16의 배수여야 GPQ 가 정수가 된다. 80, 96, 112 모두 만족.
//  ※ 기본값은 80 그대로다. Zybo 빌드는 이 파일을 고쳐도 산술이 글자 그대로 동일하다.
localparam integer NGRP = CARRY4_STAGES / 4;
localparam integer GPQ  = NGRP / 4;

reg [3:0] stg1_halfA [0:NGRP-1];
reg [3:0] stg1_halfB [0:NGRP-1];
reg [7:0] stg3_group [0:3];        // 최대 GPQ x 2 x 8 = 112 (112단) -> [7:0] 로 충분

integer i;

function [3:0] popcount8;
    input [7:0] din;
    begin
        popcount8 = din[0] + din[1] + din[2] + din[3] +
                    din[4] + din[5] + din[6] + din[7];
    end
endfunction

// -------------------------------------------------------------------------
// ★ 변경 2/3 (2026-08-04) — 탭 극성 반전을 조합으로 흡수
// -------------------------------------------------------------------------
//   S=4'b1111 이므로  O[j] = 1 XOR carry = ~carry ,  CO[j] = carry  로 서로 반대다.
//   원본(O 탭): hit 하강 -> 탭이 0->1 로 전파 -> popcount = "지나간 탭 수"
//   CO 탭     : 탭이 1->0 으로 전파       -> popcount = "아직 안 지나간 탭 수"
//
//   그래서 taps_eff = ~taps_sampled_d1 을 만들어 이후 로직이 원본과 완전히 같은
//   의미("지나간 탭 수")를 보게 한다.
//
//   ※ .D(~carry_co[...]) 로 탭 경로에 인버터를 넣으면 LUT1 이 끼어들어 CO 로 바꾼
//     이유(XOR 경로 제거)가 사라진다. 반드시 샘플링 FF 뒤에서 반전해야 하며,
//     여기서의 반전은 뒤따르는 popcount LUT 에 흡수되어 추가 지연이 없다.
//     taps_sampled_d1 자체는 반전하지 않는다 — tdc.xdc 가 taps_sampled_d1_reg 를
//     SLICE_X43Y* 에 고정해 두었고 그 사이에 LUT 를 넣으면 배치가 깨진다.
wire [NUM_TAPS-1:0] taps_eff = ~taps_sampled_d1;

// -------------------------------------------------------------------------
// 3. CARRY4 CHAIN
// -------------------------------------------------------------------------
(* keep = "true" *) wire rst_high = ~rst_n;
genvar k;
generate
    for (k = 0; k < CARRY4_STAGES; k = k + 1) begin : CARRY_CHAIN
        if (k == 0) begin : STAGE_0
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(1'b0), .CYINIT(hit), .DI(4'b0000), .S(4'b1111));
        end else begin : STAGE_N
            CARRY4 u_carry4 (.CO(carry_co[(k*4)+3:(k*4)]), .O(carry_o[(k*4)+3:(k*4)]), .CI(carry_co[(k*4)-1]), .CYINIT(1'b0), .DI(4'b0000), .S(4'b1111));
        end
        // ★ 변경 1/3 (2026-08-04) — 탭 소스를 carry_o(XOR) 에서 carry_co(캐리) 로 교체.
        //    이유는 파일 상단 주석 참조. FF 이름/BEL 은 원본과 동일하게 유지해야
        //    tdc.xdc 의 LOC/BEL 제약이 그대로 걸린다.
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_0 ( .Q(taps_sampled[(k*4)+0]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+0]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_1 ( .Q(taps_sampled[(k*4)+1]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+1]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_2 ( .Q(taps_sampled[(k*4)+2]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+2]) );
        (* DONT_TOUCH = "TRUE" *) FDC u_ff_3 ( .Q(taps_sampled[(k*4)+3]), .C(clk), .CLR(rst_high), .D(carry_co[(k*4)+3]) );
    end
endgenerate

// -------------------------------------------------------------------------
// 4. MAIN LOGIC 파이프라인
// -------------------------------------------------------------------------
localparam DEAD_TIME_CYCLES = 2;
reg [3:0] dead_time_cnt;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        taps_sampled_d1 <= 0; taps_sampled_0_history <= 0; dead_time_cnt <= 0;
        snapshot_valid_stg2 <= 0; snapshot_valid_stg3 <= 0; snapshot_valid_stg4 <= 0;
        captured_c0_stg2 <= 0; captured_c180_stg2 <= 0;
        captured_c0_stg3 <= 0; captured_c180_stg3_plus1 <= 0;
        captured_c0_stg4 <= 0; captured_c180_stg4_plus1 <= 0;
        fine_idx_stg4 <= 0;   // ★ 2026-09-03 : danger_zone_stg4 삭제 (Stage 5 로 이동)
        ts_coarse <= 0; ts_valid <= 0; ts_fine_idx <= 0;
        // ★ [2026-09-03] 448탭 확장 — 고정 20 대신 NGRP 로
        for (i = 0; i < 4;    i = i + 1) stg3_group[i] <= 0;
        for (i = 0; i < NGRP; i = i + 1) begin
            stg1_halfA[i] <= 0; stg1_halfB[i] <= 0;
        end
    end
    else begin
        // [Stage 1]
        taps_sampled_d1 <= taps_sampled;
        // ★ 변경 3/3 (2026-08-04) — 아래 taps_sampled_d1[...] 참조를 전부 taps_eff[...] 로 교체.
        //    hit 하강 시 CO 탭은 1->0 이므로 taps_eff[0] 의 상승이 원본 taps_sampled_d1[0]
        //    상승과 같은 사건(= 캐리 프론트가 탭 0 을 통과)을 가리킨다.
        //    stage 0 은 CYINIT=hit, S=1 이므로 CO[0]=hit, 즉 taps_eff[0]=~hit 로
        //    원본(O[0]=~hit)과 동일 — 하강 에지 검출 의미가 그대로 보존된다.
        taps_sampled_0_history <= taps_eff[0];

        // [Stage 2]
        if (dead_time_cnt > 0) begin
            dead_time_cnt <= dead_time_cnt - 1'b1;
            snapshot_valid_stg2 <= 1'b0;
        end
        else if (taps_eff[0] && !taps_sampled_0_history) begin
            dead_time_cnt <= DEAD_TIME_CYCLES;

            captured_c0_stg2   <= coarse_0;
            captured_c180_stg2 <= coarse_180_sync;

            // ★ [2026-09-03] 448탭 확장 — 고정 20 대신 NGRP 로
            for (i = 0; i < NGRP; i = i + 1) begin
                stg1_halfA[i] <= popcount8(taps_eff[i*16 +: 8]);
                stg1_halfB[i] <= popcount8(taps_eff[i*16+8 +: 8]);
            end
            snapshot_valid_stg2 <= 1'b1;
        end else begin
            snapshot_valid_stg2 <= 1'b0;
        end

        // [Stage 3]
        if (snapshot_valid_stg2) begin
            // ★ [2026-09-03] 448탭 확장 — 4덩어리 x GPQ묶음을 루프로 펼친다.
            //   80단(GPQ=5)이면 예전 4줄짜리 식과 글자 그대로 같은 덧셈이 나온다.
            //   합성 결과도 같은 덧셈 트리다 (누적 순서만 명시적으로 쓴 것).
            begin : CALC_STG3
                reg [7:0] acc;
                integer   q, g;
                for (q = 0; q < 4; q = q + 1) begin
                    acc = 8'd0;
                    for (g = 0; g < GPQ; g = g + 1)
                        acc = acc + stg1_halfA[q*GPQ + g] + stg1_halfB[q*GPQ + g];
                    stg3_group[q] <= acc;
                end
            end

            captured_c0_stg3 <= captured_c0_stg2;
            captured_c180_stg3_plus1 <= captured_c180_stg2 + 1'b1;

            snapshot_valid_stg3 <= 1'b1;
        end else begin
            snapshot_valid_stg3 <= 1'b0;
        end

        // [Stage 4]
        if (snapshot_valid_stg3) begin
            begin : CALC_FINE
                reg [8:0] sum_fine;
                // ★ [2026-09-03] 448탭 확장 — 배열로 바뀐 stg3_group 참조
                sum_fine = stg3_group[0] + stg3_group[1] + stg3_group[2] + stg3_group[3];
                fine_idx_stg4 <= sum_fine;

                // ★ [2026-09-03] 여기 있던 danger_zone 비교를 Stage 5 로 옮겼다.
                //   Stage 4 는 이제 덧셈만 한다. 이유는 파일 상단 DANGER_LO/HI 주석 참조.
            end

            captured_c0_stg4 <= captured_c0_stg3;
            captured_c180_stg4_plus1 <= captured_c180_stg3_plus1;
            snapshot_valid_stg4 <= 1'b1;
        end else begin
            snapshot_valid_stg4 <= 1'b0;
        end

        // [Stage 5]
        if (snapshot_valid_stg4) begin
            ts_fine_idx <= fine_idx_stg4;

            // ★ [2026-09-04] danger 판정을 여기서 한다 (Stage 4 에서 옮겨옴).
            //   fine_idx_stg4 는 레지스터 출력이므로 이 경로는 FF -> 비교 -> 먹스 -> FF 다.
            //   기존에 danger_zone_stg4 가 담고 있던 값과 완전히 동일하다
            //   (danger_zone_stg4 = f(sum_fine) 이고 fine_idx_stg4 == sum_fine).
            //
            //   [40, 220] 밖 = 클럭 에지 근처 = coarse_0 가 전이 중일 수 있다.
            //   그때는 반 주기 어긋난 180도 섀도우 카운터를 쓴다.
            //   이건 타이밍 수정이 아니라 메타스테이빌리티 회피다.
            //
            //   [2026-08-04 주의] 이 값은 O 탭 분포로 튜닝된 것이다. CO 탭은 탭당 폭
            //   분포가 달라 재튜닝이 필요할 수 있는데 아직 안 했다. 또 탭 번호 단위라
            //   보드마다 LSB 가 다르면 뜻이 달라진다 (40탭 = 집 Zybo 671 ps /
            //   ZedBoard 624 ps). AXI 단계에서 레지스터로 뺄 것.
            if (fine_idx_stg4 < DANGER_LO || fine_idx_stg4 > DANGER_HI) begin
                ts_coarse <= captured_c180_stg4_plus1;
            end else begin
                ts_coarse <= captured_c0_stg4;
            end

            ts_valid <= 1'b1;
        end else begin
            ts_valid <= 1'b0;
        end
    end
end
endmodule
