# =============================================================================
# bd_ps_sys.tcl  —  PS7 + 리셋 + AXI 인터커넥트 블록 디자인
# Generated by Claude Code, 2026-09-04
#
#  [이 블록 디자인에 든 것]
#    processing_system7  : Zynq PS (ARM). M_AXI_GP0 만 켠다.
#    proc_sys_reset      : FCLK_RESET0_N 을 동기 리셋으로 정리
#    axi_interconnect    : PS 의 AXI3 를 AXI4-Lite 로 변환 + 주소 디코딩
#
#  [왜 우리 RTL 은 여기 안 넣나]
#    tdc_axi_regs 를 BD 안에 넣으면 레지스터를 추가할 때마다 BD 를 다시 만들어야
#    한다. 2단계 이후로 레지스터가 계속 늘어날 예정이라, BD 는 PS 쪽만 담고
#    우리 RTL 은 평범한 Verilog 로 top 에서 붙인다. BD 는 한 번 만들면 안 바뀐다.
#
#  [★ 보드 프리셋을 못 쓴다 — 수동 설정]
#    이 Vivado 설치본에 ZedBoard 보드 파일이 없다 (get_board_parts *zed* 결과 없음).
#    그래서 apply_board_preset 대신 아래 값을 직접 넣는다.
#    ※ PCW_CRYSTAL_PERIPHERAL_FREQMHZ = 33.333333 은 ZedBoard 의 PS_CLK 오실레이터
#      주파수다. 이 값이 틀리면 PS PLL 설정이 어긋나 FCLK_CLK0 이 100 MHz 가 아니게 되는데,
#      Vivado 는 이를 검증할 방법이 없어 합성·타이밍·비트스트림이 전부 통과한다.
#      즉 틀려도 조용히 틀린다.
#      ★ 2026-09-05 확인 완료 — 이 값을 다시 의심하지 말 것. 근거 두 가지:
#        (1) 문서 : ZedBoard 매뉴얼에 PS_CLK 33.3333 MHz 로 명기 (사용자 확인)
#        (2) 실측 : tcl/xsct_stage1_check.tcl 로 STATUS[0] MMCM locked = 1 을 읽음.
#            clk_wiz_0 는 PRIM_IN_FREQ 100.000 전제로 배수가 고정돼 있으므로,
#            lock 이 걸렸다는 것은 FCLK_CLK0 이 100 MHz 근방으로 나온다는 뜻이다.
#        단, MMCM lock 허용 범위는 넓다. 이 두 근거는 "발진기가 33.333 MHz 계열이 맞다"
#        까지를 보장하며, 클럭 주기가 정확히 5000.0 ps 라는 뜻은 아니다.
#    ※ DDR / MIO 는 기본값 그대로 둔다. 1단계 검증은 XSCT 가 JTAG DAP 로
#      GP0 를 직접 두드리는 것이라 DDR 도 콘솔도 필요 없다.
#
#  [사용법]  build_zedboard.tcl 이 source 한다. 단독 실행도 가능:
#    vivado -mode batch -source tcl/bd_ps_sys.tcl
# =============================================================================

if {[llength [get_projects -quiet]] == 0} {
    create_project -in_memory -part xc7z020clg484-1
}

set BD_NAME ps_sys

create_bd_design $BD_NAME
current_bd_design [get_bd_designs $BD_NAME]

# ---------------------------------------------------------------- PS7
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7 ps7_0
set_property -dict [list \
    CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ {33.333333} \
    CONFIG.PCW_USE_M_AXI_GP0              {1} \
    CONFIG.PCW_EN_CLK0_PORT               {1} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ   {100} \
] [get_bd_cells ps7_0]

# ---------------------------------------------------------------- PS 전용 핀
#  ★ DDR 과 FIXED_IO 는 반드시 외부로 빼야 한다.
#    FIXED_IO 에 PS_CLK / PS_PORB / PS_SRSTB / MIO 가 들어 있다. 이걸 안 빼면
#    PS 의 클럭과 리셋이 어디에도 연결되지 않아 실물에서 PS 가 뜨지 않는다.
#    이 핀들은 Zynq 의 전용 핀이라 XDC 에 위치 제약을 쓸 필요가 없다 —
#    Vivado 가 자동으로 매핑한다.
make_bd_intf_pins_external -name DDR      [get_bd_intf_pins ps7_0/DDR]
make_bd_intf_pins_external -name FIXED_IO [get_bd_intf_pins ps7_0/FIXED_IO]

# ---------------------------------------------------------------- 리셋
create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset rst_0

# ---------------------------------------------------------------- 인터커넥트
#  지금은 슬레이브 1개(tdc_axi_regs)뿐이다. 2단계에서 교정표/히스토그램/캡처버퍼용
#  AXI BRAM Controller 3개가 붙으면 NUM_MI 를 4 로 올린다.
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect icn_0
set_property -dict [list CONFIG.NUM_SI {1} CONFIG.NUM_MI {1}] [get_bd_cells icn_0]

# ---------------------------------------------------------------- 연결
connect_bd_intf_net [get_bd_intf_pins ps7_0/M_AXI_GP0] [get_bd_intf_pins icn_0/S00_AXI]

# 클럭 : FCLK_CLK0 하나로 PS 의 AXI 포트와 인터커넥트 양쪽을 돌린다
set fclk [get_bd_pins ps7_0/FCLK_CLK0]
connect_bd_net $fclk [get_bd_pins ps7_0/M_AXI_GP0_ACLK]
connect_bd_net $fclk [get_bd_pins rst_0/slowest_sync_clk]
connect_bd_net $fclk [get_bd_pins icn_0/ACLK]
connect_bd_net $fclk [get_bd_pins icn_0/S00_ACLK]
connect_bd_net $fclk [get_bd_pins icn_0/M00_ACLK]

# 리셋
connect_bd_net [get_bd_pins ps7_0/FCLK_RESET0_N] [get_bd_pins rst_0/ext_reset_in]
set arstn [get_bd_pins rst_0/interconnect_aresetn]
connect_bd_net $arstn [get_bd_pins icn_0/ARESETN]
connect_bd_net $arstn [get_bd_pins icn_0/S00_ARESETN]
connect_bd_net $arstn [get_bd_pins icn_0/M00_ARESETN]

# ---------------------------------------------------------------- 외부로 뺄 것
#  AXI4-Lite 마스터 + 클럭 + 리셋만 밖으로 낸다. top 에서 tdc_axi_regs 에 붙인다.
#
#  ★ 외부 인터페이스 포트에 PROTOCOL 을 AXI4LITE 로 명시해야 한다.
#    안 하면 인터커넥트가 "상대가 뭔지 모르니 그대로 통과" 시켜서 PS 의 AXI3 신호
#    (arlen/arid/wlast/rlast ...)가 그대로 밖으로 나온다. 우리 슬레이브는 AXI4-Lite 라
#    받을 수 없다. 명시하면 인터커넥트가 프로토콜 변환기를 끼워 넣는다.
make_bd_intf_pins_external -name M_AXI [get_bd_intf_pins icn_0/M00_AXI]
set_property -dict [list CONFIG.PROTOCOL {AXI4LITE}                          CONFIG.DATA_WIDTH {32}                          CONFIG.ADDR_WIDTH {32}] [get_bd_intf_ports M_AXI]

#  ★ 클럭/리셋은 make_bd_pins_external 대신 포트를 직접 만들어 잇는다.
#    make_bd_pins_external 은 이미 여러 곳에 연결된 출력 핀에 대해 포트를 만들지
#    않는 경우가 있었다 (첫 시도에서 fclk_clk0 포트가 생성되지 않았다).
create_bd_port -dir O -type clk fclk_clk0
connect_bd_net [get_bd_ports fclk_clk0] $fclk
create_bd_port -dir O -type rst peripheral_arstn
connect_bd_net [get_bd_ports peripheral_arstn] [get_bd_pins rst_0/peripheral_aresetn]

#  클럭 포트에 AXI 인터페이스를 연관시킨다. 안 하면
#  "AXI interface port /M_AXI is not associated to any clock port" CRITICAL WARNING.
set_property CONFIG.ASSOCIATED_BUSIF {M_AXI} [get_bd_ports fclk_clk0]

# ---------------------------------------------------------------- 주소 배정
assign_bd_address

regenerate_bd_layout
validate_bd_design
save_bd_design

puts "\[*\] 블록 디자인 '$BD_NAME' 생성 완료"
foreach seg [get_bd_addr_segs -quiet] { puts "    주소구간 : $seg" }
