# =============================================================================
# capture_histogram.tcl  —  Mode 1 히스토그램 + 링오실레이터/온도 ILA 캡처
# Generated by Claude Code, 2026-09-05
#
#  [무엇을 하나]
#  보드에서 도는 TDC 의 히스토그램 BRAM 을 ILA 로 훑어 CSV 두 개를 만든다.
#    <out>/histo_<tag>.csv  — 탭별 누적 카운트 (파이썬 파이프라인 입력)
#    <out>/ro_<tag>.csv     — 링오실레이터 주파수 + 다이 온도 (측정 조건 기록)
#
#  [왜 ILA 인가]
#  AXI 2단계(히스토그램 리드백)가 아직 없어서, 히스토그램을 칩 밖으로 빼는
#  경로가 ILA 뿐이다. 2단계가 끝나면 이 스크립트는 필요 없어진다.
#
#  [자격저장(qualified capture)이 핵심이다]
#  ILA 는 1024 샘플밖에 못 담는데 탭은 384 칸이다. 매 클럭 담으면 384 칸을
#  한 바퀴도 못 본다. 그래서 CAPTURE_MODE 를 BASIC 으로 두고 특정 조건일 때만
#  담는다.
#    히스토그램 : readout_active == 1  (스캐너가 BRAM 을 훑는 구간만)
#                 -> 1024 샘플이 384 칸을 2.6 바퀴 덮는다. 2026-09-04 실측에서
#                    고유 주소 383 개(0x000~0x17f)가 모두 들어왔다.
#    RO/온도    : meas_strobe == 1     (1 초에 한 번 갱신되는 측정 완료 펄스)
#                 -> 1024 샘플 = 약 10 초분
#
#  [주소/데이터 짝이 어긋나지 않는 이유]
#  BRAM 포트 B 출력이 레지스터라 읽기 지연이 1 클럭이다. 그래서 RTL 이
#  probe_read_addr_d1 (한 클럭 늦춘 주소)을 ILA 에 보낸다. CSV 에서는
#  probe_read_addr_d1 과 histo_read_data 를 같은 행에서 짝지으면 맞다.
#
#  [실행]
#    vivado -mode batch -source tcl/capture_histogram.tcl -tclargs <프로젝트명> <태그>
#      예: vivado -mode batch -source tcl/capture_histogram.tcl -tclargs zed_axi fclk
#      -> vivado/histo_fclk.csv , vivado/ro_fclk.csv
#    인자를 생략하면 zed_axi / 날짜시각 태그를 쓴다.
#
#  [★ 사람이 버튼을 눌러야 한다 — 2026-09-05 에 이걸 몰라 빈 CSV 를 받았다]
#  리드아웃 스캔은 저절로 돌지 않는다. tdc_test_top.v 에서
#      wire sweep_finished = (!ps_busy_sync_d2 && ps_busy_sync_d3);   // ps_busy 하강 에지
#      if (sweep_finished && !readout_active) readout_active <= 1'b1;
#  즉 위상 시프터가 이동을 끝내는 순간에만 384칸 훑기가 시작된다. 그런데
#  phase_shifter 재설계(2026-09-04) 뒤로 ps_busy 는 phase_tgt != phase_cur 일 때만
#  뜨고, 목표 위상을 올리는 것은 현재 btn_shift 임시 블록뿐이다.
#      -> ILA 가 ARMED 라고 찍으면 ZedBoard 의 BTNU (T18) 를 누를 것. 몇 번 눌러도 된다.
#  Mode 1 은 clk_200_fixed 로 샘플링하므로, 위상이 움직여도 측정 자체는 영향받지 않는다.
#  버튼은 순전히 "리드아웃 시작 신호"로만 쓰인다.
#  (AXI 3단계에서 시퀀서를 넣으면 이 버튼은 없어진다)
#
#  [전제] 해당 프로젝트가 구현까지 끝나 debug_nets.ltx 가 있어야 하고,
#         보드에 그 비트스트림이 이미 구워져 있어야 한다.
#         (굽는 것은 tcl/xsct_stage1_check.tcl 또는 Vivado HW manager 가 한다)
# =============================================================================

set REPO C:/Work/FPGA/Project/Source/TDC

set PRJ_NAME zed_axi
set TAG      [clock format [clock seconds] -format %Y%m%d_%H%M]
if {[info exists argv] && [llength $argv] >= 1} { set PRJ_NAME [lindex $argv 0] }
if {[info exists argv] && [llength $argv] >= 2} { set TAG      [lindex $argv 1] }

set LTX_GLOB $REPO/vivado/$PRJ_NAME/$PRJ_NAME.runs/impl_1/*.ltx
set LTX [lindex [glob -nocomplain $LTX_GLOB] 0]
if {$LTX eq ""} {
    error "debug_nets.ltx 를 못 찾았다: $LTX_GLOB  (구현이 끝난 프로젝트인가?)"
}
set OUT_HISTO $REPO/vivado/histo_$TAG.csv
set OUT_RO    $REPO/vivado/ro_$TAG.csv

puts "\[*\] 프로젝트 : $PRJ_NAME"
puts "\[*\] LTX      : $LTX"
puts "\[*\] 출력     : $OUT_HISTO"
puts "\[*\]            $OUT_RO"

# ---------------------------------------------------------------- 하드웨어 연결
open_hw_manager
connect_hw_server -allow_non_jtag
open_hw_target [lindex [get_hw_targets] 0]
set dev [get_hw_devices xc7z020_1]
current_hw_device $dev
set_property PROBES.FILE $LTX $dev
refresh_hw_device $dev

set ila [lindex [get_hw_ilas] 0]
current_hw_ila $ila
puts "\[*\] ILA 프로브 [llength [get_hw_probes -of_objects $ila]] 개"

set_property CONTROL.TRIGGER_POSITION 0    $ila
set_property CONTROL.DATA_DEPTH       1024 $ila
set_property CONTROL.CAPTURE_MODE     BASIC $ila

set p_ms [get_hw_probes -of_objects $ila -filter {NAME =~ *meas_strobe*}]
set p_ra [get_hw_probes -of_objects $ila -filter {NAME =~ *readout_active*}]

# ---------------------------------------------------------------- 1) 히스토그램
# readout_active 가 1 인 클럭만 담는다. meas_strobe 는 조건에서 빼야 하므로
# 'X'(don't care) 로 둔다 — 두 조건을 다 걸면 AND 가 되어 거의 안 담긴다.
puts "\n\[1/2\] 히스토그램 캡처 (readout_active == 1)"
set_property TRIGGER_COMPARE_VALUE eq1'bX $p_ms
set_property CAPTURE_COMPARE_VALUE eq1'bX $p_ms
set_property TRIGGER_COMPARE_VALUE eq1'b1 $p_ra
set_property CAPTURE_COMPARE_VALUE eq1'b1 $p_ra
run_hw_ila $ila
puts ""
puts "  >>>>>>>>>>  ARMED — 지금 ZedBoard 의 BTNU (T18) 를 누르십시오  <<<<<<<<<<"
puts "             (누르지 않으면 readout_active 가 뜨지 않아 빈 CSV 가 나온다)"
puts ""
flush stdout
wait_on_hw_ila -timeout 180 $ila
upload_hw_ila_data $ila
write_hw_ila_data -csv_file $OUT_HISTO -force [current_hw_ila_data]
puts "      -> $OUT_HISTO"
# 빈 캡처를 조용히 넘기지 않는다 — 2026-09-05 에 0행 CSV 를 받고서야 알아챘다.
set nrow [llength [split [string trim [read [set _fh [open $OUT_HISTO r]]]] "\n"]]
close $_fh
if {$nrow <= 2} {
    puts "      ***** 데이터 0행 — 버튼을 안 눌렀거나 트리거를 놓쳤다. 다시 실행할 것."
} else {
    puts "      데이터 [expr {$nrow - 2}] 행"
}

# ---------------------------------------------------------------- 2) RO / 온도
puts "\n\[2/2\] 링오실레이터·온도 캡처 (meas_strobe == 1, 약 10 초)"
set_property TRIGGER_COMPARE_VALUE eq1'bX $p_ra
set_property CAPTURE_COMPARE_VALUE eq1'bX $p_ra
set_property TRIGGER_COMPARE_VALUE eq1'b1 $p_ms
set_property CAPTURE_COMPARE_VALUE eq1'b1 $p_ms
run_hw_ila $ila
wait_on_hw_ila -timeout 60 $ila
upload_hw_ila_data $ila
write_hw_ila_data -csv_file $OUT_RO -force [current_hw_ila_data]
puts "      -> $OUT_RO"

puts "\n=================================================="
puts " 캡처 완료. 다음: python/Histogram.py 로 Tap_Index,Hit_Count 추출"
puts "=================================================="
close_hw_manager
