# =============================================================================
# make_axi_stage1_prj.tcl  —  AXI 1단계 확인용 Vivado 프로젝트 생성
# Generated by Claude Code, 2026-09-04
#
#  [왜 이 스크립트가 따로 있나]
#  블록 디자인을 눈으로 보고 확인할 수 있어야 한다. 임시 폴더가 아니라
#  저장소 안(vivado/zed_axi_stage1)에 프로젝트를 만들어서 Vivado GUI 로
#  열어볼 수 있게 한다.
#
#  [열어보는 법]
#    Vivado 실행 -> Open Project ->
#      C:/Work/FPGA/Project/Source/TDC/vivado/zed_axi_stage1/zed_axi_stage1.xpr
#    좌측 Sources 창에서 ps_sys.bd 를 더블클릭하면 블록 디자인이 보인다.
#
#  [만드는 법]
#    cd C:/Work/FPGA/Project/Source/TDC
#    vivado -mode batch -source tcl/make_axi_stage1_prj.tcl
#
#  [지금 이 프로젝트에 든 것]
#    - ps_sys 블록 디자인 (PS7 + proc_sys_reset + AXI 인터커넥트)
#    - RTL 전체 (tdc_axi_regs.v 포함)
#    ※ 아직 top 이 BD 를 인스턴스하지 않는다. 클럭 구성을 확정한 뒤에 잇는다.
#      지금은 "블록 디자인이 이렇게 생겼다" 를 확인하는 용도다.
# =============================================================================

set SRC_ROOT [file normalize [file join [file dirname [info script]] ..]]
set PRJ_DIR  [file join $SRC_ROOT vivado zed_axi_stage1]

if {[file exists $PRJ_DIR]} {
    file delete -force $PRJ_DIR
    puts "\[*\] 기존 프로젝트 삭제 : $PRJ_DIR"
}

create_project zed_axi_stage1 $PRJ_DIR -part xc7z020clg484-1 -force
set_property target_language Verilog [current_project]

# ---------------------------------------------------------------- RTL 추가
set VSRC [list \
    [file join $SRC_ROOT RTL tdc_zedboard_top.v]   \
    [file join $SRC_ROOT RTL tdc_test_top.v]       \
    [file join $SRC_ROOT RTL tdc_fmcw_core_co.v]   \
    [file join $SRC_ROOT RTL tdc_timestamp_calc.v] \
    [file join $SRC_ROOT RTL tdc_histogram.v]      \
    [file join $SRC_ROOT RTL phase_shifter.v]      \
    [file join $SRC_ROOT RTL dna_reader.v]         \
    [file join $SRC_ROOT RTL tdc_axi_regs.v]       \
]
add_files -norecurse -fileset sources_1 $VSRC
add_files -norecurse -fileset constrs_1 [file join $SRC_ROOT RTL tdc_zedboard.xdc]
update_compile_order -fileset sources_1

# ---------------------------------------------------------------- 블록 디자인
source [file join $SRC_ROOT tcl bd_ps_sys.tcl]
make_wrapper -files [get_files ps_sys.bd] -top
add_files -norecurse [file join $PRJ_DIR zed_axi_stage1.gen sources_1 bd ps_sys hdl ps_sys_wrapper.v]
update_compile_order -fileset sources_1

# ---------------------------------------------------------------- 확인 출력
puts ""
puts "=================================================================="
puts " 프로젝트 : $PRJ_DIR/zed_axi_stage1.xpr"
puts "=================================================================="
puts " Vivado GUI 에서 열어 Sources -> ps_sys.bd 더블클릭하면 보인다."
puts ""
puts " \[블록 디자인 구성\]"
foreach c [get_bd_cells] {
    puts "   셀 : [format %-10s $c]  ([get_property VLNV $c])"
}
puts ""
puts " \[외부 포트\]"
#  ※ get_bd_ports 는 인터페이스를 구성하는 개별 신호까지 다 나열해서 오해를 준다
#    (AXI4-Lite 로 설정했는데도 arlen/awregion 같은 옛 항목이 남아 보인다).
#    실제로 생성되는 HDL 은 아래 래퍼 포트가 진실이므로 그것을 찍는다.
foreach p [get_bd_intf_ports] { puts "   $p  (인터페이스, PROTOCOL=[get_property CONFIG.PROTOCOL $p])" }
foreach p {fclk_clk0 peripheral_arstn} { puts "   /$p  ([get_property DIR [get_bd_ports $p]])" }
puts ""
puts " \[PS7 설정\]"
foreach k {PCW_CRYSTAL_PERIPHERAL_FREQMHZ PCW_FPGA0_PERIPHERAL_FREQMHZ PCW_USE_M_AXI_GP0} {
    puts "   $k = [get_property CONFIG.$k [get_bd_cells ps7_0]]"
}
puts ""
puts " \[주소\]"
foreach s [get_bd_addr_segs -quiet -of_objects [get_bd_addr_spaces]] {
    puts "   $s : [get_property OFFSET $s] , 크기 [get_property RANGE $s]"
}
puts "=================================================================="
