# =============================================================================
# xsct_capture_raw.tcl  —  Mode 2 캡처를 raw {coarse, fine} 로 받는다
# Generated by Claude Code, 2026-09-06
#
#  [왜 raw 인가]
#  기본(CAP_FMT=0)은 하드웨어가 계산한 timestamp_ps 를 준다. 그 계산은
#      timestamp_ps = coarse x 5000 - ROM[fine]
#  이고, 지금 ROM 에는 **선형 램프**만 들어 있다 (0..4987 ps, 한 칸 13 ps).
#  그런데 이 빌드의 실제 지연선은 탭 24~348 을 쓰고 한 칸이 약 15.38 ps 다.
#  즉 ROM 의 눈금이 실제와 안 맞아, 계산된 timestamp 에 수백 ps 의 계통 오차가 섞인다.
#
#  raw 로 받으면 ROM 을 거치지 않은 원본 {coarse, fine} 이 그대로 나온다.
#  파이썬에서 올바른 눈금으로 다시 계산해 비교하면, 관측된 흔들림이
#  ROM 탓인지 TDC 자체 탓인지 갈린다.
#
#  [실행]  "C:/Xilinx/Vitis/2024.1/bin/xsct.bat" tcl/xsct_capture_raw.tcl [프로젝트명]
#  [결과]  vivado/capture_raw.csv  (Index, Coarse, Fine)
#          vivado/capture_raw.log
#
#  ※ 보드에 비트스트림이 이미 구워져 있어야 한다. 이 스크립트는 굽지 않는다 —
#    같은 신호를 연속으로 두 형식으로 받아 비교하려는 것이므로, 다시 구우면
#    히스토그램과 danger 설정이 초기화되어 조건이 달라진다.
# =============================================================================

set PRJ_NAME zed_pmod
if {[info exists argv] && [llength $argv] >= 1} { set PRJ_NAME [lindex $argv 0] }
set OUT C:/Work/FPGA/Project/Source/TDC/vivado/capture_raw.csv
set LOG C:/Work/FPGA/Project/Source/TDC/vivado/capture_raw.log
set BASE 0x43C00000

set ::LOGFH [open $LOG w]
fconfigure $::LOGFH -encoding utf-8
proc say {s} { puts $s ; puts $::LOGFH $s ; flush $::LOGFH }

set R_CTRL   [expr {$BASE + 0x08}]
set R_STATUS [expr {$BASE + 0x0C}]
set R_DROP   [expr {$BASE + 0x38}]
set R_CAPN   [expr {$BASE + 0x3C}]
set R_CAPCNT [expr {$BASE + 0x40}]
set R_CAP    [expr {$BASE + 0x8000}]

set SRC_EXT     0x03
set BIT_START   [expr {1 << 2}]
set BIT_CAP_FMT [expr {1 << 6}]     ;# 1 = raw {coarse, fine}
set CAP_N       1024

connect
after 3000
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}
after 200
proc rd {addr} { return [expr {"0x[lindex [mrd -force $addr] 1]"}] }
proc rd_block {addr n} {
    set out {}
    foreach t [regexp -all -inline {\S+} [mrd -force $addr $n]] {
        if {[string first ":" $t] < 0} { lappend out [expr {"0x$t"}] }
    }
    return $out
}

say "\[*\] raw 캡처 (CAP_FMT=1)"
mwr -force $R_CAPN $CAP_N
mwr -force $R_CTRL [expr {$SRC_EXT | $BIT_START | $BIT_CAP_FMT}]

set t0 [clock milliseconds]
while {([clock milliseconds]-$t0) < 20000} {
    if {([rd $R_STATUS] >> 4) & 1} { break }
}
set n [rd $R_CAPCNT]
say [format "  CAP_CNT = %d / %d,  DROP_CNT = %d" $n $CAP_N [rd $R_DROP]]

if {$n > 0} {
    set w [rd_block $R_CAP [expr {$n*2}]]
    set fh [open $OUT w]
    puts $fh "Index,Coarse,Fine"
    for {set i 0} {$i < $n} {incr i} {
        set co [lindex $w [expr {$i*2}]]        ;# 워드0 = coarse[31:0]
        set fi [expr {[lindex $w [expr {$i*2+1}]] & 0x1FF}]   ;# 워드1 = {0, fine[8:0]}
        puts $fh "$i,$co,$fi"
    }
    close $fh
    say "  -> $OUT"
    say [format "  첫 3개 : coarse %s fine %s / %s %s / %s %s" \
            [lindex $w 0] [expr {[lindex $w 1] & 0x1FF}] \
            [lindex $w 2] [expr {[lindex $w 3] & 0x1FF}] \
            [lindex $w 4] [expr {[lindex $w 5] & 0x1FF}]]
} else {
    say "  ***** 한 발도 안 들어왔다"
}
mwr -force $R_CTRL 0x0
close $::LOGFH
disconnect
