# =============================================================================
# xsct_stage2_check.tcl  —  AXI 2단계 실물 검증 (히스토그램 리드백 + ILA 제거)
# Generated by Claude Code, 2026-09-05
#
#  [무엇을 확인하나]
#  ILA 도 BTNU 버튼도 없이, PS 가 AXI 레지스터만으로 히스토그램을 읽어오는지 본다.
#
#    1) BUILD 가 0x01806003 인가        — 맵 버전 3 = 이번 빌드가 맞는지
#    2) HISTO_CLR 로 실제로 0 이 되는가 — 제어 비트가 하드웨어에 닿는지
#    3) 384탭을 읽어 분포가 나오는가    — 읽기 경로 + 지연 처리(hpend)가 맞는지
#    4) RO_CNT / DIE_TEMP 가 그럴듯한가 — 다중비트 CDC(토글 핸드셰이크)가 맞는지
#    5) PHASE 로 위상이 움직이는가      — BTNU 대체가 됐는지
#
#  [★ 3번이 핵심이다]
#  히스토그램 BRAM 은 출력이 레지스터드라 주소를 걸고 2클럭 뒤에야 값이 나온다.
#  tdc_axi_regs 의 hpend 시프트 레지스터가 그 2클럭을 세는데, 이게 틀리면
#  히스토그램 전체가 한 칸 밀려 나온다. ILA 시절 probe_read_addr_d1 로 겪었던
#  것과 같은 함정이다. 판정은 "모양이 밀렸는지"로 한다 —
#  탭 0,1 은 원래 0 이고 탭 2 부터 히트가 시작되므로, 밀리면 그 경계가 어긋난다.
#
#  [실행]
#    "C:/Xilinx/Vitis/2024.1/bin/xsct.bat" tcl/xsct_stage2_check.tcl
#
#  [★ 결과를 눈으로 보려면]
#    화면에 찍히는 것과 똑같은 내용이 아래 두 파일로 남는다. 메모장으로 열면 된다.
#      vivado/stage2_check.log  — 검사 결과 전문
#      vivado/histo_axi.csv     — AXI 로 읽은 384탭 (Tap_Index,Hit_Count)
#    XSCT 가 하는 일은 별게 아니다. Vitis 에서 손으로 할 일을 미리 적어둔 것뿐이다 —
#    JTAG 로 ARM 코어에 붙어 mrd(메모리 읽기) / mwr(메모리 쓰기) 를 날린다.
#    C 프로그램을 보드에 올릴 필요가 없다.
#
#  [순서가 중요하다 — 1단계 스크립트와 같은 이유]
#    ps7_init 을 먼저 해야 FCLK_CLK0 가 나오고, 그래야 AXI 도 MMCM 도 돈다.
#    connect 뒤 after 3000 은 hw_server 의 JTAG 체인 열거를 기다리는 것이다.
#    fpga -file 은 FPGA 타깃을, mrd/mwr 은 ARM 타깃을 요구한다.
# =============================================================================

set PRJ  C:/Work/FPGA/Project/Source/TDC/vivado/zed_axi2
set OUT  C:/Work/FPGA/Project/Source/TDC/vivado/histo_axi.csv
set LOG  C:/Work/FPGA/Project/Source/TDC/vivado/stage2_check.log
set BASE 0x43C00000

# ★ 2026-09-05 : 화면과 파일에 동시에 찍는다.
#   터미널에서만 돌리면 결과를 나중에 볼 방법이 없다. 파일로 남겨야 확인이 된다.
set ::LOGFH [open $LOG w]
fconfigure $::LOGFH -encoding utf-8
proc say {s} {
    puts $s
    puts $::LOGFH $s
    flush $::LOGFH
}

# 레지스터 오프셋
set R_ID     [expr {$BASE + 0x00}]
set R_BUILD  [expr {$BASE + 0x04}]
set R_CTRL   [expr {$BASE + 0x08}]
set R_STATUS [expr {$BASE + 0x0C}]
set R_DNA    [expr {$BASE + 0x10}]
set R_ROCNT  [expr {$BASE + 0x14}]
set R_TEMP   [expr {$BASE + 0x18}]
set R_PHASE  [expr {$BASE + 0x1C}]
set R_HISTO  [expr {$BASE + 0x1000}]

set NUM_TAPS 384
set BIT_HISTO_CLR [expr {1 << 4}]

proc find_one {pat desc} {
    set f [glob -nocomplain $pat]
    if {[llength $f] == 0} { error "$desc 를 못 찾았다: $pat" }
    return [lindex $f 0]
}
set BIT      [find_one $PRJ/zed_axi2.runs/impl_1/*.bit "비트스트림"]
set PS7_INIT [find_one $PRJ/*.gen/sources_1/bd/ps_sys/ip/*ps7_0_0/ps7_init.tcl "ps7_init.tcl"]
say "\[*\] bit      : $BIT"
say "\[*\] ps7_init : $PS7_INIT"

connect
after 3000
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}
catch {stop}
after 200
source $PS7_INIT
ps7_init
ps7_post_config
say "\[*\] ps7_init 완료"

targets -set -nocase -filter {name =~ "xc7z020"}
fpga -file $BIT
say "\[*\] 비트스트림 다운로드 완료"
after 500
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}

proc rd {addr} { return [expr {"0x[lindex [mrd -force $addr] 1]"}] }

# mrd 를 개수와 함께 부르면 "주소: 값 값 값 값" 형태로 여러 줄이 온다.
# 주소 토큰(콜론이 붙은 것)만 걸러내면 값만 순서대로 남는다.
proc rd_block {addr n} {
    set out {}
    foreach t [regexp -all -inline {\S+} [mrd -force $addr $n]] {
        if {[string first ":" $t] < 0} { lappend out [expr {"0x$t"}] }
    }
    return $out
}

set fail 0
proc chk {name got exp} {
    global fail
    if {$got == $exp} {
        say [format "  OK    %-8s = 0x%08X" $name $got]
    } else {
        say [format "  FAIL  %-8s = 0x%08X   (기대 0x%08X)" $name $got $exp]
        incr fail
    }
}

# ---------------------------------------------------------------- 1) 신원
say "\n\[1\] 신원 / 빌드"
chk ID    [rd $R_ID]    0x54444302
chk BUILD [rd $R_BUILD] 0x01806003
chk DNA   [rd $R_DNA]   0xBD996854
set st [rd $R_STATUS]
say [format "  STATUS = 0x%08X   MMCM=%d DNA_VALID=%d PHASE_BUSY=%d" \
        $st [expr {$st & 1}] [expr {($st>>2)&1}] [expr {($st>>5)&1}]]
if {($st & 1) == 0} { say "  FAIL  MMCM 이 안 잠겼다"; incr fail }

# ---------------------------------------------------------------- 2) 측정 조건
say "\n\[2\] 측정 조건 (다중비트 CDC 확인)"
set ro   [rd $R_ROCNT]
set traw [expr {[rd $R_TEMP] & 0xFFFF}]
# UG480 eq.2-6 : T[C] = raw/65536 * 503.975 - 273.15
set tc [expr {$traw / 65536.0 * 503.975 - 273.15}]
say [format "  RO_CNT   = %d  (10 ms 게이트당 에지 수)" $ro]
say [format "  DIE_TEMP = 0x%04X -> %.2f C" $traw $tc]
if {$ro < 1000 || $ro > 10000000} { say "  FAIL  RO_CNT 가 말이 안 된다"; incr fail }
if {$tc  < 0    || $tc  > 100}    { say "  FAIL  온도가 말이 안 된다";   incr fail }

# ---------------------------------------------------------------- 3) HISTO_CLR
say "\n\[3\] HISTO_CLR — 제어 비트가 하드웨어에 닿는가"
mwr -force $R_CTRL $BIT_HISTO_CLR
after 50
# 지우는 중에는 CLEAR 상태에 머물러 누적이 멈춘다. 몇 칸 찍어 0 인지 본다.
set zsum 0
foreach i {2 50 150 300} {
    incr zsum [rd [expr {$R_HISTO + $i*4}]]
}
say [format "  지우기 유지 중 탭 2/50/150/300 합 = %d  (0 이어야 한다)" $zsum]
if {$zsum != 0} { say "  FAIL  HISTO_CLR 이 안 먹었다"; incr fail }

mwr -force $R_CTRL 0x0
say "  지우기 해제 -> 5 초 누적"
after 5000

# ---------------------------------------------------------------- 4) 384탭 읽기
say "\n\[4\] 히스토그램 384탭 읽기"
set h [rd_block $R_HISTO $NUM_TAPS]
if {[llength $h] != $NUM_TAPS} {
    say "  FAIL  [llength $h] 개만 읽혔다 (기대 $NUM_TAPS)"; incr fail
}
set H 0
set first -1
set last  -1
for {set i 0} {$i < [llength $h]} {incr i} {
    set v [lindex $h $i]
    incr H $v
    if {$v > 0} { if {$first < 0} { set first $i } ; set last $i }
}
say [format "  총 히트 H        = %d" $H]
say [format "  히트 있는 탭     = %d ~ %d" $first $last]
say [format "  탭 0,1,2,3       = %d, %d, %d, %d" \
        [lindex $h 0] [lindex $h 1] [lindex $h 2] [lindex $h 3]]
say [format "  탭 320,321,322   = %d, %d, %d" \
        [lindex $h 320] [lindex $h 321] [lindex $h 322]]

# 판정 : 2026-09-05 ILA 측정에서 히트는 탭 2~321 이었다.
#   first 가 1 이면 한 칸 앞으로 밀린 것(hpend 가 한 클럭 짧다),
#   3 이면 한 칸 뒤로 밀린 것이다.
if {$H == 0} {
    say "  FAIL  누적이 0 이다 — 링오실레이터나 누적 경로 문제"; incr fail
} elseif {$first != 2} {
    say "  FAIL  히트 시작 탭이 $first 다. 2 여야 한다 -> 읽기 지연(hpend) 의심"
    incr fail
} else {
    say "  OK    시작 탭 2 — 밀림 없음"
}

set fh [open $OUT w]
puts $fh "Tap_Index,Hit_Count"
for {set i 0} {$i < [llength $h]} {incr i} { puts $fh "$i,[lindex $h $i]" }
close $fh
say "  -> $OUT"

# ---------------------------------------------------------------- 5) PHASE
say "\n\[5\] PHASE — BTNU 없이 위상이 움직이는가"
set p0 [expr {([rd $R_PHASE] >> 16) & 0x1FF}]
mwr -force $R_PHASE 40
set spin 0
while {$spin < 200} {
    if {([rd $R_STATUS] & (1 << 5)) == 0} { break }
    incr spin
}
set p1 [expr {([rd $R_PHASE] >> 16) & 0x1FF}]
say [format "  현재 위상 %d -> %d  (목표 40, BUSY 폴링 %d회)" $p0 $p1 $spin]
if {$p1 != 40} { say "  FAIL  목표 위상에 도달하지 못했다"; incr fail }
mwr -force $R_PHASE 0

say "\n=================================================="
if {$fail == 0} {
    say " 2단계 통과 — ILA·버튼 없이 AXI 로 히스토그램을 읽는다"
} else {
    say " 실패 $fail 건"
}
say "=================================================="
close $::LOGFH
disconnect
