# =============================================================================
# xsct_mode2_check.tcl  —  Mode 2 (외부 LVDS) 수신 확인 + Mode 1 회귀 검사
# Generated by Claude Code, 2026-09-05
#
#  [무엇을 확인하나]
#  A. Mode 1 회귀 — 히트 네트 앞에 먹스 LUT 이 끼었는데 지연선이 나빠지지 않았나
#  B. Mode 2 수신 — 외부 LVDS 비트 신호가 실제로 들어와 타임스탬프가 찍히는가
#
#  [★ A 를 먼저 하는 이유]
#  이번 빌드에서 HIT_SRC 가 런타임 먹스가 되면서 히트 네트 앞에 LUT 이 하나
#  끼었다. "hit 은 CYINIT 외에 부하를 걸면 안 된다" 는 규칙은 팬아웃에 관한
#  것이라 이건 위반이 아니지만, 먹스 LUT 때문에 에지 slew 가 달라질 수 있다.
#  slew 가 나빠지면 캐리체인 진입 트랜지언트가 커진다 — 예전 led[2] 사례에서
#  초입 3탭이 정상값의 1.16~1.89배가 된 적이 있다.
#  판정은 진입부 탭(2,3번)의 비율을 2026-09-05 3단계 결과와 대조해서 한다.
#
#  [B 의 판정 기준]
#  비트 신호는 34~86 kHz(9/3 실측) 또는 최대 1 MHz 다. 히트가 들어오면
#  CAP_CNT 가 올라가고 CAP_N 에 도달해 DONE 이 뜬다. 전혀 안 오면 CAP_CNT 가
#  0 에 머문다 — 그 경우 원인은 J18 점퍼(2.5V), FMC 연결, 비교기 전원 순이다.
#  타임스탬프의 '간격' 이 비트 주기와 맞는지까지 봐야 진짜 확인이다.
#
#  [실행]
#    "C:/Xilinx/Vitis/2024.1/bin/xsct.bat" tcl/xsct_mode2_check.tcl
#  [결과 파일]
#    vivado/mode2_check.log   /  vivado/histo_mux.csv  /  vivado/capture.csv
# =============================================================================

# ★ 2026-09-05 : 프로젝트 이름을 두 번째 인자로 받는다 (기본 zed_mode2).
#   PMOD 빌드는 zed_pmod 로 따로 만들므로 스크립트를 고치지 않고 쓸 수 있어야 한다.
set PRJ_NAME zed_mode2
if {[info exists argv] && [llength $argv] >= 2} { set PRJ_NAME [lindex $argv 1] }
set PRJ  C:/Work/FPGA/Project/Source/TDC/vivado/$PRJ_NAME
set LOG  C:/Work/FPGA/Project/Source/TDC/vivado/mode2_check.log
set OUTH C:/Work/FPGA/Project/Source/TDC/vivado/histo_mux.csv
set OUTC C:/Work/FPGA/Project/Source/TDC/vivado/capture.csv
set BASE 0x43C00000

set ::LOGFH [open $LOG w]
fconfigure $::LOGFH -encoding utf-8
proc say {s} { puts $s ; puts $::LOGFH $s ; flush $::LOGFH }

set R_ID     [expr {$BASE + 0x00}]
set R_BUILD  [expr {$BASE + 0x04}]
set R_CTRL   [expr {$BASE + 0x08}]
set R_STATUS [expr {$BASE + 0x0C}]
set R_TARGET [expr {$BASE + 0x20}]
set R_HITCNT [expr {$BASE + 0x24}]
set R_DROP   [expr {$BASE + 0x38}]
set R_CAPN   [expr {$BASE + 0x3C}]
set R_CAPCNT [expr {$BASE + 0x40}]
set R_DANGER [expr {$BASE + 0x44}]
set R_HISTO  [expr {$BASE + 0x1000}]
set R_CAP    [expr {$BASE + 0x8000}]

# ★ 2026-09-05 : 인자로 Mode 2 검사를 건너뛸 수 있다.
#   외부 비교기가 없으면 B 는 어차피 0 발이 나온다. A(회귀 검사)만 돌린다.
#     xsct tcl/xsct_mode2_check.tcl 0             -> A 만, 프로젝트 zed_mode2
#     xsct tcl/xsct_mode2_check.tcl 1 zed_pmod    -> A + B, 프로젝트 zed_pmod
set DO_MODE2 1
if {[info exists argv] && [llength $argv] >= 1} { set DO_MODE2 [lindex $argv 0] }

set NUM_TAPS  384

# 2026-09-05 3단계(먹스 없음, 총 200만 발) 진입부 실측값 — 회귀 판정 기준.
# 출처 : Data/20260905_zed_fsm/histo_fsm.csv
set REF_T2 4093
set REF_T3 17993
set REF_T4 404
set REF_H  2000000
set SRC_RO    0x01
set SRC_EXT   0x03
set BIT_START [expr {1 << 2}]
set CAP_N     1024          ;# 1024 발. 1 kHz 면 1 초, 60 kHz 면 17 ms, 1 MHz 면 1 ms
set B_TIMEOUT 20000         ;# STM32 주파수를 모르므로 넉넉히 20 초 기다린다

proc find_one {pat desc} {
    set f [glob -nocomplain $pat]
    if {[llength $f] == 0} { error "$desc 를 못 찾았다: $pat" }
    return [lindex $f 0]
}
set BIT      [find_one $PRJ/$PRJ_NAME.runs/impl_1/*.bit "비트스트림"]
set PS7_INIT [find_one $PRJ/*.gen/sources_1/bd/ps_sys/ip/*ps7_0_0/ps7_init.tcl "ps7_init.tcl"]
say "\[*\] bit : $BIT"

connect
after 3000
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}
catch {stop}
after 200
source $PS7_INIT
ps7_init
ps7_post_config
targets -set -nocase -filter {name =~ "xc7z020"}
fpga -file $BIT
after 500
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}
say "\[*\] 비트스트림 다운로드 완료"

proc rd {addr} { return [expr {"0x[lindex [mrd -force $addr] 1]"}] }
proc rd_block {addr n} {
    set out {}
    foreach t [regexp -all -inline {\S+} [mrd -force $addr $n]] {
        if {[string first ":" $t] < 0} { lappend out [expr {"0x$t"}] }
    }
    return $out
}
set STATE_NAME {S_IDLE S_RO_ENABLE S_MEAS_FREQ S_STABILIZE S_ACQ S_DONE ? ?}
proc st_name {st} { global STATE_NAME ; return [lindex $STATE_NAME [expr {($st>>8)&7}]] }

set fail 0

# ---------------------------------------------------------------- 신원
say "\n\[0\] 신원"
set bld [rd $R_BUILD]
say [format "  ID=0x%08X  BUILD=0x%08X  (맵 버전 %d)" [rd $R_ID] $bld [expr {$bld & 0xFF}]]
if {[rd $R_ID] != 0x54444302} { say "  FAIL ID" ; incr fail }
if {$bld != 0x01806006}       { say "  FAIL BUILD (기대 0x01806006)" ; incr fail }

# ================================================================ A. Mode 1 회귀
say "\n\[A\] Mode 1 회귀 — 히트 먹스가 지연선을 나쁘게 했나"
mwr -force $R_TARGET 2000000
mwr -force $R_CTRL [expr {$SRC_RO | $BIT_START}]
set t0 [clock milliseconds]
while {([clock milliseconds]-$t0) < 60000} {
    if {([rd $R_STATUS] >> 4) & 1} { break }
}
set hit_cnt [rd $R_HITCNT]
set h [rd_block $R_HISTO $NUM_TAPS]
set H 0 ; set first -1 ; set last -1
for {set i 0} {$i < [llength $h]} {incr i} {
    set v [lindex $h $i]
    incr H $v
    if {$v > 0} { if {$first < 0} { set first $i } ; set last $i }
}
say [format "  HIT_CNT=%d   384탭 합=%d   차이=%d" $hit_cnt $H [expr {$hit_cnt-$H}]]
say [format "  히트 있는 탭 = %d ~ %d" $first $last]
if {$hit_cnt != $H} { say "  FAIL  HIT_CNT 와 탭 합이 다르다" ; incr fail }

# ★ 2026-09-05 : 판정 기준을 바꿨다.
#   [무엇이 문제였나] 처음엔 first != 2 || last != 321 로 봤다. 그런데 창의 절대
#     위치는 히트 경로 지연에 따라 통째로 미끄러지는 값이지 지연선 품질이 아니다.
#     실제로 HIT_SRC 먹스(LUT4)가 들어가자 히트가 약 370 ps 늦어져 창이 24~349 로
#     옮겨갔는데, tap%4 폭과 sigma 는 그대로였다. 즉 멀쩡한 것을 실패로 판정했다.
#   [바꾼 기준] 체인 끝까지 남은 여유가 진짜 기준이다. 여유가 없으면 온도가
#     올랐을 때 sum_fine 이 384 를 넘어 ROM 주소 범위 밖으로 나간다.
set headroom [expr {$NUM_TAPS - 1 - $last}]
say [format "  체인 끝까지 남은 여유 = %d 탭  (창 끝 %d, 체인 끝 %d)"         $headroom $last [expr {$NUM_TAPS-1}]]
say [format "    평균 폭 %.2f ps 로 어림하면 약 %.0f ps — 어림값이다."         [expr {5000.0/($last-$first+1)}]         [expr {$headroom * 5000.0/($last-$first+1)}]]
say "    ※ 그 탭들에는 히트가 안 오므로 폭이 측정되지 않는다. 평균으로 어림한 값이다."
if {$headroom < 20} {
    say "  FAIL  여유가 20탭 미만이다 — 온도가 오르면 체인 끝을 넘어간다"
    incr fail
} else {
    say "  OK    여유 충분"
}

# 진입부 탭 비율 — 2026-09-05 3단계(먹스 없음) 값과 대조
#   3단계 실측 : 탭2 12667, 탭3 55202 (총 200만 발 기준, stage2 로그 계열)
#   여기서는 총합이 같으므로(200만) 직접 비교할 수 있다.
set t2 [lindex $h 2] ; set t3 [lindex $h 3] ; set t4 [lindex $h 4]

# 폭 w[i] = h[i]/H x 5000 ps 로 환산해 비교한다. 총합이 달라도 공정하게 비교된다.
proc wps {hv Hv} { return [expr {$hv * 5000.0 / $Hv}] }
say [format "  %-4s %10s %10s %12s %12s" "탭" "이번" "3단계" "폭(ps)" "3단계(ps)"]
foreach {idx cur ref} [list 2 $t2 $REF_T2  3 $t3 $REF_T3  4 $t4 $REF_T4] {
    say [format "  %-4d %10d %10d %12.2f %12.2f" $idx $cur $ref \
            [wps $cur $H] [wps $ref $REF_H]]
}
set d2 [expr {[wps $t2 $H] / [wps $REF_T2 $REF_H]}]
set d3 [expr {[wps $t3 $H] / [wps $REF_T3 $REF_H]}]
set d4 [expr {[wps $t4 $H] / [wps $REF_T4 $REF_H]}]
say [format "  폭 비 (이번/3단계) : 탭2 %.3f  탭3 %.3f  탭4 %.3f" $d2 $d3 $d4]
say "  ※ 판정 : 1.0 근처면 먹스 LUT 이 에지 slew 에 영향을 주지 않은 것이다."
say "     예전 led\[2\] 사례에서는 초입 3탭이 1.16~1.89배가 됐었다."
if {$d2 > 1.15 || $d3 > 1.15} {
    say "  ***** 진입부가 15% 넘게 넓어졌다 — 먹스 LUT 의 slew 영향을 의심할 것"
    incr fail
} else {
    say "  OK    진입부 변화가 15% 안이다"
}
set fh [open $OUTH w]
puts $fh "Tap_Index,Hit_Count"
for {set i 0} {$i < [llength $h]} {incr i} { puts $fh "$i,[lindex $h $i]" }
close $fh
say "  -> $OUTH"
mwr -force $R_CTRL 0x0
after 100

# ================================================================ danger 임계값
say "\n\[A-2\] danger 임계값을 측정한 창에 맞춘다"
#  danger 는 "히트가 클럭 에지 근처인가" 를 fine 탭 번호로 판단하는 경계다.
#  에지는 창의 양 끝 두 곳이므로, 양끝에서 같은 시간만큼을 가드로 잡는다.
#  가드 폭은 coarse 카운터가 흔들리는 시간보다 커야 하는데, 그 값이 측정된 적이
#  없다. 종전 상수 40/220 의 아래 가드가 630 ps 였으므로 그것을 기준으로 삼는다.
set GUARD_PS 630.0
proc taps_for_ps {hlist H startTap dir target} {
    set acc 0.0 ; set i $startTap ; set n 0
    while {$i >= 0 && $i < [llength $hlist]} {
        set acc [expr {$acc + [lindex $hlist $i]*5000.0/$H}]
        incr n
        if {$acc >= $target} { break }
        incr i $dir
    }
    return [list $i $acc $n]
}
lassign [taps_for_ps $h $H $first  1 $GUARD_PS] lo_tap lo_ps lo_n
lassign [taps_for_ps $h $H $last  -1 $GUARD_PS] hi_tap hi_ps hi_n
say [format "  아래 가드 : 탭 %d~%d (%d칸) = %.1f ps  -> DANGER_LO = %d"         $first $lo_tap $lo_n $lo_ps [expr {$lo_tap+1}]]
say [format "  위  가드 : 탭 %d~%d (%d칸) = %.1f ps  -> DANGER_HI = %d"         $hi_tap $last $hi_n $hi_ps [expr {$hi_tap-1}]]
set new_lo [expr {$lo_tap+1}]
set new_hi [expr {$hi_tap-1}]
mwr -force $R_DANGER [expr {($new_hi << 16) | $new_lo}]
after 10
set rb [rd $R_DANGER]
say [format "  DANGER 되읽기 = 0x%08X  (lo=%d hi=%d)"         $rb [expr {$rb & 0x1FF}] [expr {($rb>>16) & 0x1FF}]]
if {($rb & 0x1FF) != $new_lo || (($rb>>16)&0x1FF) != $new_hi} {
    say "  FAIL  DANGER 레지스터가 안 먹었다" ; incr fail
} else {
    say "  OK    창에 맞춰 설정됨 (종전 상수는 40 / 220 이었다)"
}

# ================================================================ B. Mode 2 수신
if {!$DO_MODE2} {
say "\n\[B\] Mode 2 검사는 건너뛴다 (인자 0). 외부 고속 비교기가 없을 때 쓴다."
} else {
say "\n\[B\] Mode 2 — 외부 LVDS 비트 신호가 들어오는가"
mwr -force $R_CAPN $CAP_N
say [format "  CAP_N = %d" [rd $R_CAPCNT]]
say [format "  CAP_N 설정값 되읽기 = %d" [rd $R_CAPN]]
mwr -force $R_CTRL [expr {$SRC_EXT | $BIT_START}]

set t0 [clock milliseconds]
set done 0
set last_cnt -1
while {([clock milliseconds]-$t0) < $B_TIMEOUT} {
    set st [rd $R_STATUS]
    set c  [rd $R_CAPCNT]
    if {$c != $last_cnt} {
        say [format "    %5d ms   상태=%-12s  CAP_CNT=%d" \
                [expr {[clock milliseconds]-$t0}] [st_name $st] $c]
        set last_cnt $c
    }
    if {($st >> 4) & 1} { set done 1 ; break }
}
set cap_cnt [rd $R_CAPCNT]
say [format "  최종 CAP_CNT = %d / %d   (DONE=%d)" $cap_cnt $CAP_N $done]

if {$cap_cnt == 0} {
    say ""
    say "  ***** 히트가 한 발도 안 들어왔다. 순서대로 확인할 것:"
    say "        [HIT_INPUT=1 : PMOD 단선 빌드일 때]"
    say "        1) 점퍼가 PMOD JA1 1번 핀(Y11)에 꽂혀 있는가"
    say "           -> Y11 = JA1 1번 이라는 대응은 매뉴얼 기준이고 문서 대조는"
    say "              아직 안 했다. 실크스크린을 확인할 것."
    say "        2) STM32 와 ZedBoard 의 GND 가 연결돼 있는가 (필수)"
    say "        3) STM32 가 실제로 신호를 내보내고 있는가 (스코프로 확인)"
    say "        4) 신호 레벨이 3.3V 인가 (뱅크 13 은 LVCMOS33)"
    say "        [HIT_INPUT=0 : FMC LVDS 빌드일 때]"
    say "        1) ZedBoard 점퍼 J18 이 2.5V 인가 (기본값은 1.8V 다)"
    say "        2) 비교기 보드가 FMC LPC 에 꽂혀 있고 전원이 들어왔는가"
    say "        3) LA27_P/N (E21/D21) 배선이 맞는가"
    incr fail
} else {
    say "  OK    외부 LVDS 히트가 들어온다"

    # ---- 타임스탬프를 읽어 간격을 본다 ----
    # ★ 2026-09-06 : 256 -> 전량. STM32 가 chirp 를 모사하므로 램프를 여러 개
    #   봐야 톱니 모양을 확인할 수 있다. 256 발이면 램프 하나도 못 채울 수 있다.
    #   1024 발이면 AXI 읽기 2048 회 = 약 0.3 초라 부담 없다.
    set n $cap_cnt
    set w [rd_block $R_CAP [expr {$n*2}]]
    set fh [open $OUTC w]
    puts $fh "Index,Timestamp_ps"
    set prev -1
    set gaps {}
    for {set i 0} {$i < $n} {incr i} {
        set lo [lindex $w [expr {$i*2}]]
        set hi [lindex $w [expr {$i*2+1}]]
        set ts [expr {($hi << 32) | $lo}]
        puts $fh "$i,$ts"
        if {$prev >= 0} { lappend gaps [expr {$ts - $prev}] }
        set prev $ts
    }
    close $fh
    say "  -> $OUTC  ($n 발)"

    if {[llength $gaps] > 3} {
        set sorted [lsort -integer $gaps]
        set med [lindex $sorted [expr {[llength $sorted]/2}]]
        set mn  [lindex $sorted 0]
        set mx  [lindex $sorted end]
        say [format "  히트 간격 (ps)  최소 %d / 중앙 %d / 최대 %d" $mn $med $mx]
        if {$med > 0} {
            say [format "  중앙 간격 %.2f us  ->  비트 주파수 %.1f kHz" \
                    [expr {$med/1.0e6}] [expr {1.0e6/($med/1.0e6)/1000.0}]]
        }
        say "  ※ 판정 : 이 간격이 STM32 가 내보낸 주기와 맞아야 진짜 확인이다."
        say "     참고로 9/3 스코프 실측(FMCW 비트 신호)은 34~86 kHz,"
        say "     ILA 히트 간격 중앙값 15.95 us 였다."
        say "  ※ 간격이 들쭉날쭉하면 STM32 지터이거나 히트가 씹힌 것이다."
        say "     최소/최대가 중앙값의 2배 넘게 벌어지면 DROP_CNT 를 함께 볼 것."
        if {$med <= 0} {
            say "  FAIL  간격이 0 이하다 — 타임스탬프가 단조증가하지 않는다"
            incr fail
        }
    }
}
mwr -force $R_CTRL 0x0
}

say [format "\n  DROP_CNT = %d  (버퍼가 찼는데 더 온 히트)" [rd $R_DROP]]

say "\n=================================================="
if {$fail == 0} {
    if {$DO_MODE2} { say " 통과 — Mode 1 회귀 없음, Mode 2 수신 확인" } \
    else           { say " 통과 — Mode 1 회귀 없음 (Mode 2 는 검사 안 함)" }
} else {
    say " 실패 $fail 건"
}
say "=================================================="
close $::LOGFH
disconnect
