# =============================================================================
# xsct_stage3_check.tcl  —  AXI 3단계 실물 검증 (Mode 1 시퀀서 FSM)
# Generated by Claude Code, 2026-09-05
#
#  [무엇을 확인하나]
#  CTRL.START 한 번으로 "RO 켜기 -> 주파수 재기 -> 안정화 -> 누적 -> 완료"가
#  하드웨어에서 자동으로 도는지 본다. 소프트웨어는 시작을 걸고 DONE 을 기다릴 뿐이다.
#
#    1) BUILD 가 0x01806004 인가       — 맵 버전 4 = 이번 빌드가 맞는지
#    2) RO 가 꺼져 있는가 (S_IDLE)     — FSM 이 RO 를 실제로 잡고 있는지
#    3) START -> 상태가 순서대로 도는가
#    4) DONE 후 HIT_CNT == 384탭 합    — ★ 이게 핵심 판정이다
#    5) 데드타임 손실이 얼마인가        — DROP_CNT / (HIT_CNT+DROP_CNT)
#    6) 시작/끝 RO·온도가 남았는가
#
#  [★ 4번이 왜 핵심인가]
#  tdc_histogram 은 히트 하나에 4클럭을 쓴다(IDLE -> RMW_R -> RMW_A -> RMW_W).
#  ts_valid 를 보는 것은 IDLE 한 사이클뿐이라 나머지 3클럭에 온 히트는 버려진다.
#  그래서 도착한 히트를 세면 BRAM 에 들어간 수보다 많아진다.
#  탭 폭이 w[i] = h[i]/H x 5000 ps 이므로 H 가 틀리면 모든 탭 폭이 통째로 틀어지고
#  폭의 합이 5000 ps 가 아니게 된다.
#  HIT_CNT 는 히스토그램이 "받아들였다"고 알린 것만 센다. 따라서 PS 가 읽은
#  384탭의 합과 정확히 같아야 한다. 한 발이라도 다르면 어딘가 틀린 것이다.
#
#  [실행]
#    "C:/Xilinx/Vitis/2024.1/bin/xsct.bat" tcl/xsct_stage3_check.tcl
#
#  [결과를 눈으로 보려면]
#    vivado/stage3_check.log   — 검사 결과 전문
#    vivado/histo_fsm.csv      — FSM 이 모은 384탭
# =============================================================================

set PRJ  C:/Work/FPGA/Project/Source/TDC/vivado/zed_fsm
set OUT  C:/Work/FPGA/Project/Source/TDC/vivado/histo_fsm.csv
set LOG  C:/Work/FPGA/Project/Source/TDC/vivado/stage3_check.log
set BASE 0x43C00000

set ::LOGFH [open $LOG w]
fconfigure $::LOGFH -encoding utf-8
proc say {s} { puts $s ; puts $::LOGFH $s ; flush $::LOGFH }

set R_ID     [expr {$BASE + 0x00}]
set R_BUILD  [expr {$BASE + 0x04}]
set R_CTRL   [expr {$BASE + 0x08}]
set R_STATUS [expr {$BASE + 0x0C}]
set R_ROCNT  [expr {$BASE + 0x14}]
set R_TEMP   [expr {$BASE + 0x18}]
set R_TARGET [expr {$BASE + 0x20}]
set R_HITCNT [expr {$BASE + 0x24}]
set R_SETTLE [expr {$BASE + 0x28}]
set R_ROSTA  [expr {$BASE + 0x2C}]
set R_ROEND  [expr {$BASE + 0x30}]
set R_TEMPSE [expr {$BASE + 0x34}]
set R_DROP   [expr {$BASE + 0x38}]
set R_HISTO  [expr {$BASE + 0x1000}]

set NUM_TAPS   384
set SRC_RO     0x01           ;# CTRL[1:0] = 01
set BIT_START  [expr {1 << 2}]
set TARGET     2000000        ;# 200만 발. 약 1.6 초 (히트율 1.2 MHz 기준)

proc find_one {pat desc} {
    set f [glob -nocomplain $pat]
    if {[llength $f] == 0} { error "$desc 를 못 찾았다: $pat" }
    return [lindex $f 0]
}
set BIT      [find_one $PRJ/zed_fsm.runs/impl_1/*.bit "비트스트림"]
set PS7_INIT [find_one $PRJ/*.gen/sources_1/bd/ps_sys/ip/*ps7_0_0/ps7_init.tcl "ps7_init.tcl"]
say "\[*\] bit      : $BIT"

connect
after 3000
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}
catch {stop}
after 200
source $PS7_INIT
ps7_init
ps7_post_config
targets -set -nocase -filter {name =~ "xc7z020"}
fpga -file $BIT
after 500
targets -set -nocase -filter {name =~ "*Cortex-A9*#0*"}
say "\[*\] 비트스트림 다운로드 완료"

proc rd {addr} { return [expr {"0x[lindex [mrd -force $addr] 1]"}] }
proc rd_block {addr n} {
    set out {}
    foreach t [regexp -all -inline {\S+} [mrd -force $addr $n]] {
        if {[string first ":" $t] < 0} { lappend out [expr {"0x$t"}] }
    }
    return $out
}
set STATE_NAME {S_IDLE S_RO_ENABLE S_MEAS_FREQ S_STABILIZE S_HISTOGRAM S_DONE ? ?}
proc st_name {st} {
    global STATE_NAME
    return [lindex $STATE_NAME [expr {($st >> 8) & 7}]]
}

set fail 0
proc chk {name got exp} {
    global fail
    if {$got == $exp} { say [format "  OK    %-8s = 0x%08X" $name $got] } \
    else { say [format "  FAIL  %-8s = 0x%08X   (기대 0x%08X)" $name $got $exp] ; incr fail }
}

# ---------------------------------------------------------------- 1) 신원
say "\n\[1\] 신원 / 빌드"
chk ID    [rd $R_ID]    0x54444302
chk BUILD [rd $R_BUILD] 0x01806004

# ---------------------------------------------------------------- 2) 정지 상태
say "\n\[2\] 시작 전 — FSM 이 RO 를 잡고 있는가"
set st [rd $R_STATUS]
say [format "  STATUS = 0x%08X   상태=%s  BUSY=%d DONE=%d" \
        $st [st_name $st] [expr {($st>>3)&1}] [expr {($st>>4)&1}]]
if {[expr {($st>>8)&7}] != 0} { say "  FAIL  S_IDLE 이 아니다" ; incr fail }
after 100
set ro_idle [rd $R_ROCNT]
say [format "  RO_CNT = %d   (RO 가 꺼져 있으면 0 근처여야 한다)" $ro_idle]
if {$ro_idle > 1000} {
    say "  FAIL  RO 가 계속 돌고 있다 — FSM 의 ro_en 이 안 먹었다"
    incr fail
} else {
    say "  OK    RO 정지 확인 — 예전에는 전원 인가 후 영영 돌았다"
}

# ---------------------------------------------------------------- 3) 측정 시작
say "\n\[3\] START — 상태 전이"
say [format "  SETTLE_N = %d 클럭 (%.1f us @200MHz)" [rd $R_SETTLE] \
        [expr {[rd $R_SETTLE] / 200.0}]]
mwr -force $R_TARGET $TARGET
say [format "  TARGET_HITS = %d" [rd $R_TARGET]]

mwr -force $R_CTRL [expr {$SRC_RO | $BIT_START}]
set seen {}
set t0 [clock milliseconds]
set elapsed 0
while {$elapsed < 60000} {
    set st [rd $R_STATUS]
    set s  [expr {($st >> 8) & 7}]
    if {[lsearch $seen $s] < 0} {
        lappend seen $s
        say [format "    %6d ms  ->  %s" [expr {[clock milliseconds]-$t0}] [st_name $st]]
    }
    if {($st >> 4) & 1} { break }        ;# DONE
    set elapsed [expr {[clock milliseconds]-$t0}]
}
if {!(([rd $R_STATUS] >> 4) & 1)} { say "  FAIL  60초 안에 DONE 이 안 떴다" ; incr fail }

# 상태가 0->1->2->3->4->5 순으로 지나갔는가
if {$seen != {0 1 2 3 4 5}} {
    say "  주의  관측된 상태 순서 : $seen"
    say "        (폴링이 느려 중간 상태를 놓칠 수 있다. 0 과 5 만 보여도 정상일 수 있음)"
} else {
    say "  OK    6상태를 순서대로 지났다"
}

# ---------------------------------------------------------------- 4) 핵심 판정
say "\n\[4\] ★ HIT_CNT == 384탭 합 인가"
set hit_cnt [rd $R_HITCNT]
set h [rd_block $R_HISTO $NUM_TAPS]
set H 0
set first -1
set last -1
for {set i 0} {$i < [llength $h]} {incr i} {
    set v [lindex $h $i]
    incr H $v
    if {$v > 0} { if {$first < 0} { set first $i } ; set last $i }
}
say [format "  HIT_CNT (하드웨어) = %d" $hit_cnt]
say [format "  384탭 합 (읽어서)  = %d" $H]
say [format "  차이               = %d" [expr {$hit_cnt - $H}]]
say [format "  목표               = %d" $TARGET]
say [format "  히트 있는 탭       = %d ~ %d" $first $last]
if {$hit_cnt != $H} {
    say "  FAIL  일치하지 않는다 — 총 히트 수 H 를 믿을 수 없다"
    incr fail
} else {
    say "  OK    정확히 일치 — w\[i\] = h\[i\]/H x 5000 ps 의 H 를 믿을 수 있다"
}
if {$first != 2} { say "  FAIL  히트 시작 탭이 $first 다 (2 여야 한다)" ; incr fail }

set fh [open $OUT w]
puts $fh "Tap_Index,Hit_Count"
for {set i 0} {$i < [llength $h]} {incr i} { puts $fh "$i,[lindex $h $i]" }
close $fh
say "  -> $OUT"

# ---------------------------------------------------------------- 5) 데드타임
say "\n\[5\] 데드타임 손실 — 지금까지 추정값(약 2.4%)뿐이었다"
set drop [rd $R_DROP]
set arrived [expr {$hit_cnt + $drop}]
say [format "  받아들임 = %d" $hit_cnt]
say [format "  버려짐   = %d" $drop]
if {$arrived > 0} {
    say [format "  손실률   = %.2f %%   (버려짐 / 도착 전체)" \
            [expr {100.0 * $drop / $arrived}]]
}

# ---------------------------------------------------------------- 6) 측정 조건
say "\n\[6\] 측정 조건 — 시작과 끝"
set ro_s [rd $R_ROSTA]
set ro_e [rd $R_ROEND]
set tse  [rd $R_TEMPSE]
set t_s  [expr {$tse & 0xFFFF}]
set t_e  [expr {($tse >> 16) & 0xFFFF}]
# f_RO = RO_CNT x 4 / 10 ms   (ro_divider_cnt[1] = 4분주, 상승엣지만 카운트)
proc f_ro {c} { return [expr {$c * 4 / 0.01 / 1e6}] }
proc t_c  {r} { return [expr {$r / 65536.0 * 503.975 - 273.15}] }
say [format "  RO   시작 %d (%.2f MHz)  ->  끝 %d (%.2f MHz)" \
        $ro_s [f_ro $ro_s] $ro_e [f_ro $ro_e]]
say [format "  온도 시작 %.2f C  ->  끝 %.2f C   (차 %.2f C)" \
        [t_c $t_s] [t_c $t_e] [expr {[t_c $t_e] - [t_c $t_s]}]]
if {$ro_s == 0} { say "  FAIL  RO_AT_START 가 0 이다 — S_MEAS_FREQ 가 안 돌았다" ; incr fail }

# START 내려서 IDLE 복귀
mwr -force $R_CTRL 0x0
after 100
set st [rd $R_STATUS]
say [format "\n  START 해제 후 상태 = %s  (S_IDLE 이어야 한다)" [st_name $st]]
if {[expr {($st>>8)&7}] != 0} { say "  FAIL  IDLE 로 안 돌아왔다" ; incr fail }

say "\n=================================================="
if {$fail == 0} {
    say " 3단계 통과 — Mode 1 이 FSM 으로 자동 동작한다"
} else {
    say " 실패 $fail 건"
}
say "=================================================="
close $::LOGFH
disconnect
