# =============================================================================
# build_zedboard.tcl  —  ZedBoard(XC7Z020-CLG484-1) 프로젝트 생성 스크립트
# Generated by Claude Code, 2026-09-03
#
#  [왜 만들었나]
#    ZedBoard 프로젝트가 회사 PC 에만 있어서 집에서 테스트하려면 §2 절차를 손으로
#    다시 밟아야 했다. IP 4개 설정을 손으로 다시 넣는 것은 실수가 나기 쉽고,
#    특히 clk_wiz_0 의 VCO 가 1000 MHz 가 아니면 Mode 0 의 참 시간축(17.857 ps)이
#    통째로 틀어진다. 스크립트로 만들면 집/회사 어디서 만들어도 같은 프로젝트가 된다.
#
#  [사용법]  Vivado Tcl Console 또는 배치 모드에서
#      cd C:/Work/FPGA/Project/Source/TDC
#      vivado -mode batch -source build_zedboard.tcl -tclargs 1
#    또는 GUI 의 Tcl Console 에서
#      cd C:/Work/FPGA/Project/Source/TDC
#      set argv 1 ; source build_zedboard.tcl
#
#    tclargs 첫 번째 = OPERATION_MODE (0/1/2, 기본 1)
#           두 번째 = 프로젝트 폴더 이름 (기본 vivado/zed_mode<N>)
#
#  [만들어지는 것]
#    - 소스 7개 + XDC 1개를 **참조로** 추가 (복사 안 함 → 이 저장소를 고치면 바로 반영)
#    - IP 4개 : clk_wiz_0 / tdc_calib_rom / ila_0 / xadc_wiz_0
#    - 최상위 tdc_zedboard_top, generic 으로 OPERATION_MODE 전달
#
#  [합성은 자동으로 안 돌린다]  스크립트 끝의 안내를 보고 직접 실행할 것.
#
#  ★ 주의 — IP 프로퍼티 이름은 Vivado 버전에 따라 조금씩 다르다.
#    이 스크립트는 2024.1 기준으로 썼다. set_property 가 실패하면 그 IP 만
#    GUI 로 만들고 나머지는 스크립트를 그대로 쓰면 된다. 실패는 조용히 넘어가지
#    않고 에러로 멈춘다 (그게 안전하다).
# =============================================================================

# ---------------------------------------------------------------- 인자 처리
set OP_MODE 1
if {[info exists argv] && [llength $argv] >= 1} { set OP_MODE [lindex $argv 0] }
if {$OP_MODE < 0 || $OP_MODE > 2} { error "OPERATION_MODE 는 0/1/2 여야 한다: $OP_MODE" }

set SRC_ROOT [file normalize [file dirname [info script]]]
set PRJ_NAME "zed_mode$OP_MODE"
if {[info exists argv] && [llength $argv] >= 2} { set PRJ_NAME [lindex $argv 1] }
set PRJ_DIR  [file join $SRC_ROOT vivado $PRJ_NAME]

# 384탭(96단) 기준. 체인 단수를 바꾸면 python/gen_chain_xdc.py 와 함께 여기도 고칠 것.
set CHAIN_STAGES 96
set NUM_TAPS     [expr {$CHAIN_STAGES * 4}]
set COE_FILE     [file join $SRC_ROOT python tdc_calib_mode0_rom.coe]

puts "=========================================================="
puts " ZedBoard 프로젝트 생성"
puts "   소스 루트     : $SRC_ROOT"
puts "   프로젝트      : $PRJ_DIR"
puts "   OPERATION_MODE: $OP_MODE   (0=DPS스윕 / 1=링오실레이터 / 2=외부LVDS)"
puts "   캐리체인      : ${CHAIN_STAGES}단 = ${NUM_TAPS}탭"
puts "   ROM COE       : $COE_FILE"
puts "=========================================================="

if {![file exists $COE_FILE]} {
    error "COE 가 없다: $COE_FILE\n  python/ 에서 448줄 COE 를 먼저 만들 것."
}
set coe_lines [llength [split [string trim [read [open $COE_FILE r]]] "\n"]]
puts "\[*\] COE 줄 수 : $coe_lines  (헤더 2줄 + 데이터 $NUM_TAPS 줄 = [expr {$NUM_TAPS + 2}] 이어야 함)"

# ---------------------------------------------------------------- 프로젝트
if {[file exists $PRJ_DIR]} {
    error "이미 있다: $PRJ_DIR\n  지우거나 두 번째 인자로 다른 이름을 줄 것."
}
create_project $PRJ_NAME $PRJ_DIR -part xc7z020clg484-1 -force
set_property target_language Verilog [current_project]

# ---------------------------------------------------------------- 소스 추가
# ★ 복사하지 않고 참조로 넣는다. 저장소의 .v 를 고치면 프로젝트에 바로 반영된다.
set VSRC [list \
    [file join $SRC_ROOT RTL tdc_zedboard_top.v]   \
    [file join $SRC_ROOT RTL tdc_test_top.v]       \
    [file join $SRC_ROOT RTL tdc_fmcw_core_co.v]   \
    [file join $SRC_ROOT RTL tdc_timestamp_calc.v] \
    [file join $SRC_ROOT RTL tdc_histogram.v]      \
    [file join $SRC_ROOT RTL phase_shifter.v]      \
    [file join $SRC_ROOT RTL dna_reader.v]         \
]
foreach f $VSRC { if {![file exists $f]} { error "소스 없음: $f" } }
add_files -norecurse -fileset sources_1 $VSRC
set_property is_global_include false [get_files $VSRC]

set XDCF [file join $SRC_ROOT RTL tdc_zedboard.xdc]
if {![file exists $XDCF]} { error "XDC 없음: $XDCF" }
add_files -norecurse -fileset constrs_1 $XDCF

set_property top tdc_zedboard_top [current_fileset]
set_property generic "OPERATION_MODE=$OP_MODE" [current_fileset]
update_compile_order -fileset sources_1
puts "\[*\] 소스 7개 + XDC 1개 추가 완료. 최상위 = tdc_zedboard_top, OPERATION_MODE=$OP_MODE"

# =============================================================================
# IP 1/4 — clk_wiz_0
#   ★ 이 프로젝트에서 제일 중요한 설정이다.
#     phase_shifter.v 의 위상 스텝 = VCO 주기의 1/56 = 17.857 ps 이고,
#     이 값이 Mode 0 의 '참 시간축' 이다. VCO 가 1000 MHz 가 아니면 교정 계산이
#     전부 틀어진다. 100 MHz x 10 / 1 = 1000 MHz, ÷5 = 200 MHz.
#     Vivado 가 다른 M/D 조합을 제안해도 아래 값이 우선이다.
# =============================================================================
create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name clk_wiz_0
set_property -dict [list \
    CONFIG.PRIM_IN_FREQ                {100.000} \
    CONFIG.PRIM_SOURCE                 {Single_ended_clock_capable_pin} \
    CONFIG.PRIMITIVE                   {MMCM} \
    CONFIG.NUM_OUT_CLKS                {2} \
    CONFIG.CLKOUT2_USED                {true} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ  {200.000} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ  {200.000} \
    CONFIG.MMCM_DIVCLK_DIVIDE          {1} \
    CONFIG.MMCM_CLKFBOUT_MULT_F        {10.000} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F       {5.000} \
    CONFIG.MMCM_CLKOUT1_DIVIDE         {5} \
    CONFIG.USE_DYN_PHASE_SHIFT         {true} \
    CONFIG.USE_RESET                   {true} \
    CONFIG.RESET_TYPE                  {ACTIVE_HIGH} \
    CONFIG.USE_LOCKED                  {true} \
] [get_ips clk_wiz_0]

set _m [get_property CONFIG.MMCM_CLKFBOUT_MULT_F [get_ips clk_wiz_0]]
set _d [get_property CONFIG.MMCM_DIVCLK_DIVIDE   [get_ips clk_wiz_0]]
set _vco [expr {100.0 * $_m / $_d}]
puts "\[*\] clk_wiz_0 : M=$_m D=$_d  ->  VCO = $_vco MHz"
if {abs($_vco - 1000.0) > 0.001} {
    error "VCO 가 $_vco MHz 다. 1000 MHz 여야 한다 — phase_shifter.v 의 17.857 ps 가 깨진다."
}
puts "\[*\] 위상 스텝 = 1000/56 = [format %.4f [expr {1000.0/56.0}]] ps  (Mode 0 참 시간축) OK"

# =============================================================================
# IP 2/4 — tdc_calib_rom  (교정 LUT)
#   ★ Latency 2 필수. 아니면 tdc_timestamp_calc.v 의 5단 파이프라인 정렬이 깨진다.
#     BMG 에서 Latency 2 = 프리미티브 출력 레지스터 + 코어 출력 레지스터 둘 다 켬.
#   ★ 깊이 448. 320 으로 두면 탭 320 이상이 전부 ROM 주소 범위 밖이 된다.
# =============================================================================
create_ip -name blk_mem_gen -vendor xilinx.com -library ip -module_name tdc_calib_rom
set_property -dict [list \
    CONFIG.Interface_Type                                {Native} \
    CONFIG.Memory_Type                                   {Single_Port_ROM} \
    CONFIG.Write_Depth_A                                 $NUM_TAPS \
    CONFIG.Read_Width_A                                  {13} \
    CONFIG.Write_Width_A                                 {13} \
    CONFIG.Enable_A                                      {Use_ENA_Pin} \
    CONFIG.Use_RSTA_Pin                                  {false} \
    CONFIG.Register_PortA_Output_of_Memory_Primitives    {true} \
    CONFIG.Register_PortA_Output_of_Memory_Core          {true} \
    CONFIG.Load_Init_File                                {true} \
    CONFIG.Coe_File                                      $COE_FILE \
    CONFIG.Fill_Remaining_Memory_Locations               {true} \
    CONFIG.Remaining_Memory_Locations                    {0} \
] [get_ips tdc_calib_rom]
puts "\[*\] tdc_calib_rom : 깊이 $NUM_TAPS x 13bit, latency 2, COE 로드"
puts "    ※ IP 요약창에서 'Latency = 2' 인지 눈으로 한 번 확인할 것."

# =============================================================================
# IP 3/4 — ila_0  (universal_ila)
#   probe 10개. 폭은 tdc_test_top.v 의 instantiation 과 반드시 같아야 한다.
#   C_EN_STRG_QUAL = 1 : storage qualification(자격저장) 사용. 없으면
#   히스토그램/INL 캡처를 못 한다.
# =============================================================================
create_ip -name ila -vendor xilinx.com -library ip -module_name ila_0
set_property -dict [list \
    CONFIG.C_NUM_OF_PROBES     {10} \
    CONFIG.C_DATA_DEPTH        {8192} \
    CONFIG.C_EN_STRG_QUAL      {1} \
    CONFIG.C_ADV_TRIGGER       {false} \
    CONFIG.C_INPUT_PIPE_STAGES {0} \
    CONFIG.ALL_PROBE_SAME_MU_CNT {2} \
    CONFIG.C_PROBE0_WIDTH  {1}  \
    CONFIG.C_PROBE1_WIDTH  {1}  \
    CONFIG.C_PROBE2_WIDTH  {9}  \
    CONFIG.C_PROBE3_WIDTH  {48} \
    CONFIG.C_PROBE4_WIDTH  {9}  \
    CONFIG.C_PROBE5_WIDTH  {32} \
    CONFIG.C_PROBE6_WIDTH  {32} \
    CONFIG.C_PROBE7_WIDTH  {1}  \
    CONFIG.C_PROBE8_WIDTH  {16} \
    CONFIG.C_PROBE9_WIDTH  {32} \
] [get_ips ila_0]
puts "\[*\] ila_0 : probe 10개(1,1,9,48,9,32,32,1,16,32 = 181비트), depth 8192, 자격저장 ON"

# =============================================================================
# IP 4/4 — xadc_wiz_0  (다이 온도)
#   RTL 이 daddr_in=0x00(on-chip temperature) 을 DRP 로 직접 읽는다.
# =============================================================================
#   ★ 2026-09-03 : 처음에 ENABLE_TEMPERATURE_ALARM / ENABLE_VCCINT_ALARM /
#     ENABLE_VCCAUX_ALARM 을 껐다가 "Cannot find parameter" 로 실패했다.
#     2024.1 의 xadc_wiz 에는 그 이름이 없다(VCCPINT/VCCPAUX/VBRAM/VCCDDRO 만 있음).
#     그리고 나머지 기본값이 이미 우리가 원하는 것이라 건드릴 게 거의 없다 —
#     INTERFACE_SELECTION=ENABLE_DRP, XADC_STARUP_SELECTION=single_channel,
#     SINGLE_CHANNEL_SELECTION=TEMPERATURE 가 전부 기본값이다.
#     DCLK 만 200 MHz(clk_200_fixed)로 맞춘다.
#     alarm_out 계열은 RTL 에서 미연결(.alarm_out())이라 켜져 있어도 무해하다.
create_ip -name xadc_wiz -vendor xilinx.com -library ip -module_name xadc_wiz_0
set_property -dict [list \
    CONFIG.INTERFACE_SELECTION      {ENABLE_DRP} \
    CONFIG.XADC_STARUP_SELECTION    {single_channel} \
    CONFIG.SINGLE_CHANNEL_SELECTION {TEMPERATURE} \
    CONFIG.DCLK_FREQUENCY           {200} \
] [get_ips xadc_wiz_0]
puts "\[*\] xadc_wiz_0 : DRP, 온칩 온도, DCLK 200 MHz"

# ---------------------------------------------------------------- 출력 생성
puts "\[*\] IP 출력물 생성 중 (몇 분 걸린다)..."
generate_target all [get_ips]
catch { config_ip_cache -export [get_ips] }
export_ip_user_files -of_objects [get_ips] -no_script -sync -force -quiet
# ★ 2026-09-03 : create_ip_run 은 컬렉션을 안 받는다 ("A collection of objects is
#   currently not supported"). IP 하나씩 돌려야 OOC 합성 run 이 만들어진다.
foreach ip [get_ips] { create_ip_run $ip }
puts "\[*\] IP [llength [get_ips]] 개 생성 완료 : [get_ips]"

# ---------------------------------------------------------------- 합성 (선택)
# 세 번째 인자가 1 이면 합성~비트스트림까지 이어서 돌리고 결과를 검증한다.
set DO_BUILD 0
if {[info exists argv] && [llength $argv] >= 3} { set DO_BUILD [lindex $argv 2] }

if {$DO_BUILD} {
    puts "\[*\] 합성 시작..."
    launch_runs synth_1 -jobs 8
    wait_on_run synth_1
    if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
        error "합성 실패 — vivado/<프로젝트>/…/runs/synth_1/runme.log 확인"
    }
    open_run synth_1 -name synth_1

    # ---- 체인이 제대로 들어갔는지 (LOC 제약이 먹었는지) ----
    # ★ 2026-09-03 : 필터를 *u_carry4* 로 두면 ILA IP 내부의 u_carry4_inst 91개가
    #   같이 잡혀 203 이 나온다. CARRY_CHAIN 계층을 명시해야 우리 지연선만 센다.
    set n_carry [llength [get_cells -hier -filter {NAME =~ *CARRY_CHAIN*u_carry4*}]]
    set n_taps  [llength [get_cells -hier -filter {NAME =~ *taps_sampled_d1_reg*}]]
    puts "\[검증\] CARRY4 = $n_carry  (기대 $CHAIN_STAGES)"
    puts "\[검증\] taps_sampled_d1_reg = $n_taps  (기대 $NUM_TAPS)"

    # ---- hit 네트에 부하가 붙지 않았는지 ----
    #   CYINIT 말고 다른 것을 구동하면 에지 slew 가 나빠져 진입 트랜지언트가 커진다
    #   (led[2] 사례: 초입 3탭이 정상값의 1.16~1.89배). 반드시 확인할 것.
    catch {
        set hitnet [get_nets -hier -filter {NAME =~ *tdc_hit_in*}]
        puts "\[검증\] hit 네트 fanout = [get_property FLAT_PIN_COUNT [lindex $hitnet 0]]"
    }

    puts "\[*\] 구현 + 비트스트림 시작..."
    launch_runs impl_1 -to_step write_bitstream -jobs 8
    wait_on_run impl_1
    open_run impl_1

    set wns [get_property SLACK [get_timing_paths -delay_type max]]
    set whs [get_property SLACK [get_timing_paths -delay_type min]]
    puts ""
    puts "=========================================================="
    puts " \[타이밍\]  WNS = $wns ns    WHS = $whs ns"
    if {$wns < 0 || $whs < 0} {
        puts " ★ 음수다 — popcount 트리에 파이프라인 단을 추가해야 한다."
    } else {
        puts " OK — 타이밍 통과"
    }
    puts "=========================================================="
    report_timing_summary -delay_type min_max -max_paths 5 \
        -file [file join $PRJ_DIR timing_summary.rpt]
    report_utilization -file [file join $PRJ_DIR utilization.rpt]
    puts "\[*\] 리포트: $PRJ_DIR/timing_summary.rpt , utilization.rpt"
}

# ---------------------------------------------------------------- 마무리 안내
puts ""
puts "=========================================================="
puts " 프로젝트 생성 완료 : $PRJ_DIR"
puts "=========================================================="
puts " 다음 순서:"
puts "   1) launch_runs synth_1 -jobs 8 ; wait_on_run synth_1"
puts "   2) open_run synth_1 ; 아래 확인:"
puts "        puts \"carry4=\[llength \[get_cells -hier -filter {NAME =~ *u_carry4*}\]\]\"    ;# $CHAIN_STAGES"
puts "        puts \"taps  =\[llength \[get_cells -hier -filter {NAME =~ *taps_sampled_d1_reg*}\]\]\" ;# $NUM_TAPS"
puts "        puts \"hit fanout=\[get_property FLAT_PIN_COUNT \[get_nets -hier -filter {NAME =~ *tdc_hit_in*}\]\]\"  ;# 1 이어야 함"
puts "   3) launch_runs impl_1 -to_step write_bitstream -jobs 8 ; wait_on_run impl_1"
puts "   4) open_run impl_1 ; report_timing_summary -delay_type min_max"
puts "        WNS / WHS 가 음수면 알릴 것 (popcount 트리 파이프라인 추가로 해결)"
puts ""
puts " 하드웨어 확인 (J18 점퍼): FMC 뱅크 VCCO 를 2.5V 로 둘 것 (LVDS_25 + DIFF_TERM)"
puts "=========================================================="
