# =============================================================================
# build_zedboard.tcl  —  ZedBoard(XC7Z020-CLG484-1) 프로젝트 생성 스크립트
# Generated by Claude Code, 2026-09-03
#
#  [왜 만들었나]
#    ZedBoard 프로젝트가 회사 PC 에만 있어서 집에서 테스트하려면 §2 절차를 손으로
#    다시 밟아야 했다. IP 4개 설정을 손으로 다시 넣는 것은 실수가 나기 쉽고,
#    특히 clk_wiz_0 의 VCO 가 1000 MHz 가 아니면 Mode 0 의 참 시간축(17.857 ps)이
#    통째로 틀어진다. 스크립트로 만들면 집/회사 어디서 만들어도 같은 프로젝트가 된다.
#
#  [사용법]  Vivado Tcl Console 또는 배치 모드에서
#      cd C:/Work/FPGA/Project/Source/TDC
#      vivado -mode batch -source build_zedboard.tcl -tclargs 1
#    또는 GUI 의 Tcl Console 에서
#      cd C:/Work/FPGA/Project/Source/TDC
#      set argv 1 ; source build_zedboard.tcl
#
#    tclargs 첫 번째 = OPERATION_MODE (0/1/2, 기본 1)
#           두 번째 = 프로젝트 폴더 이름 (기본 vivado/zed_mode<N>)
#           세 번째 = 1 이면 합성~비트스트림까지 이어서 실행
#           네 번째 = HIT_INPUT (0=FMC LVDS 기본 / 1=PMOD 단선 Y11)
#
#  [만들어지는 것]
#    - 소스 7개 + XDC 1개를 **참조로** 추가 (복사 안 함 → 이 저장소를 고치면 바로 반영)
#    - IP 3개 : clk_wiz_0 / tdc_calib_rom / xadc_wiz_0  (★ 2026-09-05 : ila_0 제거)
#    - 최상위 tdc_zedboard_top, generic 으로 OPERATION_MODE 전달
#
#  [합성은 자동으로 안 돌린다]  스크립트 끝의 안내를 보고 직접 실행할 것.
#
#  ★ 주의 — IP 프로퍼티 이름은 Vivado 버전에 따라 조금씩 다르다.
#    이 스크립트는 2024.1 기준으로 썼다. set_property 가 실패하면 그 IP 만
#    GUI 로 만들고 나머지는 스크립트를 그대로 쓰면 된다. 실패는 조용히 넘어가지
#    않고 에러로 멈춘다 (그게 안전하다).
# =============================================================================

# ---------------------------------------------------------------- 인자 처리
set OP_MODE 1
if {[info exists argv] && [llength $argv] >= 1} { set OP_MODE [lindex $argv 0] }
if {$OP_MODE < 0 || $OP_MODE > 2} { error "OPERATION_MODE 는 0/1/2 여야 한다: $OP_MODE" }

set SRC_ROOT [file normalize [file dirname [info script]]]
set PRJ_NAME "zed_mode$OP_MODE"
if {[info exists argv] && [llength $argv] >= 2} { set PRJ_NAME [lindex $argv 1] }
set PRJ_DIR  [file join $SRC_ROOT vivado $PRJ_NAME]

# ★ 2026-09-05 : 히트 입력 선택 (네 번째 인자)
#   0 = FMC LPC LA27_P/N 차동쌍 (TLV3605 LVDS 비교기). 기본값.
#   1 = PMOD 단선 Y11 (STM32 를 점퍼로 물린 임시 신호원)
#   RTL 을 고치지 않고 왕복할 수 있게 파라미터로 뒀다. 상세는
#   tdc_zedboard_top.v 의 HIT_INPUT 파라미터 주석 참조.
set HIT_INPUT 0
if {[info exists argv] && [llength $argv] >= 4} { set HIT_INPUT [lindex $argv 3] }

# 384탭(96단) 기준. 체인 단수를 바꾸면 python/gen_chain_xdc.py 와 함께 여기도 고칠 것.
set CHAIN_STAGES 96
set NUM_TAPS     [expr {$CHAIN_STAGES * 4}]
set COE_FILE     [file join $SRC_ROOT python tdc_calib_mode0_rom.coe]

puts "=========================================================="
puts " ZedBoard 프로젝트 생성"
puts "   소스 루트     : $SRC_ROOT"
puts "   프로젝트      : $PRJ_DIR"
puts "   OPERATION_MODE: $OP_MODE   (0=DPS스윕 / 1=링오실레이터 / 2=외부입력)"
puts "   HIT_INPUT     : $HIT_INPUT   (0=FMC LVDS E21/D21 / 1=PMOD 단선 Y11)"
puts "   캐리체인      : ${CHAIN_STAGES}단 = ${NUM_TAPS}탭"
puts "   ROM COE       : $COE_FILE"
puts "=========================================================="

if {![file exists $COE_FILE]} {
    error "COE 가 없다: $COE_FILE\n  python/ 에서 448줄 COE 를 먼저 만들 것."
}
set coe_lines [llength [split [string trim [read [open $COE_FILE r]]] "\n"]]
puts "\[*\] COE 줄 수 : $coe_lines  (헤더 2줄 + 데이터 $NUM_TAPS 줄 = [expr {$NUM_TAPS + 2}] 이어야 함)"

# ---------------------------------------------------------------- 프로젝트
if {[file exists $PRJ_DIR]} {
    error "이미 있다: $PRJ_DIR\n  지우거나 두 번째 인자로 다른 이름을 줄 것."
}
create_project $PRJ_NAME $PRJ_DIR -part xc7z020clg484-1 -force
set_property target_language Verilog [current_project]

# ---------------------------------------------------------------- 소스 추가
# ★ 복사하지 않고 참조로 넣는다. 저장소의 .v 를 고치면 프로젝트에 바로 반영된다.
set VSRC [list \
    [file join $SRC_ROOT RTL tdc_zedboard_top.v]   \
    [file join $SRC_ROOT RTL tdc_test_top.v]       \
    [file join $SRC_ROOT RTL tdc_fmcw_core_co.v]   \
    [file join $SRC_ROOT RTL tdc_timestamp_calc.v] \
    [file join $SRC_ROOT RTL tdc_histogram.v]      \
    [file join $SRC_ROOT RTL phase_shifter.v]      \
    [file join $SRC_ROOT RTL dna_reader.v]         \
    [file join $SRC_ROOT RTL tdc_axi_regs.v]       \
    [file join $SRC_ROOT RTL tdc_seq.v]            \
    [file join $SRC_ROOT RTL tdc_capture.v]        \
]
foreach f $VSRC { if {![file exists $f]} { error "소스 없음: $f" } }
add_files -norecurse -fileset sources_1 $VSRC
set_property is_global_include false [get_files $VSRC]

set XDCF [file join $SRC_ROOT RTL tdc_zedboard.xdc]
if {![file exists $XDCF]} { error "XDC 없음: $XDCF" }
add_files -norecurse -fileset constrs_1 $XDCF

# ---------------------------------------------------------------- 블록 디자인
#  ★ 2026-09-04 추가 : PS7 + proc_sys_reset + AXI 인터커넥트.
#    TDC 의 클럭(FCLK_CLK0)도 여기서 나온다. 상세는 tcl/bd_ps_sys.tcl 참조.
source [file join $SRC_ROOT tcl bd_ps_sys.tcl]
make_wrapper -files [get_files ps_sys.bd] -top
add_files -norecurse [file join $PRJ_DIR ${PRJ_NAME}.gen sources_1 bd ps_sys hdl ps_sys_wrapper.v]
puts "\[*\] 블록 디자인 ps_sys 생성 + 래퍼 추가"

set_property top tdc_zedboard_top [current_fileset]
set_property generic "OPERATION_MODE=$OP_MODE HIT_INPUT=$HIT_INPUT" [current_fileset]
update_compile_order -fileset sources_1
puts "\[*\] 소스 7개 + XDC 1개 추가 완료. 최상위 = tdc_zedboard_top, OPERATION_MODE=$OP_MODE"

# =============================================================================
# IP 1/4 — clk_wiz_0
#   ★ 이 프로젝트에서 제일 중요한 설정이다.
#     phase_shifter.v 의 위상 스텝 = VCO 주기의 1/56 = 17.857 ps 이고,
#     이 값이 Mode 0 의 '참 시간축' 이다. VCO 가 1000 MHz 가 아니면 교정 계산이
#     전부 틀어진다. 100 MHz x 10 / 1 = 1000 MHz, ÷5 = 200 MHz.
#     Vivado 가 다른 M/D 조합을 제안해도 아래 값이 우선이다.
# =============================================================================
#   ★ 2026-09-04 : PRIM_SOURCE 가 Global_buffer 다. 입력이 Y9 외부 핀에서
#     PS 의 FCLK_CLK0(내부 클럭)으로 바뀌었기 때문이다. 핀용 설정을 그대로
#     두면 쓸데없는 IBUF 가 끼어든다.
create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name clk_wiz_0
set_property -dict [list \
    CONFIG.PRIM_IN_FREQ                {100.000} \
    CONFIG.PRIM_SOURCE                 {Global_buffer} \
    CONFIG.PRIMITIVE                   {MMCM} \
    CONFIG.NUM_OUT_CLKS                {2} \
    CONFIG.CLKOUT2_USED                {true} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ  {200.000} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ  {200.000} \
    CONFIG.MMCM_DIVCLK_DIVIDE          {1} \
    CONFIG.MMCM_CLKFBOUT_MULT_F        {10.000} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F       {5.000} \
    CONFIG.MMCM_CLKOUT1_DIVIDE         {5} \
    CONFIG.USE_DYN_PHASE_SHIFT         {true} \
    CONFIG.USE_RESET                   {true} \
    CONFIG.RESET_TYPE                  {ACTIVE_HIGH} \
    CONFIG.USE_LOCKED                  {true} \
] [get_ips clk_wiz_0]

set _m [get_property CONFIG.MMCM_CLKFBOUT_MULT_F [get_ips clk_wiz_0]]
set _d [get_property CONFIG.MMCM_DIVCLK_DIVIDE   [get_ips clk_wiz_0]]
set _vco [expr {100.0 * $_m / $_d}]
puts "\[*\] clk_wiz_0 : M=$_m D=$_d  ->  VCO = $_vco MHz"
if {abs($_vco - 1000.0) > 0.001} {
    error "VCO 가 $_vco MHz 다. 1000 MHz 여야 한다 — phase_shifter.v 의 17.857 ps 가 깨진다."
}
puts "\[*\] 위상 스텝 = 1000/56 = [format %.4f [expr {1000.0/56.0}]] ps  (Mode 0 참 시간축) OK"

# =============================================================================
# IP 2/4 — tdc_calib_rom  (교정 LUT)
#   ★ Latency 2 필수. 아니면 tdc_timestamp_calc.v 의 5단 파이프라인 정렬이 깨진다.
#     BMG 에서 Latency 2 = 프리미티브 출력 레지스터 + 코어 출력 레지스터 둘 다 켬.
#   ★ 깊이 448. 320 으로 두면 탭 320 이상이 전부 ROM 주소 범위 밖이 된다.
# =============================================================================
create_ip -name blk_mem_gen -vendor xilinx.com -library ip -module_name tdc_calib_rom
set_property -dict [list \
    CONFIG.Interface_Type                                {Native} \
    CONFIG.Memory_Type                                   {Single_Port_ROM} \
    CONFIG.Write_Depth_A                                 $NUM_TAPS \
    CONFIG.Read_Width_A                                  {13} \
    CONFIG.Write_Width_A                                 {13} \
    CONFIG.Enable_A                                      {Use_ENA_Pin} \
    CONFIG.Use_RSTA_Pin                                  {false} \
    CONFIG.Register_PortA_Output_of_Memory_Primitives    {true} \
    CONFIG.Register_PortA_Output_of_Memory_Core          {true} \
    CONFIG.Load_Init_File                                {true} \
    CONFIG.Coe_File                                      $COE_FILE \
    CONFIG.Fill_Remaining_Memory_Locations               {true} \
    CONFIG.Remaining_Memory_Locations                    {0} \
] [get_ips tdc_calib_rom]
puts "\[*\] tdc_calib_rom : 깊이 $NUM_TAPS x 13bit, latency 2, COE 로드"
puts "    ※ IP 요약창에서 'Latency = 2' 인지 눈으로 한 번 확인할 것."

# =============================================================================
# =============================================================================
# ★ 2026-09-05 — ila_0 (universal_ila) 제거
#   [무엇이 있었나] probe 10개(1,1,9,48,9,32,32,1,16,32 = 181비트), depth 8192,
#     자격저장(C_EN_STRG_QUAL=1) 켠 ILA IP.
#   [왜 뺐나] AXI 2단계에서 히스토그램을 0x43C0_1000+탭*4 로, RO 카운트·온도·DNA 를
#     레지스터로 읽게 되어 ILA 로만 볼 수 있던 값이 남지 않았다. 또 ILA 를 쓰려면
#     Vivado Hardware Manager 를 띄우고 사람이 BTNU 를 눌러야 했는데, Vitis 에서
#     레지스터만으로 측정을 끝내는 것이 목표다.
#     덤으로 2026-09-04 빌드의 타이밍 임계경로가 ILA IP 안에 있었으니 여유가 는다.
#   [되살리려면] 여기 create_ip 블록과 tdc_test_top.v §7 의 인스턴스를 함께 복원할 것.
#     둘 중 하나만 되살리면 포트 폭이 어긋나 합성이 깨진다.
#     지운 설정은 git 이력(커밋 dd02425 이전)에 그대로 있다.
# =============================================================================

# =============================================================================
# IP 4/4 — xadc_wiz_0  (다이 온도)
#   RTL 이 daddr_in=0x00(on-chip temperature) 을 DRP 로 직접 읽는다.
# =============================================================================
#   ★ 2026-09-03 : 처음에 ENABLE_TEMPERATURE_ALARM / ENABLE_VCCINT_ALARM /
#     ENABLE_VCCAUX_ALARM 을 껐다가 "Cannot find parameter" 로 실패했다.
#     2024.1 의 xadc_wiz 에는 그 이름이 없다(VCCPINT/VCCPAUX/VBRAM/VCCDDRO 만 있음).
#     그리고 나머지 기본값이 이미 우리가 원하는 것이라 건드릴 게 거의 없다 —
#     INTERFACE_SELECTION=ENABLE_DRP, XADC_STARUP_SELECTION=single_channel,
#     SINGLE_CHANNEL_SELECTION=TEMPERATURE 가 전부 기본값이다.
#     DCLK 만 200 MHz(clk_200_fixed)로 맞춘다.
#     alarm_out 계열은 RTL 에서 미연결(.alarm_out())이라 켜져 있어도 무해하다.
create_ip -name xadc_wiz -vendor xilinx.com -library ip -module_name xadc_wiz_0
set_property -dict [list \
    CONFIG.INTERFACE_SELECTION      {ENABLE_DRP} \
    CONFIG.XADC_STARUP_SELECTION    {single_channel} \
    CONFIG.SINGLE_CHANNEL_SELECTION {TEMPERATURE} \
    CONFIG.DCLK_FREQUENCY           {200} \
] [get_ips xadc_wiz_0]
puts "\[*\] xadc_wiz_0 : DRP, 온칩 온도, DCLK 200 MHz"

# ---------------------------------------------------------------- 출력 생성
puts "\[*\] IP 출력물 생성 중 (몇 분 걸린다)..."
# ★ 2026-09-04 : get_ips 는 블록 디자인 안에 들어 있는 IP 까지 전부 잡는다.
#   그걸 개별로 generate 하면 "Nested sub-design can only be generated by its
#   parent sub-design" 에러가 난다. 우리가 직접 만든 4개만 대상으로 하고,
#   블록 디자인은 .bd 파일 단위로 따로 생성한다.
set MY_IPS [get_ips clk_wiz_0 tdc_calib_rom xadc_wiz_0]   ;# ★ 2026-09-05 : ila_0 제거
generate_target all $MY_IPS
catch { config_ip_cache -export $MY_IPS }
export_ip_user_files -of_objects $MY_IPS -no_script -sync -force -quiet
# create_ip_run 은 컬렉션을 안 받는다 ("A collection of objects is currently not
# supported"). IP 하나씩 돌려야 OOC 합성 run 이 만들어진다.
foreach ip $MY_IPS { create_ip_run $ip }

# 블록 디자인은 통째로 생성한다 (내부 IP 는 BD 가 알아서 만든다)
generate_target all [get_files ps_sys.bd]
export_ip_user_files -of_objects [get_files ps_sys.bd] -no_script -sync -force -quiet
puts "\[*\] IP [llength [get_ips]] 개 생성 완료 : [get_ips]"

# ---------------------------------------------------------------- 합성 (선택)
# 세 번째 인자가 1 이면 합성~비트스트림까지 이어서 돌리고 결과를 검증한다.
set DO_BUILD 0
if {[info exists argv] && [llength $argv] >= 3} { set DO_BUILD [lindex $argv 2] }

if {$DO_BUILD} {
    puts "\[*\] 합성 시작..."
    launch_runs synth_1 -jobs 8
    wait_on_run synth_1
    if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
        error "합성 실패 — vivado/<프로젝트>/…/runs/synth_1/runme.log 확인"
    }
    open_run synth_1 -name synth_1

    # ---- 체인이 제대로 들어갔는지 (LOC 제약이 먹었는지) ----
    # ★ 2026-09-03 : 필터를 *u_carry4* 로 두면 ILA IP 내부의 u_carry4_inst 91개가
    #   같이 잡혀 203 이 나온다. CARRY_CHAIN 계층을 명시해야 우리 지연선만 센다.
    set n_carry [llength [get_cells -hier -filter {NAME =~ *CARRY_CHAIN*u_carry4*}]]
    set n_taps  [llength [get_cells -hier -filter {NAME =~ *taps_sampled_d1_reg*}]]
    puts "\[검증\] CARRY4 = $n_carry  (기대 $CHAIN_STAGES)"
    puts "\[검증\] taps_sampled_d1_reg = $n_taps  (기대 $NUM_TAPS)"

    # ---- hit 네트에 부하가 붙지 않았는지 ----
    #   CYINIT 말고 다른 것을 구동하면 에지 slew 가 나빠져 진입 트랜지언트가 커진다
    #   (led[2] 사례: 초입 3탭이 정상값의 1.16~1.89배). 반드시 확인할 것.
    catch {
        set hitnet [get_nets -hier -filter {NAME =~ *tdc_hit_in*}]
        puts "\[검증\] hit 네트 fanout = [get_property FLAT_PIN_COUNT [lindex $hitnet 0]]"
    }

    # ★ 2026-09-05 : 구현 전략을 기본값에서 Performance_ExplorePostRoutePhysOpt 로 바꾼다.
    #   [무엇이 문제였나] PS7 + AXI 를 넣은 뒤 기본 전략으로는 hold 가 깨진다.
    #     WHS = -0.045 ns, 위반 경로 captured_c0_stg2 -> stg3 (같은 clk_200_fixed 도메인).
    #     원인은 지연이 아니라 스큐다 : 캐리체인 pblock 을 384탭 때문에 Y140 까지 넓히면서
    #     체인 양끝의 클럭 도착 시각 차이(스큐 0.298 ns)가 데이터 지연(0.266 ns)을 넘어섰다.
    #   [왜 이 전략인가] 이 전략은 route 뒤에 post_route_phys_opt_design 단계를 켠다
    #     (EnableStepBool=1). 라우팅이 끝난 실제 지연을 보고 레지스터를 재배치·복제해
    #     스큐를 줄이므로, 배치 단계의 추정치로만 판단하는 기본 전략이 못 잡는 hold 를 잡는다.
    #   [결과] 2026-09-05 zed_axi 빌드 : WNS +0.089 / WHS +0.034 ns, 비트스트림 정상 생성.
    #   [대가] 구현 시간이 늘어난다(단계가 하나 더 붙는다). 타이밍이 필수라 감수한다.
    set_property strategy Performance_ExplorePostRoutePhysOpt [get_runs impl_1]
    puts "\[*\] 구현 전략 : [get_property strategy [get_runs impl_1]]"

    puts "\[*\] 구현 + 비트스트림 시작..."
    launch_runs impl_1 -to_step write_bitstream -jobs 8
    wait_on_run impl_1
    open_run impl_1

    set wns [get_property SLACK [get_timing_paths -delay_type max]]
    set whs [get_property SLACK [get_timing_paths -delay_type min]]
    puts ""
    puts "=========================================================="
    puts " \[타이밍\]  WNS = $wns ns    WHS = $whs ns"
    # ★ 2026-09-05 : setup 과 hold 는 처방이 다르다. 예전엔 둘 다 "파이프라인 추가"로
    #   안내했는데, hold 위반에 파이프라인을 넣으면 오히려 악화된다(경로가 더 짧아진다).
    if {$wns < 0} {
        puts " ★ WNS 음수 (setup) — 경로가 5 ns 안에 못 들어온다."
        puts "    popcount 트리에 파이프라인 단을 추가하거나, 비교 로직을 뒤 단으로 옮긴다."
    }
    if {$whs < 0} {
        puts " ★ WHS 음수 (hold) — 데이터가 클럭보다 먼저 도착한다. 스큐 문제다."
        puts "    구현 전략이 Performance_ExplorePostRoutePhysOpt 인지 먼저 확인할 것."
    }
    if {$wns >= 0 && $whs >= 0} {
        puts " OK — 타이밍 통과"
    }
    puts "=========================================================="
    report_timing_summary -delay_type min_max -max_paths 5 \
        -file [file join $PRJ_DIR timing_summary.rpt]
    report_utilization -file [file join $PRJ_DIR utilization.rpt]
    puts "\[*\] 리포트: $PRJ_DIR/timing_summary.rpt , utilization.rpt"
}

# ---------------------------------------------------------------- 마무리 안내
puts ""
puts "=========================================================="
puts " 프로젝트 생성 완료 : $PRJ_DIR"
puts "=========================================================="
puts " 다음 순서:"
puts "   1) launch_runs synth_1 -jobs 8 ; wait_on_run synth_1"
puts "   2) open_run synth_1 ; 아래 확인:"
puts "        puts \"carry4=\[llength \[get_cells -hier -filter {NAME =~ *u_carry4*}\]\]\"    ;# $CHAIN_STAGES"
puts "        puts \"taps  =\[llength \[get_cells -hier -filter {NAME =~ *taps_sampled_d1_reg*}\]\]\" ;# $NUM_TAPS"
puts "        puts \"hit fanout=\[get_property FLAT_PIN_COUNT \[get_nets -hier -filter {NAME =~ *tdc_hit_in*}\]\]\"  ;# 1 이어야 함"
puts "   3) set_property strategy Performance_ExplorePostRoutePhysOpt \[get_runs impl_1\]"
puts "        ★ 2026-09-05 : 기본 전략이면 hold 가 깨진다 (WHS -0.045 ns). 반드시 먼저 걸 것."
puts "      launch_runs impl_1 -to_step write_bitstream -jobs 8 ; wait_on_run impl_1"
puts "   4) open_run impl_1 ; report_timing_summary -delay_type min_max"
puts "        WNS 음수 = setup, popcount 파이프라인 추가로 해결"
puts "        WHS 음수 = hold(스큐), 위 전략이 걸렸는지 확인 — 파이프라인은 역효과"
puts ""
puts " 하드웨어 확인 (J18 점퍼): FMC 뱅크 VCCO 를 2.5V 로 둘 것 (LVDS_25 + DIFF_TERM)"
puts "=========================================================="
