import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

FOLDER_PATH = "./"          # 데이터 저장 폴더
FILE_PATTERN = "iladata_*.csv" 
T_CLK_PS = 5000.0           # 200 MHz 주클럭의 주기 (5000 ps)
NUM_TAPS = 320              # 총 탭 수

def run_calibration_flow():
    # 1. 파일 자동 탐색 및 통합
    search_path = os.path.join(FOLDER_PATH, FILE_PATTERN)
    file_list = sorted(glob.glob(search_path))
    if not file_list:
        raise FileNotFoundError("대상 CSV 파일을 찾을 수 없습니다.")
        
    df_list = []
    for file in file_list:
        # 두 번째 줄의 Radix 라인 스킵
        temp_df = pd.read_csv(file, skiprows=[1])
        temp_df.columns = [col.split('[')[0].strip() for col in temp_df.columns]
        # ts_coarse HEX를 int로 변환
        temp_df['ts_coarse'] = temp_df['ts_coarse'].apply(
            lambda x: int(str(x).strip(), 16) if pd.notnull(x) else np.nan
        )
        df_list.append(temp_df)
        
    combined_df = pd.concat(df_list, ignore_index=True)
    fine_data = combined_df['ts_fine_idx'].dropna().astype(int).values
    total_samples = len(fine_data)
    
    # 2. 코드 밀도 기반 캘리브레이션 알고리즘 계산
    hist, _ = np.histogram(fine_data, bins=range(NUM_TAPS + 1))
    tap_widths_ps = T_CLK_PS * (hist / total_samples) # W(i) = T_CLK * (H(i)/N_total)
    calibration_lut = np.cumsum(tap_widths_ps)       # Cumulative_Delay_ps = Sum(W(i))
    
    # 3. 보정표 CSV 내보내기 (소프트웨어/파이썬 분석용)
    lut_df = pd.DataFrame({
        'Fine_Index': range(NUM_TAPS),
        'Hit_Count': hist,
        'Tap_Width_ps': tap_widths_ps,
        'Cumulative_Delay_ps': calibration_lut
    })
    lut_df.to_csv("tdc_calibration_lut.csv", index=False)
    print("-> [저장 완료] 소프트웨어 분석용 CSV: tdc_calibration_lut.csv")
    
    # =====================================================================
    # [추가된 부분] 4. Vivado ROM IP 적용을 위한 .coe 파일 생성 (하드웨어용)
    # =====================================================================
    # FPGA Block RAM에 넣기 위해 소수점을 반올림하여 정수(int)로 변환
    lut_integers = np.round(calibration_lut).astype(int)
    
    coe_filename = "tdc_lut.coe"
    with open(coe_filename, "w") as f:
        f.write("; ================================================\n")
        f.write("; TDC Calibration LUT generated by Python Script\n")
        f.write(f"; Total Taps: {NUM_TAPS}, Clock: {T_CLK_PS}ps\n")
        f.write("; ================================================\n")
        f.write("memory_initialization_radix=10;\n")  # 10진수 포맷 지정
        f.write("memory_initialization_vector=\n")
        
        # 데이터를 쉼표(,)로 구분하고 마지막은 세미콜론(;)으로 마무리
        for i, val in enumerate(lut_integers):
            if i == len(lut_integers) - 1:
                f.write(f"{val};\n")
            else:
                f.write(f"{val},\n")
    print(f"-> [저장 완료] Vivado 하드웨어 ROM용: {coe_filename}")
    # =====================================================================

    # 5. 분석 리포트 그래프 시각화 및 PNG 파일 저장
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    ax1.bar(range(NUM_TAPS), hist, color='royalblue', width=1.0)
    ax1.set_title("Fine Index Frequency (Code Density Test)")
    ax1.set_xlabel("Fine Index"), ax1.set_ylabel("Occurrence Count")
    ax1.grid(True, linestyle='--', alpha=0.5)
    
    ax2.plot(range(NUM_TAPS), calibration_lut, color='crimson', linewidth=2.5)
    ax2.set_title("Cumulative Delay Curve (TDC Calibration LUT)")
    ax2.set_xlabel("Fine Index"), ax2.set_ylabel("Calibrated Time (ps)")
    ax2.axhline(y=T_CLK_PS, color='darkgreen', linestyle=':', label=f"Clock Period ({T_CLK_PS} ps)")
    ax2.legend(loc='lower right'), ax2.grid(True, linestyle='--', alpha=0.5)
    
    plt.tight_layout()
    plt.savefig("tdc_analysis_results.png", dpi=300)
    print("-> [저장 완료] 분석 결과 이미지: tdc_analysis_results.png")

if __name__ == "__main__":
    run_calibration_flow()