import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# =====================================================================
# 설정 파라미터
# =====================================================================
FOLDER_PATH = "./"              # ILA CSV 데이터가 있는 폴더 경로
FILE_PATTERN = "iladata_*.csv"  # ILA 파일 이름 패턴
T_CLK_PS = 5000.0               # 200 MHz 주클럭의 주기 (5000 ps)
NUM_TAPS = 320                  # TDC 총 탭 수

def run_calibration_flow():
    print("-> [진행] ILA CSV 파일 탐색 시작...")
    search_path = os.path.join(FOLDER_PATH, FILE_PATTERN)
    file_list = sorted(glob.glob(search_path))
    if not file_list:
        print("[에러] 대상 CSV 파일을 찾을 수 없습니다. (iladata_1.csv 등이 폴더에 있는지 확인)")
        return
        
    df_list = []
    fine_col_name = ""
    
    # 1. 파일 읽기 및 스마트 이름 탐색
    for file in file_list:
        # 두 번째 줄의 Radix 라인 스킵
        temp_df = pd.read_csv(file, skiprows=[1])
        # 헤더의 [31:0] 같은 비트 표기 제거
        temp_df.columns = [col.split('[')[0].strip() for col in temp_df.columns]
        
        # 'ts_coarse'나 'ts_fine_idx'라는 단어가 포함된 열을 똑똑하게 자동으로 찾음 (_d5 등이 붙어있어도 OK)
        try:
            coarse_col = [col for col in temp_df.columns if 'ts_coarse' in col][0]
            fine_col = [col for col in temp_df.columns if 'ts_fine_idx' in col][0]
            fine_col_name = fine_col # 통합 후 사용하기 위해 기억해둠
        except IndexError:
            print(f"[에러] {file} 파일에 'ts_coarse' 또는 'ts_fine_idx' 열이 없습니다. 건너뜁니다.")
            continue
            
        # HEX 데이터를 Int(십진수)로 변환
        temp_df[coarse_col] = temp_df[coarse_col].apply(
            lambda x: int(str(x).strip(), 16) if pd.notnull(x) else np.nan
        )
        df_list.append(temp_df)
        
    if not df_list:
        print("[에러] 유효한 데이터를 추출하지 못했습니다.")
        return
        
    combined_df = pd.concat(df_list, ignore_index=True)
    
    # 스마트 탐색으로 찾은 fine_idx 열 데이터를 넘파이 배열로 추출
    fine_data = combined_df[fine_col_name].dropna().astype(int).values
    total_samples = len(fine_data)
    print(f"-> [완료] 총 {total_samples}개의 랜덤 샘플 데이터를 병합했습니다.")
    
    # =====================================================================
    # 2. 통계 기반 캘리브레이션 (Code Density Test) 및 DNL/INL 계산
    # =====================================================================
    print("-> [진행] 캘리브레이션 알고리즘 및 DNL/INL 연산 중...")
    hist, _ = np.histogram(fine_data, bins=range(NUM_TAPS + 1))
    tap_widths_ps = T_CLK_PS * (hist / total_samples)
    calibration_lut = np.cumsum(tap_widths_ps)       
    
    LSB_ideal = T_CLK_PS / NUM_TAPS                  # 이상적인 1탭의 너비 (15.625 ps)
    dnl = (tap_widths_ps - LSB_ideal) / LSB_ideal    
    inl = np.cumsum(dnl)                             
    
    # =====================================================================
    # 3. 분석 결과 CSV 내보내기 (엑셀 켜져있으면 방어)
    # =====================================================================
    lut_df = pd.DataFrame({
        'Fine_Index': range(NUM_TAPS),
        'Hit_Count': hist,
        'Tap_Width_ps': tap_widths_ps,
        'Cumulative_Delay_ps': calibration_lut,
        'DNL_LSB': dnl,
        'INL_LSB': inl
    })
    
    try:
        lut_df.to_csv("tdc_calibration_lut.csv", index=False)
        print("-> [저장 완료] 소프트웨어 분석용 CSV: tdc_calibration_lut.csv")
    except PermissionError:
        print("\n🚨 [경고] 'tdc_calibration_lut.csv' 파일이 열려있습니다! 엑셀을 닫고 다시 실행해주세요.\n")
        return
    
    # =====================================================================
    # 4. Vivado Block ROM 적용용 .coe 파일 생성
    # =====================================================================
    lut_integers = np.round(calibration_lut).astype(int)
    coe_filename = "tdc_lut.coe"
    
    try:
        with open(coe_filename, "w") as f:
            f.write("; ================================================\n")
            f.write("; TDC Calibration LUT generated by Python Script\n")
            f.write(f"; Total Taps: {NUM_TAPS}, Clock: {T_CLK_PS}ps\n")
            f.write("; ================================================\n")
            f.write("memory_initialization_radix=10;\n")
            f.write("memory_initialization_vector=\n")
            for i, val in enumerate(lut_integers):
                if i == len(lut_integers) - 1:
                    f.write(f"{val};\n")
                else:
                    f.write(f"{val},\n")
        print(f"-> [저장 완료] Vivado 하드웨어 ROM용 COE: {coe_filename}")
    except PermissionError:
        print("\n🚨 [경고] 'tdc_lut.coe' 파일이 열려있어 덮어쓸 수 없습니다.\n")
        return

    # =====================================================================
    # 5. 종합 분석 리포트 그래프 시각화
    # =====================================================================
    fig, axs = plt.subplots(2, 2, figsize=(16, 10))
    
    axs[0, 0].bar(range(NUM_TAPS), hist, color='royalblue', width=1.0)
    axs[0, 0].set_title("Fine Index Frequency (Code Density Test)", fontsize=13, fontweight='bold')
    axs[0, 0].set_xlabel("Fine Index"), axs[0, 0].set_ylabel("Occurrence Count")
    axs[0, 0].grid(True, linestyle='--', alpha=0.5)
    
    axs[0, 1].plot(range(NUM_TAPS), calibration_lut, color='crimson', linewidth=2.5)
    axs[0, 1].set_title("Cumulative Delay Curve (TDC LUT)", fontsize=13, fontweight='bold')
    axs[0, 1].set_xlabel("Fine Index"), axs[0, 1].set_ylabel("Calibrated Time (ps)")
    axs[0, 1].axhline(y=T_CLK_PS, color='darkgreen', linestyle=':', label=f"Clock Period ({T_CLK_PS} ps)")
    axs[0, 1].legend(loc='lower right')
    axs[0, 1].grid(True, linestyle='--', alpha=0.5)

    axs[1, 0].plot(range(NUM_TAPS), dnl, color='purple', linewidth=1.5)
    axs[1, 0].set_title("DNL (Differential Non-Linearity)", fontsize=13, fontweight='bold')
    axs[1, 0].set_xlabel("Fine Index"), axs[1, 0].set_ylabel("DNL (LSB)")
    axs[1, 0].axhline(y=0, color='black', linewidth=1)
    axs[1, 0].axhline(y=-1, color='red', linestyle=':', label='Missing Code (-1 LSB)')
    axs[1, 0].legend()
    axs[1, 0].grid(True, linestyle='--', alpha=0.5)

    axs[1, 1].plot(range(NUM_TAPS), inl, color='darkorange', linewidth=1.5)
    axs[1, 1].set_title("INL (Integral Non-Linearity)", fontsize=13, fontweight='bold')
    axs[1, 1].set_xlabel("Fine Index"), axs[1, 1].set_ylabel("INL (LSB)")
    axs[1, 1].axhline(y=0, color='black', linewidth=1)
    axs[1, 1].grid(True, linestyle='--', alpha=0.5)
    
    plt.tight_layout()
    try:
        plt.savefig("tdc_comprehensive_analysis.png", dpi=300)
        print("-> [저장 완료] 종합 분석 결과 이미지: tdc_comprehensive_analysis.png\n")
    except PermissionError:
        print("-> [경고] 이미지를 저장할 수 없습니다 (파일이 열려있음).\n")

if __name__ == "__main__":
    run_calibration_flow()