import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# =====================================================================
# 설정 파라미터
# =====================================================================
FOLDER_PATH = "./"              # ILA CSV 데이터가 있는 폴더 경로
FILE_PATTERN = "iladata_*.csv"  # ILA 파일 이름 패턴
T_CLK_PS = 5000.0               # 200 MHz 주클럭의 주기 (5000 ps)
NUM_TAPS = 320                  # TDC 총 탭 수

def run_calibration_flow():
    # =====================================================================
    # 1. 파일 자동 탐색 및 데이터 통합
    # =====================================================================
    search_path = os.path.join(FOLDER_PATH, FILE_PATTERN)
    file_list = sorted(glob.glob(search_path))
    if not file_list:
        raise FileNotFoundError("대상 CSV 파일을 찾을 수 없습니다. 경로를 확인하세요.")
        
    df_list = []
    for file in file_list:
        # 두 번째 줄의 Radix 라인 스킵
        temp_df = pd.read_csv(file, skiprows=[1])
        temp_df.columns = [col.split('[')[0].strip() for col in temp_df.columns]
        # ts_coarse HEX를 int로 변환
        temp_df['ts_coarse'] = temp_df['ts_coarse'].apply(
            lambda x: int(str(x).strip(), 16) if pd.notnull(x) else np.nan
        )
        df_list.append(temp_df)
        
    combined_df = pd.concat(df_list, ignore_index=True)
    fine_data = combined_df['ts_fine_idx'].dropna().astype(int).values
    total_samples = len(fine_data)
    
    # =====================================================================
    # 2. 통계 기반 캘리브레이션 (Code Density Test) 및 DNL/INL 계산
    # =====================================================================
    # 빈도수(Hit Count), 탭 폭(Tap Width), 누적 지연(Cumulative Delay)
    hist, _ = np.histogram(fine_data, bins=range(NUM_TAPS + 1))
    tap_widths_ps = T_CLK_PS * (hist / total_samples)
    calibration_lut = np.cumsum(tap_widths_ps)       
    
    # DNL (미분 비선형성) / INL (적분 비선형성) 계산
    LSB_ideal = T_CLK_PS / NUM_TAPS                  # 이상적인 1탭의 너비 (15.625 ps)
    dnl = (tap_widths_ps - LSB_ideal) / LSB_ideal    # DNL 계산 (LSB 단위)
    inl = np.cumsum(dnl)                             # INL 계산 (DNL 누적합)
    
    # =====================================================================
    # 3. 분석 결과 CSV 내보내기 (PC 후처리 및 분석용)
    # =====================================================================
    lut_df = pd.DataFrame({
        'Fine_Index': range(NUM_TAPS),
        'Hit_Count': hist,
        'Tap_Width_ps': tap_widths_ps,
        'Cumulative_Delay_ps': calibration_lut,
        'DNL_LSB': dnl,
        'INL_LSB': inl
    })
    lut_df.to_csv("tdc_calibration_lut.csv", index=False)
    print("-> [저장 완료] 소프트웨어 분석용 CSV: tdc_calibration_lut.csv")
    
    # =====================================================================
    # 4. Vivado Block ROM 적용용 .coe 파일 생성 (하드웨어 실시간 연산용)
    # =====================================================================
    lut_integers = np.round(calibration_lut).astype(int)
    
    coe_filename = "tdc_lut.coe"
    with open(coe_filename, "w") as f:
        f.write("; ================================================\n")
        f.write("; TDC Calibration LUT generated by Python Script\n")
        f.write(f"; Total Taps: {NUM_TAPS}, Clock: {T_CLK_PS}ps\n")
        f.write("; ================================================\n")
        f.write("memory_initialization_radix=10;\n")
        f.write("memory_initialization_vector=\n")
        for i, val in enumerate(lut_integers):
            if i == len(lut_integers) - 1:
                f.write(f"{val};\n")
            else:
                f.write(f"{val},\n")
    print(f"-> [저장 완료] Vivado 하드웨어 ROM용 COE: {coe_filename}")

    # =====================================================================
    # 5. 종합 분석 리포트 그래프 시각화 (PNG 저장)
    # =====================================================================
    # 2x2 형태의 대형 그래프 그리드 생성
    fig, axs = plt.subplots(2, 2, figsize=(16, 10))
    
    # [Top-Left] 빈도수 히스토그램
    axs[0, 0].bar(range(NUM_TAPS), hist, color='royalblue', width=1.0)
    axs[0, 0].set_title("Fine Index Frequency (Code Density Test)", fontsize=13, fontweight='bold')
    axs[0, 0].set_xlabel("Fine Index"), axs[0, 0].set_ylabel("Occurrence Count")
    axs[0, 0].grid(True, linestyle='--', alpha=0.5)
    
    # [Top-Right] 누적 딜레이 곡선 (Calibration LUT)
    axs[0, 1].plot(range(NUM_TAPS), calibration_lut, color='crimson', linewidth=2.5)
    axs[0, 1].set_title("Cumulative Delay Curve (TDC LUT)", fontsize=13, fontweight='bold')
    axs[0, 1].set_xlabel("Fine Index"), axs[0, 1].set_ylabel("Calibrated Time (ps)")
    axs[0, 1].axhline(y=T_CLK_PS, color='darkgreen', linestyle=':', label=f"Clock Period ({T_CLK_PS} ps)")
    axs[0, 1].legend(loc='lower right')
    axs[0, 1].grid(True, linestyle='--', alpha=0.5)

    # [Bottom-Left] DNL (Differential Non-Linearity)
    axs[1, 0].plot(range(NUM_TAPS), dnl, color='purple', linewidth=1.5)
    axs[1, 0].set_title("DNL (Differential Non-Linearity)", fontsize=13, fontweight='bold')
    axs[1, 0].set_xlabel("Fine Index"), axs[1, 0].set_ylabel("DNL (LSB)")
    axs[1, 0].axhline(y=0, color='black', linewidth=1)
    axs[1, 0].axhline(y=-1, color='red', linestyle=':', label='Missing Code (-1 LSB)')
    axs[1, 0].legend()
    axs[1, 0].grid(True, linestyle='--', alpha=0.5)

    # [Bottom-Right] INL (Integral Non-Linearity)
    axs[1, 1].plot(range(NUM_TAPS), inl, color='darkorange', linewidth=1.5)
    axs[1, 1].set_title("INL (Integral Non-Linearity)", fontsize=13, fontweight='bold')
    axs[1, 1].set_xlabel("Fine Index"), axs[1, 1].set_ylabel("INL (LSB)")
    axs[1, 1].axhline(y=0, color='black', linewidth=1)
    axs[1, 1].grid(True, linestyle='--', alpha=0.5)
    
    # 텍스트가 겹치지 않게 레이아웃 자동 조정 후 저장
    plt.tight_layout()
    plt.savefig("tdc_comprehensive_analysis.png", dpi=300)
    print("-> [저장 완료] 종합 분석 결과 이미지: tdc_comprehensive_analysis.png")

if __name__ == "__main__":
    run_calibration_flow()