@echo off
REM ===========================================================================
REM  run_build.bat  -  Build the ZedBoard TDC project (Vivado batch mode)
REM  Generated by Claude Code, 2026-09-06
REM
REM  NOTE: ASCII only on purpose. Korean text in a .bat breaks cmd parsing
REM        because cmd reads the file using the OEM codepage.
REM        Full Korean guide: Markdown\HANDOVER_...(handover).md
REM
REM  USAGE   double-click, or from a Command Prompt:
REM      run_build.bat
REM      run_build.bat 2 zed_pmod 1 1
REM
REM  ARGS (all optional, defaults shown)
REM      1) OPERATION_MODE   0=DPS(not implemented) 1=ring-osc 2=external   [2]
REM      2) project folder   created under vivado\<name>            [zed_pmod]
REM      3) build?           1=synth..bitstream  0=create project only     [1]
REM      4) HIT_INPUT        1=PMOD single-ended Y11  0=FMC LVDS E21/D21   [1]
REM
REM  COMMON
REM      run_build.bat 2 zed_pmod 1 1    STM32 on PMOD  (current setup)
REM      run_build.bat 2 zed_fmc  1 0    fast LVDS comparator on FMC
REM
REM  Takes 20-30 min. When done, check that WNS and WHS are both positive.
REM ===========================================================================
setlocal
set VIVADO=C:\Xilinx\Vivado\2024.1\bin\vivado.bat

set OPMODE=%1
set PRJ=%2
set DOBUILD=%3
set HITIN=%4
if "%OPMODE%"==""  set OPMODE=2
if "%PRJ%"==""     set PRJ=zed_pmod
if "%DOBUILD%"=="" set DOBUILD=1
if "%HITIN%"==""   set HITIN=1

cd /d "%~dp0"

if not exist "%VIVADO%" goto NOVIVADO
if exist "vivado\%PRJ%" goto EXISTS

echo ==========================================================
echo  ZedBoard TDC build
echo    OPERATION_MODE : %OPMODE%
echo    project        : vivado\%PRJ%
echo    build          : %DOBUILD%
echo    HIT_INPUT      : %HITIN%    1=PMOD Y11  0=FMC LVDS
echo ==========================================================
echo.

"%VIVADO%" -mode batch -nojournal -source build_zedboard.tcl -tclargs %OPMODE% %PRJ% %DOBUILD% %HITIN%

echo.
echo ==========================================================
if exist "vivado\%PRJ%\%PRJ%.runs\impl_1\tdc_zedboard_top.bit" goto OK
echo  [!] No bitstream. Look for ERROR in the log above.
goto END
:OK
echo  Bitstream:
echo    vivado\%PRJ%\%PRJ%.runs\impl_1\tdc_zedboard_top.bit
echo.
echo  Timing report: vivado\%PRJ%\timing_summary.rpt
echo  WNS and WHS must both be positive.
echo.
echo  Next: run_check.bat
goto END

:NOVIVADO
echo.
echo  [!] Vivado not found: %VIVADO%
echo      Edit the VIVADO= line near the top of this file.
goto END

:EXISTS
echo.
echo  [!] Already exists: vivado\%PRJ%
echo      The build script never overwrites. Either delete that folder,
echo      or pass a different name as the 2nd argument.
echo      Example:  run_build.bat 2 zed_test 1 1
goto END

:END
echo ==========================================================
echo.
pause
endlocal
