@echo off
REM ===========================================================================
REM  run_capture.bat  -  Mode 2 raw capture {coarse, fine} via XSCT
REM  Generated by Claude Code, 2026-09-06
REM
REM  NOTE: ASCII only on purpose (Korean in a .bat breaks cmd parsing).
REM        Full Korean guide: Markdown\HANDOVER_...(handover).md
REM
REM  USAGE
REM      run_capture.bat                4096 hits
REM      run_capture.bat 1024           1024 hits
REM      run_capture.bat 4096 zed_fmc   pick a different project folder
REM
REM  WHY RAW
REM      The default capture (CAP_FMT=0) returns timestamp_ps, which the
REM      hardware computes through the calibration ROM. That ROM currently
REM      holds a plain linear ramp whose scale does not match this build's
REM      real tap size. Measured 2026-09-06: 552 ps vs 415 ps, i.e. 25% worse.
REM      Raw gives {coarse, fine} untouched, so you can recompute in Python
REM      with the correct scale and compare.
REM
REM  *** The board must already be programmed. This script does NOT program it.
REM      Reprogramming would clear the histogram and the danger settings.
REM      Run run_check.bat once first.
REM
REM  OUTPUT   vivado\capture_raw.csv   (Index, Coarse, Fine)
REM  ANALYSE  python python\analyze_chirp_capture.py
REM ===========================================================================
setlocal
set XSCT=C:\Xilinx\Vitis\2024.1\bin\xsct.bat

set CAPN=%1
set PRJ=%2
if "%CAPN%"=="" set CAPN=4096
if "%PRJ%"==""  set PRJ=zed_pmod

cd /d "%~dp0"

if not exist "%XSCT%" goto NOXSCT

echo ==========================================================
echo  Raw capture    CAP_N = %CAPN%    project vivado\%PRJ%
echo ==========================================================
echo.

"%XSCT%" tcl\xsct_capture_raw.tcl %PRJ% %CAPN%

echo.
if exist "vivado\capture_raw.csv" goto OK
echo  [!] No capture file. Check the log above.
echo      If 0 hits arrived, check in this order:
echo        1) Is GND connected between the source and the board
echo        2) Is the source actually producing a signal (scope)
echo        3) Is HIT_INPUT right (1=PMOD Y11, 0=FMC LVDS)
goto END
:OK
echo  -^> vivado\capture_raw.csv
echo.
echo  To analyse:  python python\analyze_chirp_capture.py
goto END

:NOXSCT
echo.
echo  [!] XSCT not found: %XSCT%
goto END

:END
echo.
pause
endlocal
