@echo off
REM ===========================================================================
REM  run_check.bat  -  Program the board, then check registers / Mode 1 / danger
REM  Generated by Claude Code, 2026-09-06
REM
REM  NOTE: ASCII only on purpose (Korean in a .bat breaks cmd parsing).
REM        Full Korean guide: Markdown\HANDOVER_...(handover).md
REM
REM  USAGE
REM      run_check.bat              skip Mode 2  (no external signal)
REM      run_check.bat 1            include Mode 2 capture
REM      run_check.bat 1 zed_fmc    pick a different project folder
REM
REM  WHAT IT DOES
REM      ps7_init -> download bitstream -> read ID/BUILD/DNA/STATUS
REM      -> Mode 1 measurement (2,000,000 hits) -> window / headroom check
REM      -> auto-set the danger thresholds from the histogram
REM      -> (if arg 1) Mode 2 capture
REM
REM  *** The danger auto-set is the important part. The measurement window
REM      shifts on every build, so run this once after each build. If the
REM      thresholds do not match the window, coarse can be off by 5000 ps and
REM      the histogram will NOT show it.
REM
REM  OUTPUT  vivado\mode2_check.log , vivado\histo_mux.csv , vivado\capture.csv
REM  Takes 1-2 min. No C program needed - XSCT talks to the ARM over JTAG.
REM ===========================================================================
setlocal
set XSCT=C:\Xilinx\Vitis\2024.1\bin\xsct.bat

set DOMODE2=%1
set PRJ=%2
if "%DOMODE2%"=="" set DOMODE2=0
if "%PRJ%"==""     set PRJ=zed_pmod

cd /d "%~dp0"

if not exist "%XSCT%" goto NOXSCT
if not exist "vivado\%PRJ%\%PRJ%.runs\impl_1\tdc_zedboard_top.bit" goto NOBIT

echo ==========================================================
echo  Board check    project vivado\%PRJ%    Mode2 = %DOMODE2%
echo  (board power and USB-JTAG must be connected)
echo ==========================================================
echo.

"%XSCT%" tcl\xsct_mode2_check.tcl %DOMODE2% %PRJ%

echo.
echo ==========================================================
echo  Result files (open with Notepad):
echo    vivado\mode2_check.log   full check output
echo    vivado\histo_mux.csv     Mode 1 histogram, 384 taps
if "%DOMODE2%"=="1" echo    vivado\capture.csv       Mode 2 capture
goto END

:NOXSCT
echo.
echo  [!] XSCT not found: %XSCT%
echo      Edit the XSCT= line near the top of this file.
goto END

:NOBIT
echo.
echo  [!] No bitstream: vivado\%PRJ%\...\tdc_zedboard_top.bit
echo      Run run_build.bat first.
goto END

:END
echo ==========================================================
echo.
pause
endlocal
