/* Generated by Claude Code, 2026-09-06
 * =============================================================================
 * tdc_app.c  —  ZedBoard TDC 를 PS(ARM)에서 조종하는 베어메탈 프로그램
 *
 *  [무엇을 하나]
 *  Vitis 에서 이 파일 하나만 넣고 빌드해 돌리면, TDC 측정을 처음부터 끝까지 한다.
 *  결과는 UART(115200-8-N-1)로 나온다. 터미널을 열어 텍스트를 그대로 복사해
 *  CSV 로 저장하면 python/ 의 분석 스크립트에 바로 넣을 수 있다.
 *
 *  [Vitis 설정 — 두 가지만 확인]
 *   1) 링커 스크립트의 메모리 영역을 **ps7_ram_0 (OCM)** 으로 둘 것.
 *      이 프로젝트의 블록 디자인은 DDR 파라미터를 ZedBoard 에 맞춰 넣지 않았다.
 *      (보드 파일이 없어 배선 지연 값을 손으로 넣으면 틀리기 쉽다)
 *      OCM 은 256 KB 이고 이 프로그램은 전역 배열이 40 KB 남짓이라 충분하다.
 *   2) stdout 이 ps7_uart_1 인지 확인 (BSP 설정). ZedBoard 의 USB-UART 가 MIO 48/49 다.
 *
 *  [메뉴]
 *  프로그램이 뜨면 UART 로 한 글자를 받아 동작한다. 터미널에서 키를 누르면 된다.
 *    i  신원/상태 읽기
 *    1  Mode 1 (링오실레이터 코드밀도) 측정 -> 384탭 CSV 출력
 *    2  Mode 2 (외부 신호) 캡처 -> 타임스탬프 CSV 출력
 *    r  Mode 2 캡처를 raw {coarse,fine} 형식으로
 *    d  히스토그램에서 danger 임계값을 계산해 설정
 *    p  위상 이동 시험
 *    h  도움말
 *
 *  [★ 반드시 알아야 할 것 — 측정 창은 빌드마다 움직인다]
 *  히트가 찍히는 탭 범위(창)는 히트 경로 지연에 따라 통째로 미끄러진다.
 *  2026-09-05 에 HIT_SRC 먹스(LUT 하나)가 들어가자 창이 탭 2~321 에서 24~348 로
 *  옮겨갔고, 같은 RTL 을 재빌드해도 349 -> 348 로 1탭 달라졌다.
 *  danger 임계값은 그 창의 양 끝에 있어야 하므로, **빌드할 때마다 'd' 를 한 번
 *  돌려 다시 맞춰야 한다.** 안 맞으면 coarse 가 5000 ps 틀리는 일이 생기는데
 *  히스토그램으로는 보이지 않는다.
 * =============================================================================
 */
#include <stdio.h>
#include "xil_printf.h"
#include "xil_io.h"
#include "xparameters.h"
#include "xuartps_hw.h"
#include "sleep.h"

/* ---------------------------------------------------------------- 레지스터 맵 */
/* 맵 버전 6. BUILD 레지스터의 하위 8비트로 확인할 수 있다. */
#define TDC_BASE      0x43C00000u

#define R_ID          (TDC_BASE + 0x00u)  /* R   0x54444302                     */
#define R_BUILD       (TDC_BASE + 0x04u)  /* R   {탭수16, 단수8, 맵버전8}        */
#define R_CTRL        (TDC_BASE + 0x08u)  /* RW  아래 비트 정의 참조             */
#define R_STATUS      (TDC_BASE + 0x0Cu)  /* R   아래 비트 정의 참조             */
#define R_DNA         (TDC_BASE + 0x10u)  /* R   [31]valid + DNA[30:0]          */
#define R_ROCNT       (TDC_BASE + 0x14u)  /* R   10 ms 게이트당 RO 에지 수       */
#define R_TEMP        (TDC_BASE + 0x18u)  /* R   [15:0] XADC 온도 raw           */
#define R_PHASE       (TDC_BASE + 0x1Cu)  /* RW  쓰기=목표, 읽기[24:16]=현재     */
#define R_TARGET      (TDC_BASE + 0x20u)  /* RW  목표 히트 수 (0 = 무제한)       */
#define R_HITCNT      (TDC_BASE + 0x24u)  /* R   실제 누적된 히트 수             */
#define R_SETTLE      (TDC_BASE + 0x28u)  /* RW  RO 안정화 대기 클럭 수          */
#define R_ROSTA       (TDC_BASE + 0x2Cu)  /* R   측정 시작 시 RO 카운트          */
#define R_ROEND       (TDC_BASE + 0x30u)  /* R   측정 종료 시 RO 카운트          */
#define R_TEMPSE      (TDC_BASE + 0x34u)  /* R   {끝 온도[31:16], 시작[15:0]}    */
#define R_DROP        (TDC_BASE + 0x38u)  /* R   버려진 히트 수                  */
#define R_CAPN        (TDC_BASE + 0x3Cu)  /* RW  캡처할 히트 수 (1..4096)        */
#define R_CAPCNT      (TDC_BASE + 0x40u)  /* R   지금까지 모인 수                */
#define R_DANGER      (TDC_BASE + 0x44u)  /* RW  {hi[24:16], lo[8:0]}           */

#define R_HISTO(i)    (TDC_BASE + 0x1000u + (u32)(i) * 4u)          /* i=0..383  */
#define R_CAP_LO(i)   (TDC_BASE + 0x8000u + (u32)(i) * 8u)          /* i=0..4095 */
#define R_CAP_HI(i)   (TDC_BASE + 0x8000u + (u32)(i) * 8u + 4u)

/* CTRL 비트 */
#define C_SRC_OFF     0x0u        /* 히트 소스 : 꺼짐                            */
#define C_SRC_RO      0x1u        /*             링오실레이터 (Mode 1)           */
#define C_SRC_DPS     0x2u        /*             위상시프트 (Mode 0, 미구현)     */
#define C_SRC_EXT     0x3u        /*             외부 입력 (Mode 2)              */
#define C_START       (1u << 2)
#define C_STOP        (1u << 3)
#define C_HISTO_CLR   (1u << 4)
#define C_TDC_RST     (1u << 5)   /* ※ 아직 하드웨어에 연결 안 됨 (2026-09-06)   */
#define C_CAP_FMT     (1u << 6)   /* 0 = timestamp_ps, 1 = raw {coarse,fine}     */

/* STATUS 비트 */
#define S_MMCM_LOCKED (1u << 0)
#define S_DNA_VALID   (1u << 2)
#define S_BUSY        (1u << 3)
#define S_DONE        (1u << 4)
#define S_PHASE_BUSY  (1u << 5)
#define S_STATE_SHIFT 8
#define S_STATE_MASK  0x7u

#define NUM_TAPS      384
#define CAP_MAX       4096

static u32 g_histo[NUM_TAPS];
static u32 g_cap_lo[CAP_MAX];
static u32 g_cap_hi[CAP_MAX];

static const char *STATE_NAME[8] = {
    "S_IDLE", "S_RO_ENABLE", "S_MEAS_FREQ", "S_STABILIZE",
    "S_ACQ", "S_DONE", "?", "?"
};

#define RD(a)     Xil_In32((a))
#define WR(a, v)  Xil_Out32((a), (u32)(v))

/* ---------------------------------------------------------------- 도우미 */

/* XADC 온도 raw -> 섭씨. UG480 식 (2-6).
 * 정수 연산으로 0.01 도 단위를 만든다 (베어메탈에서 float printf 는 무겁다). */
static int temp_centi(u32 raw)
{
    /* T[C] = raw/65536 * 503.975 - 273.15  ->  100배 해서 정수로 */
    return (int)(((s64)(raw & 0xFFFFu) * 50397) / 65536) - 27315;
}

static void print_centi(const char *name, int c)
{
    xil_printf("%s%s%d.%02d C\r\n", name, (c < 0 ? "-" : ""),
               (c < 0 ? -c : c) / 100, (c < 0 ? -c : c) % 100);
}

/* RO 에지 수 -> 주파수 [kHz].
 *   ro_divider_cnt 는 RO 상승엣지마다 +1, 측정 탭이 [1] 이라 4번 증가마다 한 주기,
 *   ro_edge 는 상승엣지만 세므로 RO 4주기당 1카운트다. 게이트는 10 ms.
 *     f_RO [Hz] = RO_CNT x 4 / 0.01 s     ->  [kHz] = RO_CNT x 4 / 10
 *   ※ 이 식이 코드에 없어서 2026-09-04 문서가 2배 틀린 값을 실은 적이 있다. */
static u32 ro_khz(u32 cnt) { return (cnt * 4u) / 10u; }

static int wait_done(int timeout_ms)
{
    int i;
    for (i = 0; i < timeout_ms; i++) {
        if (RD(R_STATUS) & S_DONE) return 1;
        usleep(1000);
    }
    return 0;
}

/* ---------------------------------------------------------------- 명령들 */

static void cmd_info(void)
{
    u32 build = RD(R_BUILD);
    u32 st    = RD(R_STATUS);
    u32 dna   = RD(R_DNA);
    u32 dg    = RD(R_DANGER);

    xil_printf("\r\n===== 신원 / 상태 =====\r\n");
    xil_printf("ID      = 0x%08X   (0x54444302 이어야 함)\r\n", RD(R_ID));
    xil_printf("BUILD   = 0x%08X   탭 %d, 단수 %d, 맵버전 %d\r\n",
               build, (build >> 16) & 0xFFFF, (build >> 8) & 0xFF, build & 0xFF);
    xil_printf("DNA     = 0x%08X   valid=%d\r\n", dna, (dna >> 31) & 1u);
    xil_printf("STATUS  = 0x%08X   MMCM=%d BUSY=%d DONE=%d PHASE_BUSY=%d  상태=%s\r\n",
               st, st & 1u, (st >> 3) & 1u, (st >> 4) & 1u, (st >> 5) & 1u,
               STATE_NAME[(st >> S_STATE_SHIFT) & S_STATE_MASK]);
    xil_printf("RO_CNT  = %d   (약 %d kHz)\r\n", RD(R_ROCNT), ro_khz(RD(R_ROCNT)));
    print_centi("DIE_TEMP= ", temp_centi(RD(R_TEMP)));
    xil_printf("DANGER  = lo %d, hi %d\r\n", dg & 0x1FFu, (dg >> 16) & 0x1FFu);
    xil_printf("CAP_N   = %d,  TARGET_HITS = %d,  SETTLE_N = %d\r\n",
               RD(R_CAPN), RD(R_TARGET), RD(R_SETTLE));

    if ((st & S_MMCM_LOCKED) == 0)
        xil_printf("!! MMCM 이 안 잠겼다. FCLK 를 확인할 것.\r\n");
}

/* Mode 1 : 링오실레이터 코드밀도 히스토그램 */
static void cmd_mode1(u32 target)
{
    int i;
    u32 sum = 0, hitcnt, first = 0xFFFFFFFFu, last = 0;

    xil_printf("\r\n===== Mode 1 : 코드밀도 히스토그램 =====\r\n");
    xil_printf("목표 히트 %d 발. 시작...\r\n", target);

    WR(R_TARGET, target);
    WR(R_CTRL, C_SRC_RO | C_START);

    if (!wait_done(120000)) {           /* 최대 2분 */
        xil_printf("!! 시간 초과. 상태=%s\r\n",
                   STATE_NAME[(RD(R_STATUS) >> S_STATE_SHIFT) & S_STATE_MASK]);
        WR(R_CTRL, 0);
        return;
    }

    hitcnt = RD(R_HITCNT);
    for (i = 0; i < NUM_TAPS; i++) {
        g_histo[i] = RD(R_HISTO(i));
        sum += g_histo[i];
        if (g_histo[i]) { if (first == 0xFFFFFFFFu) first = (u32)i; last = (u32)i; }
    }

    xil_printf("\r\nHIT_CNT = %d,  384탭 합 = %d,  차이 = %d\r\n",
               hitcnt, sum, (int)hitcnt - (int)sum);
    if (hitcnt != sum)
        xil_printf("!! 일치하지 않는다. 총 히트 수 H 를 믿을 수 없다.\r\n");
    else
        xil_printf("OK  정확히 일치 -> w[i] = h[i]/H x 5000 ps 의 H 를 믿을 수 있다\r\n");

    xil_printf("히트 있는 탭 = %d ~ %d,  체인 끝까지 여유 = %d 탭\r\n",
               first, last, NUM_TAPS - 1 - (int)last);
    if ((int)(NUM_TAPS - 1 - (int)last) < 20)
        xil_printf("!! 여유 20탭 미만. 온도가 오르면 체인 끝을 넘어간다.\r\n");

    xil_printf("DROP_CNT = %d  (데드타임에 버려진 히트)\r\n", RD(R_DROP));
    xil_printf("RO  시작 %d (%d kHz) -> 끝 %d (%d kHz)\r\n",
               RD(R_ROSTA), ro_khz(RD(R_ROSTA)), RD(R_ROEND), ro_khz(RD(R_ROEND)));
    {
        u32 tse = RD(R_TEMPSE);
        print_centi("온도 시작 ", temp_centi(tse & 0xFFFFu));
        print_centi("온도 끝   ", temp_centi((tse >> 16) & 0xFFFFu));
    }

    xil_printf("\r\n----- 여기부터 CSV (복사해서 tap_histogram.csv 로 저장) -----\r\n");
    xil_printf("Tap_Index,Hit_Count\r\n");
    for (i = 0; i < NUM_TAPS; i++) xil_printf("%d,%d\r\n", i, g_histo[i]);
    xil_printf("----- CSV 끝 -----\r\n");

    WR(R_CTRL, 0);                      /* START 를 내려야 S_IDLE 로 돌아간다 */
}

/* 히스토그램에서 danger 임계값을 계산해 설정한다.
 *
 *  danger 는 "히트가 클럭 에지 근처인가" 를 fine 탭 번호로 판단하는 경계다.
 *  에지는 창의 양 끝 두 곳이므로 양끝에서 같은 시간만큼을 가드로 잡는다.
 *  목표 630 ps 는 2026-09-05 에 상수 40 이 만들던 아래 가드 폭이다 —
 *  "예전과 같은 여유를 창이 어디로 가든 유지한다" 는 뜻이지 630 ps 가 옳다는
 *  뜻은 아니다. coarse 카운터의 실제 불안정 구간은 아직 측정된 적이 없다.
 *
 *  ※ 반드시 cmd_mode1 을 먼저 돌려 g_histo 를 채운 뒤 호출할 것.
 */
static void cmd_set_danger(void)
{
    const u32 GUARD_PS = 630u;
    u32 H = 0, acc, i, first = 0xFFFFFFFFu, last = 0, lo = 0, hi = 0;

    for (i = 0; i < NUM_TAPS; i++) {
        H += g_histo[i];
        if (g_histo[i]) { if (first == 0xFFFFFFFFu) first = i; last = i; }
    }
    if (H == 0) { xil_printf("!! 히스토그램이 비었다. 먼저 '1' 을 실행할 것.\r\n"); return; }

    /* w[i] = h[i]/H x 5000 ps 를 누적한다. 정수로 하려고 순서를 바꿔 곱셈을 먼저 한다. */
    acc = 0;
    for (i = first; i <= last; i++) {
        acc += (u32)(((u64)g_histo[i] * 5000u) / H);
        if (acc >= GUARD_PS) { lo = i + 1; break; }
    }
    acc = 0;
    for (i = last; i > first; i--) {
        acc += (u32)(((u64)g_histo[i] * 5000u) / H);
        if (acc >= GUARD_PS) { hi = i - 1; break; }
    }
    if (lo == 0 || hi == 0 || lo >= hi) {
        xil_printf("!! 가드를 못 잡았다 (lo=%d hi=%d). 히스토그램을 확인할 것.\r\n", lo, hi);
        return;
    }

    xil_printf("\r\n창 %d~%d  ->  DANGER lo=%d hi=%d  (가드 각 %d ps 목표)\r\n",
               first, last, lo, hi, GUARD_PS);
    WR(R_DANGER, ((u32)hi << 16) | (u32)lo);
    {
        u32 rb = RD(R_DANGER);
        xil_printf("되읽기 = 0x%08X  (lo=%d hi=%d)  %s\r\n",
                   rb, rb & 0x1FFu, (rb >> 16) & 0x1FFu,
                   ((rb & 0x1FFu) == lo && ((rb >> 16) & 0x1FFu) == hi) ? "OK" : "!! 안 먹었다");
    }
}

/* Mode 2 : 외부 신호 캡처. raw != 0 이면 {coarse, fine} 형식 */
static void cmd_mode2(u32 capn, int raw)
{
    u32 i, ctrl;

    if (capn > CAP_MAX) capn = CAP_MAX;
    xil_printf("\r\n===== Mode 2 : 외부 신호 캡처 (%s) =====\r\n",
               raw ? "raw {coarse,fine}" : "timestamp_ps");

    WR(R_CAPN, capn);
    ctrl = C_SRC_EXT | C_START | (raw ? C_CAP_FMT : 0u);
    WR(R_CTRL, ctrl);

    if (!wait_done(30000)) {
        xil_printf("!! 시간 초과. CAP_CNT = %d / %d\r\n", RD(R_CAPCNT), capn);
        xil_printf("   히트가 안 들어오면 순서대로 확인:\r\n");
        xil_printf("   1) 신호원이 실제로 신호를 내보내는가 (스코프)\r\n");
        xil_printf("   2) GND 가 연결돼 있는가 (점퍼로 이을 때 제일 흔히 빠뜨린다)\r\n");
        xil_printf("   3) HIT_INPUT=1(PMOD Y11) 빌드인가, 0(FMC LVDS)인가\r\n");
        xil_printf("   4) FMC LVDS 라면 J18 점퍼가 2.5V 인가 (기본 1.8V)\r\n");
        WR(R_CTRL, 0);
        return;
    }

    for (i = 0; i < capn; i++) {
        g_cap_lo[i] = RD(R_CAP_LO(i));
        g_cap_hi[i] = RD(R_CAP_HI(i));
    }
    xil_printf("CAP_CNT = %d,  DROP_CNT = %d\r\n", RD(R_CAPCNT), RD(R_DROP));

    xil_printf("\r\n----- 여기부터 CSV -----\r\n");
    if (raw) {
        /* capture_raw.csv 와 같은 형식 -> python/analyze_chirp_capture.py 에 그대로 */
        xil_printf("Index,Coarse,Fine\r\n");
        for (i = 0; i < capn; i++)
            xil_printf("%d,%u,%d\r\n", i, g_cap_lo[i], g_cap_hi[i] & 0x1FFu);
    } else {
        /* timestamp_ps 는 48비트라 32비트 두 개로 나눠 찍는다.
         * 파이썬에서 ts = hi * 2^32 + lo 로 합치면 된다. */
        xil_printf("Index,TS_Lo,TS_Hi\r\n");
        for (i = 0; i < capn; i++)
            xil_printf("%d,%u,%u\r\n", i, g_cap_lo[i], g_cap_hi[i]);
    }
    xil_printf("----- CSV 끝 -----\r\n");

    WR(R_CTRL, 0);
}

/* 위상 이동 시험. Mode 0 자체는 아직 하드웨어에 없다 —
 * 위상 시프터가 도는지만 본다. */
static void cmd_phase(void)
{
    u32 tgt, cur, spin;

    xil_printf("\r\n===== 위상 이동 시험 =====\r\n");
    for (tgt = 0; tgt <= 240; tgt += 40) {
        WR(R_PHASE, tgt);
        for (spin = 0; spin < 100000u; spin++)
            if ((RD(R_STATUS) & S_PHASE_BUSY) == 0) break;
        cur = (RD(R_PHASE) >> 16) & 0x1FFu;
        xil_printf("목표 %3d -> 현재 %3d   %s\r\n", tgt, cur, (cur == tgt) ? "OK" : "!! 불일치");
    }
    WR(R_PHASE, 0);
}

static void help(void)
{
    xil_printf("\r\n===== 명령 =====\r\n");
    xil_printf("  i : 신원/상태 읽기\r\n");
    xil_printf("  1 : Mode 1 코드밀도 측정 (200만 발) -> 384탭 CSV\r\n");
    xil_printf("  d : 히스토그램에서 danger 임계값 계산해 설정  <- '1' 뒤에 반드시 한 번\r\n");
    xil_printf("  2 : Mode 2 캡처 (timestamp_ps) -> CSV\r\n");
    xil_printf("  r : Mode 2 캡처 (raw coarse/fine) -> CSV\r\n");
    xil_printf("  p : 위상 이동 시험\r\n");
    xil_printf("  h : 이 도움말\r\n");
}

int main(void)
{
    xil_printf("\r\n\r\n############################################\r\n");
    xil_printf("  ZedBoard TDC — PS 제어 프로그램\r\n");
    xil_printf("  Generated by Claude Code, 2026-09-06\r\n");
    xil_printf("############################################\r\n");

    cmd_info();
    help();

    for (;;) {
        u8 c;
        xil_printf("\r\n> ");
        while (!XUartPs_IsReceiveData(STDIN_BASEADDRESS)) { }
        c = XUartPs_ReadReg(STDIN_BASEADDRESS, XUARTPS_FIFO_OFFSET);
        xil_printf("%c\r\n", c);

        switch (c) {
        case 'i': cmd_info();          break;
        case '1': cmd_mode1(2000000u); break;
        case 'd': cmd_set_danger();    break;
        case '2': cmd_mode2(1024u, 0); break;
        case 'r': cmd_mode2(4096u, 1); break;
        case 'p': cmd_phase();         break;
        case 'h': help();              break;
        default:  xil_printf("모르는 명령. 'h' 를 눌러 볼 것.\r\n"); break;
        }
    }
    return 0;
}
