# Generated by Claude Code, 2026-09-05
# ★ 2026-09-06 전면 개정 — 실측을 해보니 처음 방식이 안 맞았다. 아래 [방법] 참조.
# =============================================================================
# analyze_chirp_capture.py — Mode 2 캡처를 STM32 참값과 대조한다
#
#  [무엇을 하나]
#  STM32 가 내보낸 chirp 를 TDC 가 얼마나 정확히 쟀는지 본다.
#  STM32 코드가 있으므로 **참값을 안다** — 그게 이 분석의 핵심이다.
#
#  [참값 — STM32 main.c 에서]
#      TIMER_CLK = 170 MHz         -> 타이머 눈금 = 5882.35 ps
#      F_START = 100 kHz, F_END = 1 MHz, CHIRP_DURATION = 5 ms
#      beta = (1e6-1e5)/0.005 = 180 kHz/ms
#      arr = round(170e6/f) - 1  ->  **간격은 눈금의 정수배다**
#  즉 STM32 는 양자화된 참값을 공짜로 준다. 격자에서 벗어난 양이 곧 오차다.
#
#  [★ 방법 — 왜 '간격의 차이' 로 보나]
#  처음엔 간격 자체를 눈금으로 나눠 정수배인지 봤는데 실패했다. 이유:
#  간격이 269~998 눈금이라, 눈금 길이가 1 ps 만 틀려도 998 ps 오차가 되어
#  반올림이 어긋난다. STM32 는 HSI(내장 RC)라 170 MHz 가 정확하지 않으므로
#  이 문제를 피할 수 없다.
#    -> **이웃한 간격의 차이**를 본다. chirp 는 눈금을 하나씩 줄여가므로
#       그 차이는 0, -1, -2 눈금뿐이다. 정수가 작아 반올림이 안정하다.
#  실측에서 1022개 전부 맞았다 (0:804, -1:214, -2:4).
#
#  [입력]
#    raw 캡처 : vivado/capture_raw.csv  (Index, Coarse, Fine)   <- 권장
#    히스토그램: vivado/histo_mux.csv    (Tap_Index, Hit_Count)
#  raw 를 쓰는 이유는 ROM 을 거치지 않은 원본이라, fine->ps 변환을 바꿔가며
#  비교할 수 있기 때문이다.
#
#  [실행]  python python/analyze_chirp_capture.py [raw.csv] [histo.csv]
# =============================================================================
import csv
import os
import sys

import numpy as np

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "vivado", "capture_raw.csv")
HST = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "..", "vivado", "histo_mux.csv")

TICK_NOM = 1e12 / 170e6          # STM32 타이머 눈금 [ps]
BETA_NOM = 180.0                 # 소인율 [kHz/ms]

raw = np.loadtxt(RAW, delimiter=",", skiprows=1, dtype=np.int64)
coarse, fine = raw[:, 1].astype(float), raw[:, 2].astype(int)
h = np.array([int(r[1]) for r in list(csv.reader(open(HST)))[1:]], float)

nzi = np.nonzero(h)[0]
lo, hi = nzi[0], nzi[-1]
w = h / h.sum() * 5000.0          # w[i] = h[i]/H x 5000 ps  (코드밀도 정의)
cum = np.concatenate([[0.0], np.cumsum(w)])

TABLES = {
    # 지금 FPGA 안에 실제로 들어 있는 ROM. 선형 램프, 한 칸 13 ps.
    "(a) 지금 ROM (선형 13 ps)": np.minimum(np.arange(384) * 13, 4987).astype(float),
    # 창을 0~5000 ps 에 균등 배분한 것. 탭 폭이 다 같다고 가정.
    "(b) 단순 선형 (창 균등)": (np.arange(384) - lo) * (5000.0 / (hi - lo + 1)),
    # 코드밀도 : 히스토그램에서 잰 실제 탭 폭의 누적 + 반 칸
    "(c) 코드밀도 LUT": (cum[:384] + w / 2.0) - (cum[lo] + w[lo] / 2.0),
}

print(f"[0] 입력")
print(f"    캡처   : {RAW}  ({len(raw)} 발)")
print(f"    히스토 : {HST}  창 {lo}~{hi} ({hi-lo+1}칸), 평균 탭 폭 {5000.0/(hi-lo+1):.3f} ps")
print(f"    fine 범위 : {fine.min()} ~ {fine.max()}")


def fit_grid(ts):
    """이웃한 간격의 차이로 눈금을 맞춘다. (d 는 간격, dd 는 그 차이)"""
    d = np.diff(ts)
    dd = np.diff(d)
    tick = TICK_NOM
    for _ in range(40):
        k = np.round(dd / tick)
        m = np.abs(dd / tick - k) < 0.4
        if m.sum() < 50:
            break
        tick = float(np.sum(k[m] * dd[m]) / np.sum(k[m] ** 2))
    k = np.round(dd / tick)
    m = np.abs(dd / tick - k) < 0.4
    r = dd - k * tick
    r = r[m] - r[m].mean()
    return tick, r, k[m], m, d


print("\n[1] 타임스탬프 건전성")
ts0 = coarse * 5000.0 - TABLES["(c) 코드밀도 LUT"][fine]
d0 = np.diff(ts0)
print(f"    0 이하인 간격 : {int((d0 <= 0).sum())} 개  (시간이 거꾸로 가면 coarse 선택 오류다)")
print(f"    간격 {d0.min()/1e6:.3f} ~ {d0.max()/1e6:.3f} us")

print("\n[2] chirp 파라미터 — STM32 코드와 대조")
T = (ts0[-1] - ts0[0]) / 1e12
f0, f1 = 1e12 / d0[0], 1e12 / d0[-1]
print(f"    캡처 구간   : {T*1e3:.3f} ms")
print(f"    주파수      : {f0/1e3:.2f} -> {f1/1e3:.2f} kHz  ({f1/f0:.2f} 배)")
# 소인율 = (주파수 변화 [kHz]) / (걸린 시간 [ms])
beta_meas = ((f1 - f0) / 1e3) / (T * 1e3)
print(f"    소인율      : 실측 {beta_meas:.1f} kHz/ms   vs 코드 {BETA_NOM:.1f} kHz/ms"
      f"   ({(beta_meas/BETA_NOM-1)*100:+.2f} %)")

print("\n[3] ★ STM32 눈금 격자와 대조 — fine->ps 변환을 바꿔가며")
print(f"    {'변환':26s} {'간격오차RMS':>12s} {'최대':>10s} {'맞춘 STM32 클럭':>18s}")
for name, tbl in TABLES.items():
    ts = coarse * 5000.0 - tbl[fine]
    tick, r, k, m, d = fit_grid(ts)
    # dd 는 간격 두 개의 차이이므로 간격 하나의 오차는 /sqrt(2)
    print(f"    {name:26s} {r.std()/np.sqrt(2):12.1f} {np.abs(r).max()/np.sqrt(2):10.1f}"
          f" {1e6/tick:14.4f} MHz  ({m.sum()}/{len(m)})")

tick, r, k, m, d = fit_grid(coarse * 5000.0 - TABLES["(c) 코드밀도 LUT"][fine])
ku, kc = np.unique(k.astype(int), return_counts=True)
print(f"\n    눈금 변화량 분포 : {list(zip(ku.tolist(), kc.tolist()))}")
print("    -> 0 과 -1 에 몰려야 정상이다 (chirp 이 눈금을 하나씩 줄인다)")
print(f"    STM32 클럭 : 공칭 170.000 MHz vs 실측 {1e6/tick:.4f} MHz "
      f"({(1e6/tick/170.0-1)*100:+.3f} %)  — HSI 내장 RC 라 이 정도는 정상")

print("\n[4] 남은 오차는 무엇인가")
print(f"    간격 오차 RMS            : {r.std()/np.sqrt(2):.0f} ps")
print(f"    TDC 양자화 한계(히스토그램) : 7.07 ps")
print(f"    -> {r.std()/np.sqrt(2)/7.07:.0f} 배다. 지연선 탓이 아니다.")
print("    근거 : 코드밀도 LUT 이 단순 선형보다 나아지지 않았다.")
print("           탭 폭 불균일이 지배적이라면 반드시 나아졌어야 한다.")
print("    ※ 남은 후보는 STM32 의 HSI 클럭 지터와 우리 FCLK 지터다.")
print("      이 캡처만으로는 못 가른다 — chirp 이라 간격 길이와 램프 위치가")
print("      함께 변해 서로 얽혀 있기 때문이다.")
print("      가르려면 STM32 를 **고정 주파수**로 두고 한 번 더 재야 한다.")
