# Generated by Claude Code, 2026-09-03
# =============================================================================
# 캐리체인 LOC/BEL 제약 생성기
#
# [왜 필요한가]
#   tdc_zedboard.xdc 의 캐리체인 제약은 단(stage)마다 25줄씩 기계적으로 반복된다.
#   80단이면 2000줄, 112단이면 2800줄이다. 손으로 고칠 분량이 아니고, 한 줄만
#   틀려도 그 단이 배치기 마음대로 놓여 지연선 특성이 통째로 달라진다.
#   단수를 바꿀 때마다 이 스크립트로 다시 뽑는다.
#
# [무엇을 만드나]
#   단 k 마다 정확히 25줄:
#     - SLICE_X42Y<k>  : CARRY4 1개 + u_ff_0~3 (BEL AFF/BFF/CFF/DFF)
#     - SLICE_X43Y<k>  : taps_sampled_d1_reg[4k .. 4k+3] (BEL AFF/BFF/CFF/DFF)
#   기존 파일의 문자열 형식을 그대로 재현한다 (get_cells 필터 표현까지 동일).
#
# [사용법]
#   python gen_chain_xdc.py                 # 기본 112단으로 RTL/tdc_zedboard.xdc 갱신
#   python gen_chain_xdc.py --stages 96
#   python gen_chain_xdc.py --check         # 파일을 안 고치고 현재 상태만 보고
#
# [주의]
#   - CARRY4 체인은 한 열 안에서 수직으로만 이어진다. SLICE_X42/X43 이 Y0~Y<stages-1>
#     까지 끊김 없이 있어야 한다. XC7Z020-CLG484 에서 2026-09-03 Tcl 로 확인한 결과는
#     X42 = SLICEM Y0~Y149, X43 = SLICEL Y0~Y149 (둘 다 연속) 이므로 최대 150단 가능.
#   - 단수는 16의 배수여야 popcount 트리가 4x(N/16)x16 으로 떨어진다 (80, 96, 112).
#   - 448탭(112단) 초과 금지 — sum_fine/ts_fine_idx 가 [8:0](<=511) 이고
#     히스토그램 BRAM 이 512칸이다.
# =============================================================================

import argparse
import os
import re
import sys

BEL = ["AFF", "BFF", "CFF", "DFF"]

# 체인 제약 블록의 시작/끝을 찾는 표지 (이 두 줄 자체는 블록에 포함되지 않는다)
FIRST_LINE_RE = re.compile(r"^set_property LOC SLICE_X42Y0 .*CARRY_CHAIN\[0\]\.STAGE")
LAST_LINE_RE = re.compile(r"^set_property LOC SLICE_X43Y\d+ .*taps_sampled_d1_reg\[\d+\]\}\]\s*$")


def stage_block(k):
    """단 k 에 해당하는 25줄을 만든다."""
    out = []
    # --- SLICE_X42Y<k> : CARRY4 + 샘플링 FF 4개 ---
    out.append(
        f"set_property LOC SLICE_X42Y{k} "
        f"[get_cells -hierarchical -filter {{NAME =~ *CARRY_CHAIN[{k}].STAGE*u_carry4*}}]"
    )
    for j, bel in enumerate(BEL):
        out.append(
            f"set_property BEL {bel} "
            f"[get_cells -hierarchical -filter {{NAME =~ *CARRY_CHAIN[{k}]*u_ff_{j}*}}]"
        )
        out.append(f"set_property BEL {bel} [get_cells {{u_tdc/CARRY_CHAIN[{k}].u_ff_{j}}}]")
        out.append(
            f"set_property LOC SLICE_X42Y{k} "
            f"[get_cells -hierarchical -filter {{NAME =~ *CARRY_CHAIN[{k}]*u_ff_{j}*}}]"
        )
    # --- SLICE_X43Y<k> : taps_sampled_d1_reg 4개 ---
    for j, bel in enumerate(BEL):
        t = k * 4 + j
        out.append(f"set_property BEL {bel} [get_cells -hierarchical {{*taps_sampled_d1_reg[{t}]}}]")
        out.append(f"set_property BEL {bel} [get_cells {{u_tdc/taps_sampled_d1_reg[{t}]}}]")
        out.append(
            f"set_property LOC SLICE_X43Y{k} [get_cells -hierarchical {{*taps_sampled_d1_reg[{t}]}}]"
        )
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stages", type=int, default=112, help="캐리체인 단수 (탭 수 = 단수 x 4)")
    ap.add_argument("--xdc", default=None, help="대상 XDC (기본 ../RTL/tdc_zedboard.xdc)")
    ap.add_argument("--check", action="store_true", help="파일을 고치지 않고 현재 상태만 보고")
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    xdc_path = args.xdc or os.path.join(here, "..", "RTL", "tdc_zedboard.xdc")
    xdc_path = os.path.normpath(xdc_path)

    if args.stages % 16 != 0:
        print(f"[!] 단수 {args.stages} 가 16의 배수가 아니다 — popcount 트리가 안 떨어진다.")
        sys.exit(1)
    if args.stages * 4 > 448:
        print(f"[!] 탭 수 {args.stages * 4} > 448 — sum_fine 이 9비트를 넘는다.")
        sys.exit(1)
    if args.stages > 150:
        print(f"[!] 단수 {args.stages} > 150 — SLICE_X42/X43 열이 Y149 까지밖에 없다.")
        sys.exit(1)

    with open(xdc_path, encoding="utf-8") as f:
        lines = f.read().splitlines()

    # 기존 체인 블록의 범위를 찾는다
    starts = [i for i, l in enumerate(lines) if FIRST_LINE_RE.match(l)]
    if len(starts) != 1:
        print(f"[!] 체인 블록 시작줄을 {len(starts)} 개 찾았다 (1개여야 함). 중단.")
        sys.exit(1)
    start = starts[0]
    end = start
    for i in range(start, len(lines)):
        if lines[i].startswith("set_property LOC SLICE_X4") or lines[i].startswith("set_property BEL "):
            end = i
        else:
            break
    old_n = (end - start + 1)
    old_stages = old_n // 25

    print(f"[*] 대상        : {xdc_path}")
    print(f"[*] 기존 체인   : {start + 1}~{end + 1} 줄 = {old_n} 줄 = {old_stages} 단 ({old_stages * 4} 탭)")
    print(f"[*] 새 체인     : {args.stages} 단 ({args.stages * 4} 탭) = {args.stages * 25} 줄")
    print(f"[*] 사용 슬라이스: SLICE_X42Y0~Y{args.stages - 1}, SLICE_X43Y0~Y{args.stages - 1}")

    if old_n % 25 != 0:
        print(f"[!] 기존 블록 줄 수 {old_n} 이 25의 배수가 아니다 — 형식이 예상과 다르다. 중단.")
        sys.exit(1)
    if args.check:
        print("[*] --check 이므로 파일을 고치지 않는다.")
        return

    new_block = []
    for k in range(args.stages):
        new_block += stage_block(k)

    out = lines[:start] + new_block + lines[end + 1:]

    # pblock 은 파이프라인(stg*/mul*/_dN_reg*)용이다.
    #
    # ★ 2026-09-03 : 가로도 같이 넓힌다. 112단 첫 빌드에서 WNS = -0.226 ns 로 타이밍이
    #   깨졌는데, 최악 경로의 지연 중 64~67 %가 배선이었다 (로직은 1.9 ns 뿐).
    #   원인은 X42~X47 6열 중 X42/X43 을 체인이 Y0~Y111 까지 통째로 차지해서
    #   popcount 트리가 실제로 쓸 수 있는 것이 X44~X47 4열뿐이었던 것.
    #   448비트를 112행에 걸쳐 모아야 하는데 통로가 너무 좁았다.
    #   체인 옆으로 18열을 준다 (X42~X59). 체인 자체는 LOC 로 고정돼 있어 안 움직인다.
    pb_y = max(140, args.stages + 30)
    pb_x = 59
    for i, l in enumerate(out):
        if l.startswith("resize_pblock") and "pblock_pipeline" in l:
            out[i] = (
                "resize_pblock [get_pblocks pblock_pipeline] "
                f"-add {{SLICE_X42Y0:SLICE_X{pb_x}Y{pb_y}}}"
            )
            print(f"[*] pblock      : SLICE_X42Y0:SLICE_X{pb_x}Y{pb_y} 로 확대")

    with open(xdc_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")

    print(f"[*] 완료 : 총 {len(out)} 줄")
    print("[!] 합성 후 반드시 확인할 것:")
    print("    get_cells -hier -filter {NAME =~ *u_carry4*} 개수 ==", args.stages)
    print("    LOC 가 안 걸린 체인 셀이 없는지, WNS/WHS 가 음수가 아닌지")


if __name__ == "__main__":
    main()
