# Generated by Claude Code, 2026-09-04
# =============================================================================
# 2026-09-04 ZedBoard 384탭 Mode 1 히스토그램 차트
#
#   입력 : Data/20260904_zed_mode1/tap_histogram_zed_mode1.csv  (Tap_Index,Hit_Count)
#   출력 : Markdown/fig/2026-09-04_*.png  (4장)
#
#   탭 폭 계산 :  w[i] = h[i] / H * 5000 ps      H = 전체 히트 수
#   이 식은 "비동기 히트가 균일하게 도착하면 탭에 떨어지는 빈도는 그 탭의 폭에
#   비례한다" 는 코드밀도 원리다. 링오실레이터는 200 MHz 클럭과 무관하게 발진하므로
#   이 가정이 성립한다.
# =============================================================================
import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

# 한글 폰트 (Windows). 없으면 영문으로 떨어진다.
for fam in ("Malgun Gothic", "NanumGothic", "DejaVu Sans"):
    if any(f.name == fam for f in matplotlib.font_manager.fontManager.ttflist):
        plt.rcParams["font.family"] = fam
        break
plt.rcParams["axes.unicode_minus"] = False

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
CSV = os.path.join(ROOT, "Data", "20260904_zed_mode1", "tap_histogram_zed_mode1.csv")
FIG = os.path.join(ROOT, "Markdown", "fig")
os.makedirs(FIG, exist_ok=True)

# --- 색 (dataviz 기본 팔레트, validate_palette.js 통과) ---
C_MAIN = "#2a78d6"   # slot1 blue   — 단일 계열 기본
CAT4 = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100"]   # tap%4 = 0,1,2,3
INK, INK2, INK3 = "#0b0b0b", "#52514e", "#8a8880"
SURF, GRIDC = "#fcfcfb", "#e3e2dd"

d = np.loadtxt(CSV, delimiter=",", skiprows=1, dtype=np.int64)
tap, h = d[:, 0], d[:, 1].astype(float)
H = h.sum()
w = h / H * 5000.0                       # 탭 폭 [ps]
solid = np.where(h > 1000)[0]            # 실질 유효 탭 (경계 1발짜리 제외)
LO, HI = int(solid.min()), int(solid.max())
NVALID = HI - LO + 1
LSB = 5000.0 / NVALID


def style(ax, xlab, ylab, title=None):
    ax.set_facecolor(SURF)
    ax.grid(True, color=GRIDC, lw=0.8, zorder=0)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    for s in ("left", "bottom"):
        ax.spines[s].set_color(GRIDC)
    ax.tick_params(colors=INK2, labelsize=9, length=0)
    ax.set_xlabel(xlab, color=INK2, fontsize=10)
    ax.set_ylabel(ylab, color=INK2, fontsize=10)
    if title:
        ax.set_title(title, color=INK, fontsize=12, loc="left", pad=10)


# =============================================================================
# 그림 1 — 탭 폭 분포 : 전체 + 끝단 확대
#   목적: "히트가 어디서 멈추는가" 를 한눈에. 이게 오늘의 답이다.
# =============================================================================
fig, (a1, a2) = plt.subplots(1, 2, figsize=(13, 4.6), facecolor=SURF,
                             gridspec_kw={"width_ratios": [2, 1]})

a1.axvspan(HI + 1.5, 383.5, color=GRIDC, alpha=0.75, zorder=1)
a1.plot(tap, w, lw=1.0, color=C_MAIN, zorder=3)
a1.axvline(HI + 1.5, color=INK, lw=1.4, ls="--", zorder=4)
a1.annotate(f"탭 {HI} 에서 멈춘다\n→ 5 ns = {NVALID}칸\n→ LSB {LSB:.3f} ps",
            xy=(HI, 30), xytext=(HI - 150, 44), fontsize=10, color=INK,
            arrowprops=dict(arrowstyle="->", color=INK, lw=1.2), zorder=5)
a1.text(354, 8, f"빈 칸 {383-HI-1}개\n(16 %)", ha="center", fontsize=10, color=INK2, zorder=5)
a1.set_xlim(-4, 388)
a1.xaxis.set_major_locator(MultipleLocator(64))
style(a1, "탭 번호", "탭 폭 [ps]", "384탭 중 실제로 쓰이는 것은 앞 320칸뿐")

z0, z1 = 300, 384
a2.bar(tap[z0:z1], w[z0:z1], width=0.82, color=C_MAIN, zorder=3)
a2.axvspan(HI + 1.5, 383.5, color=GRIDC, alpha=0.75, zorder=1)
a2.annotate(f"탭 {HI+1} : 4.2억 발 중 1발",
            xy=(HI + 1, 0.8), xytext=(HI - 20, 12), fontsize=9, color=INK,
            arrowprops=dict(arrowstyle="->", color=INK, lw=1.1,
                            connectionstyle="arc3,rad=-0.2"), zorder=5)
a2.set_xlim(z0 - 1, z1)
a2.xaxis.set_major_locator(MultipleLocator(20))
style(a2, "탭 번호", "탭 폭 [ps]", "끝단 확대 (탭 300~383)")

fig.tight_layout()
fig.savefig(os.path.join(FIG, "2026-09-04_tap_width.png"), dpi=150, facecolor=SURF)
plt.close(fig)

# =============================================================================
# 그림 2 — 누적 시간 : 몇 번째 탭에서 5000 ps 에 닿는가
#   이것이 곧 "5 ns 를 덮는 데 필요한 탭 수" 의 정의다.
# =============================================================================
cum = np.cumsum(w)
fig, ax = plt.subplots(figsize=(9, 4.6), facecolor=SURF)
ax.axhline(5000, color=INK2, lw=1.4, ls="--", zorder=2)
ax.text(6, 5090, "클럭 한 주기 = 5000 ps", color=INK2, fontsize=10, zorder=4)
ax.plot(tap[:HI + 1], cum[:HI + 1], lw=2.0, color=C_MAIN, zorder=3)
ax.plot([HI], [cum[HI]], "o", ms=8, color=C_MAIN, mec=SURF, mew=2, zorder=5)
ax.annotate(f"탭 {HI} 에서 {cum[HI]:.0f} ps", xy=(HI, cum[HI]),
            xytext=(HI - 170, 4150), fontsize=11, color=INK,
            arrowprops=dict(arrowstyle="->", color=INK, lw=1.2), zorder=5)
ax.axvspan(HI + 1.5, 383.5, color=GRIDC, alpha=0.75, zorder=1)
ax.text(354, 2400, "도달 못 함\n(빈 칸)", ha="center", fontsize=10, color=INK2, zorder=4)
ax.set_xlim(-4, 388)
ax.set_ylim(0, 5600)
ax.xaxis.set_major_locator(MultipleLocator(64))
style(ax, "탭 번호", "누적 시간 [ps]", "지연선을 따라간 누적 시간 — 탭 321에서 5 ns에 닿는다")
fig.tight_layout()
fig.savefig(os.path.join(FIG, "2026-09-04_cumulative.png"), dpi=150, facecolor=SURF)
plt.close(fig)

# =============================================================================
# 그림 3 — tap%4 구조 : CARRY4 한 개 안 4비트의 폭 차이
#   왜 교정이 필요한지를 보여주는 그림.
# =============================================================================
fig, (b1, b2) = plt.subplots(1, 2, figsize=(13, 4.6), facecolor=SURF,
                             gridspec_kw={"width_ratios": [1, 2]})

means = [w[[i for i in range(LO, HI + 1) if i % 4 == m]].mean() for m in range(4)]
bars = b1.bar(range(4), means, width=0.62, color=CAT4, zorder=3)
for i, (bar, v) in enumerate(zip(bars, means)):
    b1.text(bar.get_x() + bar.get_width() / 2, v + 0.7, f"{v:.2f} ps",
            ha="center", fontsize=11, color=INK, zorder=5)
b1.axhline(LSB, color=INK2, lw=1.2, ls="--", zorder=4)
b1.text(3.42, LSB + 0.5, f"평균 {LSB:.2f}", ha="right", fontsize=9, color=INK2, zorder=5)
b1.set_xticks(range(4))
b1.set_xticklabels([f"tap%4\n= {m}" for m in range(4)])
b1.set_ylim(0, 31)
style(b1, "", "평균 탭 폭 [ps]", "CARRY4 안 4비트가 7배 차이난다")

for m in range(4):
    idx = [i for i in range(0, 32) if i % 4 == m]
    b2.bar(idx, w[idx], width=0.82, color=CAT4[m], label=f"tap%4 = {m}", zorder=3)
b2.set_xlim(-1, 32)
b2.xaxis.set_major_locator(MultipleLocator(4))
lg = b2.legend(frameon=False, fontsize=9, ncol=4, loc="upper right")
for t in lg.get_texts():
    t.set_color(INK2)
b2.annotate("탭 3 = 47.96 ps", xy=(3, w[3]), xytext=(5.5, 50), fontsize=9,
            color=INK, arrowprops=dict(arrowstyle="->", color=INK, lw=1.1), zorder=5)
b2.annotate("탭 4 = 0.98 ps", xy=(4, w[4] + 0.4), xytext=(4.6, 9.5), fontsize=9,
            color=INK, arrowprops=dict(arrowstyle="->", color=INK, lw=1.1), zorder=5)
b2.set_ylim(0, 58)
style(b2, "탭 번호", "탭 폭 [ps]", "진입부 32칸 — 눈금 간격이 제각각이다")

fig.tight_layout()
fig.savefig(os.path.join(FIG, "2026-09-04_tap_mod4.png"), dpi=150, facecolor=SURF)
plt.close(fig)

# =============================================================================
# 그림 4 — 세 보드 비교
# =============================================================================
boards = ["회사 Zybo\nXC7Z010", "집 Zybo\nXC7Z010", "ZedBoard\nXC7Z020"]
taps_n = [282, 293, NVALID]
lsbs = [5000 / n for n in taps_n]

fig, (c1, c2) = plt.subplots(1, 2, figsize=(11, 4.2), facecolor=SURF)
for ax, vals, ylab, ttl, fmt in (
        (c1, taps_n, "5 ns 를 덮는 탭 수", "유효 탭 수 — 많을수록 촘촘하다", "{:.0f}칸"),
        (c2, lsbs, "LSB [ps]", "눈금 하나의 크기 — 작을수록 좋다", "{:.3f} ps")):
    bars = ax.bar(range(3), vals, width=0.55, zorder=3,
                  color=[INK3, INK3, C_MAIN])
    for bar, v in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width() / 2, v * 1.015, fmt.format(v),
                ha="center", fontsize=11, color=INK, zorder=5)
    ax.set_xticks(range(3))
    ax.set_xticklabels(boards, fontsize=9)
    ax.set_ylim(0, max(vals) * 1.18)
    style(ax, "", ylab, ttl)
fig.tight_layout()
fig.savefig(os.path.join(FIG, "2026-09-04_boards.png"), dpi=150, facecolor=SURF)
plt.close(fig)

print(f"H = {H:,}   유효탭 {LO}~{HI} = {NVALID}칸   LSB = {LSB:.3f} ps")
print("tap%4 평균 폭 :", "  ".join(f"{m}:{v:.2f}ps" for m, v in enumerate(means)))
print(f"빈 칸(카운트 0) : 탭 {HI+2}~383 = {383-HI-1}개")
print(f"폭 <0.5/<1/<2 ps : {(w[LO:HI+1]<0.5).sum()} / {(w[LO:HI+1]<1).sum()} / {(w[LO:HI+1]<2).sum()}개")
_s = w[LO:HI+1]
print(f"폭 최소/중앙/평균/최대 : {_s.min():.2f} / {np.median(_s):.2f} / {_s.mean():.2f} / {_s.max():.2f} ps")
print(f"양자화 한계 sigma = {np.sqrt((_s**3).sum()/(12*_s.sum())):.2f} ps")
print("저장:", ", ".join(sorted(f for f in os.listdir(FIG) if f.startswith("2026-09-04"))))
