/* Generated by Claude Code, 2026-09-06
 * =============================================================================
 * main.c  —  TDC 검증용 고정 주파수 신호원 (STM32, TIM1 CH1 PWM)
 *
 *  [왜 고정 주파수인가]
 *  chirp 로는 TDC 측정 오차의 정체를 못 가린다. chirp 은 간격 길이와 램프 위치가
 *  함께 변해 두 변수가 얽히기 때문이다. 고정 주파수면 참값이 하나뿐이라
 *  **잰 간격들이 흩어진 정도가 곧 측정 오차**다. 격자 맞춤도 필요 없다.
 *
 *  [지금까지 알아낸 것 — 2026-09-06 실측]
 *    ZedBoard TDC 로 이 신호를 재면 간격 오차가 약 415~430 ps 나온다.
 *    TDC 의 이론 한계(양자화)는 7.07 ps 이므로 59 배다.
 *    다음이 배제되었다:
 *      - 지연선 탭 폭 불균일  (코드밀도 교정을 해도 안 줄어든다)
 *      - fine 값 의존성       (상관계수 +0.010)
 *      - STM32 클럭 '정확도'  (HSI -> HSE 로 바꿔 5배 정확해져도 그대로)
 *    남은 후보는 '정확도' 가 아니라 '주기마다의 흔들림(지터)' 이다:
 *      - STM32 의 PLL 지터
 *      - ZedBoard 쪽 클럭 지터 (PS 크리스털 -> PS PLL -> FCLK -> MMCM -> 200 MHz)
 *
 *  [이 코드로 할 실험 두 가지]
 *   (1) 주파수를 바꿔가며 잰다 (FIXED_FREQ_HZ 를 100k / 300k / 1M 으로)
 *       오차가 간격에 비례해 커지면 -> 클럭 지터가 쌓이는 것
 *       오차가 간격과 무관하면     -> 에지 하나를 찍는 오차
 *   (2) DMA 를 쓸 때와 안 쓸 때를 비교한다 (USE_DMA 0/1)
 *       매 주기 DMA 버스트가 도는 것 자체가 지터원일 수 있다.
 *       이건 원래 chirp 코드에는 없던 검사다.
 *
 *  [쓰는 법]
 *    아래 ★ 표시된 곳만 보면 된다. USER CODE 구간 밖은 CubeMX 가 만든 것 그대로다.
 *    ※ SystemClock_Config 는 **여러분이 HSE 로 이미 바꾼 것을 그대로 쓰십시오.**
 *      이 파일의 것은 참고용이며, 보드마다 HSE 가 크리스털인지 ST-LINK 가 주는
 *      클럭 신호인지가 달라 잘못 넣으면 부팅이 안 됩니다.
 * =============================================================================
 */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "dma.h"
#include "tim.h"
#include "gpio.h"

/* USER CODE BEGIN PD */

/* ★★★ 여기 두 개만 바꾸면 됩니다 ★★★ */

/* 내보낼 주파수 [Hz].
 *   실험 (1) 을 하려면 이 값을 바꿔 세 번 빌드해 각각 재십시오.
 *     100000.0f  -> 간격 10.000 us  (ARR+1 = 1700)
 *     300000.0f  -> 간격  3.333 us  (ARR+1 =  567)
 *    1000000.0f  -> 간격  1.000 us  (ARR+1 =  170)
 *   ※ TIM1 의 ARR 은 16비트다. 170 MHz 기준 f >= 2.6 kHz 여야 한다.
 */
#define FIXED_FREQ_HZ       100000.0f

/* 1 = 기존 chirp 코드와 똑같이 DMA 버스트로 매 주기 ARR 를 다시 쓴다
 *     (LUT 값이 전부 같으므로 주파수는 고정된다. 하드웨어 경로가 chirp 때와
 *      완전히 같아 비교가 공정하다.)
 * 0 = DMA 를 아예 안 쓴다. ARR 를 한 번만 설정하고 타이머가 자유 실행한다.
 *     (DMA 버스트 자체가 지터원인지 가리는 대조군)
 */
#define USE_DMA             1

/* ---- 아래는 원래 코드의 값을 그대로 둔 것 ---- */
#define TIMER_CLK           170000000.0f  /* TIM1 클럭 [Hz]. SystemClock 과 맞출 것 */

#define MAX_PULSES          512           /* chirp 때 3000 이었으나 고정이면 이만큼 필요 없다 */

typedef struct {
    uint32_t arr;
    uint32_t rcr;
    uint32_t ccr;
} TimerConfig_t;

TimerConfig_t chirp_lut[MAX_PULSES];
uint32_t total_pulses = 0;

/* 확인용 — 디버거로 들여다보면 실제로 나가는 값이 보인다 */
volatile uint32_t g_arr_plus1 = 0;        /* 한 주기의 눈금 수 */
volatile float    g_actual_freq = 0.0f;   /* 반올림 뒤 실제 주파수 [Hz] */

/* USER CODE END PD */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */
void Generate_Fixed_LUT(void);
/* USER CODE END PFP */

/**
  * @brief  The application entry point.
  */
int main(void)
{
  HAL_Init();

  /* ※ 여러분이 HSE 로 바꾼 SystemClock_Config 를 그대로 쓰십시오. */
  SystemClock_Config();

  MX_GPIO_Init();
  MX_DMA_Init();
  MX_TIM1_Init();

  /* USER CODE BEGIN 2 */

  Generate_Fixed_LUT();

  /* ★ 프리스케일러를 0 으로 못 박는다.
   *   CubeMX 가 PSC 를 0 이 아닌 값으로 만들어 두면 눈금이 170 MHz 가 아니게 되어
   *   위 계산이 전부 틀어진다. 타이머를 켜기 전에 확정한다. */
  __HAL_TIM_SET_PRESCALER(&htim1, 0);

  /* ★ 첫 주기부터 원하는 값이 나가도록 ARR/CCR 을 미리 넣는다.
   *   DMA 를 쓰더라도 첫 update event 전까지는 이 값이 쓰인다. */
  __HAL_TIM_SET_AUTORELOAD(&htim1, chirp_lut[0].arr);
  __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, chirp_lut[0].ccr);

  HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);

#if USE_DMA
  /* chirp 때와 똑같은 경로. LUT 값이 전부 같아 주파수만 고정된다.
   * TIM_DMABASE_ARR 부터 3워드 = ARR, RCR, CCR1 (레지스터 순서와 일치) */
  HAL_TIM_DMABurst_MultiWriteStart(
      &htim1,
      TIM_DMABASE_ARR,
      TIM_DMA_UPDATE,
      (uint32_t*)chirp_lut,
      TIM_DMABURSTLENGTH_3TRANSFERS,
      total_pulses * 3
  );
#endif

  /* USER CODE END 2 */

  while (1)
  {
  }
}

/* USER CODE BEGIN 4 */

/**
  * @brief  LUT 을 전부 같은 값으로 채운다 = 고정 주파수.
  *
  *  원래 Generate_Chirp_LUT 과 산술을 똑같이 맞췄다 (반올림 방식까지).
  *  그래야 chirp 결과와 나란히 놓고 비교할 수 있다.
  */
void Generate_Fixed_LUT(void)
{
    float    period_ticks = TIMER_CLK / FIXED_FREQ_HZ;
    uint32_t arr_val = (uint32_t)(period_ticks + 0.5f) - 1;
    uint32_t ccr_val = (arr_val + 1) / 2;          /* 듀티 50 % */
    uint32_t i;

    for (i = 0; i < MAX_PULSES; i++) {
        chirp_lut[i].arr = arr_val;
        chirp_lut[i].rcr = 0;
        chirp_lut[i].ccr = ccr_val;
    }
    total_pulses = MAX_PULSES;

    /* 확인용 : 반올림 때문에 요청 주파수와 실제 주파수가 조금 다르다.
     * 예) 100 kHz 요청 -> ARR+1 = 1700 -> 실제 100.000 kHz (딱 맞음)
     *     300 kHz 요청 -> ARR+1 =  567 -> 실제 299.824 kHz (-0.06 %)
     * TDC 쪽 분석은 실제 값을 데이터에서 다시 구하므로 문제되지 않는다. */
    g_arr_plus1   = arr_val + 1;
    g_actual_freq = TIMER_CLK / (float)(arr_val + 1);
}

/* USER CODE END 4 */

void Error_Handler(void)
{
  __disable_irq();
  while (1)
  {
  }
}
